/** Traduzioni, parte 3. Vedi traduzioni.ts per il criterio delle chiavi. */
export const PARTE_3: Record<string, string> = {
  // --- anagrafica e ruoli ---
  'Leave blank to auto-generate an avatar': "Lascia vuoto per generare un'immagine",
  'Location': 'Sede',
  'Manage': 'Gestisci',
  'Manage Role & Permissions': 'Gestisci ruolo e permessi',
  'Manage Team': 'Gestisci il team',
  'Manage Users': 'Gestisci utenti',
  'Manage all users and departments': 'Gestisci tutti gli utenti e i dipartimenti',
  'Manage tasks within their department(s)': 'Gestisce le attività dei propri dipartimenti',
  'Manage your team members, roles, and departments':
    'Gestisci le persone del team, i ruoli e i dipartimenti',
  "Manage your team's work efficiently": 'Organizza il lavoro del tuo team',
  'Manager': 'Manager',
  'Manager (Department Admin)': 'Manager (responsabile di dipartimento)',
  'Member': 'Membro',
  'Name': 'Nome',
  'Name and role are required': 'Nome e ruolo sono obbligatori',
  'Phone Number': 'Numero di telefono',
  'Role': 'Ruolo',
  'Role and permissions updated successfully': 'Ruolo e permessi aggiornati',
  'Need different permissions?': 'Ti servono permessi diversi?',
  'Override default role permissions with custom settings':
    'Sostituisci i permessi predefiniti del ruolo con impostazioni personalizzate',
  'Permission Status': 'Stato dei permessi',
  'Search by name, role, email, department, skills...':
    'Cerca per nome, ruolo, email, dipartimento, competenze...',
  'Select All': 'Seleziona tutto',
  'Set Active': 'Segna come attivo',
  'Set Inactive': 'Segna come non attivo',
  'Senior Developer': 'Sviluppatore senior',
  'San Francisco, CA': 'Milano, Italia',
  'New York, Remote...': 'Roma, da remoto...',
  'React, TypeScript, Node.js': 'React, TypeScript, Node.js',

  // --- dipartimenti ---
  'No Department Data': 'Nessun dato sui dipartimenti',
  'No department data available': 'Nessun dato disponibile sui dipartimenti',
  'No departments selected. Add departments above.':
    'Nessun dipartimento selezionato. Aggiungine uno qui sopra.',
  'No departments yet': 'Ancora nessun dipartimento',
  'No employees assigned to this department': 'Nessuna persona assegnata a questo dipartimento',
  'Multi-metric comparison across departments': 'Confronto su più indicatori fra dipartimenti',
  'Quick insights for your departments': 'Sguardo rapido sui tuoi dipartimenti',
  'Quick-start templates for common department types. Choose individual departments or create entire categories at once.':
    'Modelli pronti per i dipartimenti più comuni. Scegli un singolo dipartimento o crea intere categorie in una volta.',
  'Replace all departments': 'Sostituisci tutti i dipartimenti',
  'Require Department Assignment': "Richiedi l'assegnazione a un dipartimento",
  'Select All Departments': 'Seleziona tutti i dipartimenti',
  'Select a team lead (optional)': 'Scegli un responsabile (facoltativo)',
  'Set department leads': 'Imposta i responsabili dei dipartimenti',
  'Please select at least one department': 'Seleziona almeno un dipartimento',

  // --- attività ---
  'Low Priority': 'Priorità bassa',
  'Medium': 'Media',
  'Medium Priority': 'Priorità media',
  'My Dashboard': 'Il mio cruscotto',
  'My Tasks': 'Le mie attività',
  'Match skills and departments': 'Fa combaciare competenze e dipartimenti',
  'New Task Assigned': 'Nuova attività assegnata',
  'New Comment': 'Nuovo commento',
  'New Announcement': 'Nuovo annuncio',
  'Not Started Tasks': 'Attività da iniziare',
  'No task data available yet': 'Ancora nessun dato sulle attività',
  'No tasks found': 'Nessuna attività trovata',
  'No unassigned tasks to assign': 'Nessuna attività da assegnare',
  'No upcoming deadlines in the next 3 days': 'Nessuna scadenza nei prossimi 3 giorni',
  'Overdue Tasks': 'Attività in ritardo',
  'Overdue tasks (priority)': 'Attività in ritardo (priorità)',
  'Priority Breakdown': 'Ripartizione per priorità',
  'Priority Distribution': 'Distribuzione delle priorità',
  'Priority Warnings': 'Avvisi di priorità',
  'Please enter a task title first': "Scrivi prima il titolo dell'attività",
  'Reminder Before Due (days)': 'Promemoria prima della scadenza (giorni)',
  'Require Task Approval': "Richiedi l'approvazione delle attività",
  'Requiring immediate attention': 'Richiedono attenzione immediata',
  'Needs Attention': 'Richiede attenzione',
  'Need attention': 'Richiedono attenzione',
  'Review the suggested task assignments below. These are optimized for workload balance and task requirements.':
    'Rivedi le assegnazioni proposte qui sotto: tengono conto del carico di lavoro e dei requisiti delle attività.',
  'Review the suggestions before applying them.': 'Rivedi i suggerimenti prima di applicarli.',

  // --- messaggi vuoti ---
  'No active employees available': 'Nessuna persona attiva disponibile',
  'No activity yet': 'Ancora nessuna attività',
  'No announcements': 'Nessun annuncio',
  'No attachments yet': 'Ancora nessun allegato',
  'No audit entries yet': 'Ancora nessuna voce nel registro',
  'No click data available': 'Nessun dato sui clic',
  'No comments yet': 'Ancora nessun commento',
  'No feedback yet': 'Ancora nessun riscontro',
  'No insights available yet': 'Ancora nessuna analisi disponibile',
  'No notifications': 'Nessuna notifica',
  'No performance data available': 'Nessun dato sulle prestazioni',
  'No team members found': 'Nessuna persona trovata',
  'No team members yet. Add team members to see analytics.':
    'Ancora nessuna persona nel team. Aggiungine per vedere le analisi.',
  'None': 'Nessuno',

  // --- notifiche ---
  'Mark all read': 'Segna tutte come lette',
  'Mark as read': 'Segna come letta',
  'Muted': 'Silenziate',
  'Notification Frequency': 'Frequenza delle notifiche',
  'Notification Retention (days)': 'Conservazione delle notifiche (giorni)',
  'Notification Settings': 'Impostazioni delle notifiche',
  'Notification Sounds': 'Suoni delle notifiche',
  'Notification Type': 'Tipo di notifica',
  'Notification Types': 'Tipi di notifica',
  'Notifications': 'Notifiche',
  'Notifications will be paused between these times':
    'Le notifiche saranno sospese in questa fascia oraria',
  'Notify when attachments are excluded': 'Avvisa quando un allegato viene escluso',
  'Pause notifications during specific times': 'Sospendi le notifiche in certe fasce orarie',
  'Play sounds when notifications arrive': "Riproduci un suono all'arrivo di una notifica",
  'Quiet Hours': 'Orari di silenzio',
  'Quiet Hours Active': 'Orari di silenzio attivi',
  'Real-time': 'In tempo reale',
  'Receive notifications': 'Ricevi le notifiche',
  'Receive notifications via email': 'Ricevi le notifiche via email',
  'Receive real-time alerts on your desktop for important task updates':
    'Ricevi avvisi immediati sul desktop per gli aggiornamenti importanti',
  'Send Test Notification': 'Invia una notifica di prova',

  // --- email ---
  'Max Attachment Size (MB)': 'Dimensione massima allegato (MB)',
  'Maximum single attachment size': 'Dimensione massima di un singolo allegato',
  'Maximum total attachment size per email': 'Dimensione massima totale degli allegati',
  'Most email providers have attachment size limits. SendGrid and Resend both support up to 25MB total.':
    'Quasi tutti i provider hanno un limite per gli allegati: SendGrid e Resend arrivano a 25 MB complessivi.',
  'Most popular links in your emails': 'Link più cliccati nelle tue email',
  'Office Documents': 'Documenti Office',
  'PDF Documents': 'Documenti PDF',
  'Open Rate': 'Percentuale di apertura',
  'Opened': 'Aperte',
  'Open and click rates for different email types':
    'Aperture e clic per tipo di email',
  'Percentage of opened emails that received clicks':
    'Percentuale di email aperte che hanno ricevuto un clic',
  'Performance by Email Type': 'Prestazioni per tipo di email',
  'Plain Text': 'Testo semplice',
  'Preview': 'Anteprima',
  'Recent Deliveries': 'Consegne recenti',
  'Recipient': 'Destinatario',
  'Resend': 'Resend',
  'SendGrid': 'SendGrid',
  'Sent': 'Inviate',
  'Set maximum file sizes for email attachments':
    'Imposta le dimensioni massime degli allegati',
  'Save Template': 'Salva il modello',

  // --- sistema ---
  'MM/DD/YYYY': 'MM/GG/AAAA',
  'Maintenance Mode': 'Modalità di manutenzione',
  'Max AI Requests Per Day': 'Richieste AI massime al giorno',
  'Max Login Attempts': 'Tentativi di accesso massimi',
  'Monday': 'Lunedì',
  'Mountain Time': 'Fuso orario delle Montagne Rocciose',
  'Pacific Time': 'Fuso orario del Pacifico',
  'London': 'Londra',
  'Paris': 'Parigi',
  'Password Expiry (days)': 'Scadenza della password (giorni)',
  'Permanently delete all audit log entries. This action cannot be undone.':
    'Elimina definitivamente tutte le voci del registro. Non è reversibile.',
  'Permanently delete all tasks, employees, and settings':
    'Elimina definitivamente attività, persone e impostazioni',
  'Require 2FA for all users': "Richiedi l'autenticazione a due fattori a tutti",
  'Require Email Verification': "Richiedi la verifica dell'email",
  'Require Strong Passwords': 'Richiedi password robuste',
  'Reset': 'Ripristina',
  'Reset to Default': 'Riporta al valore predefinito',
  'Reset to Defaults': 'Riporta ai valori predefiniti',
  'Restore': 'Ripristina',
  'Restore from a previous backup file': 'Ripristina da un file di backup',
  'Restore system data from a previously exported backup file.':
    'Ripristina i dati da un backup esportato in precedenza.',
  'Save': 'Salva',
  'Save Changes': 'Salva le modifiche',
  'Save Settings': 'Salva le impostazioni',
  'Security': 'Sicurezza',
  'Security Settings': 'Impostazioni di sicurezza',
  'Security Status': 'Stato della sicurezza',
  'Security policies and audit configuration':
    'Regole di sicurezza e configurazione del registro',
  'Session Timeout (minutes)': 'Scadenza della sessione (minuti)',
  'Set expiration date': 'Imposta una data di scadenza',
  'Please set an expiry date': 'Imposta una data di scadenza',
  'Overview': 'Riepilogo',
  'Overall Summary': 'Riepilogo generale',
  'Quick Actions': 'Azioni rapide',
  'Quick Info': 'Informazioni rapide',
  'Quick Presets': 'Preimpostazioni',
  'Recent Activity': 'Attività recente',
  'Recent Audit Log': 'Registro recente',
  'Refresh': 'Aggiorna',
  'Previous': 'Precedente',
  'Next': 'Avanti',
  'Rate': 'Valuta',
  'Recommendations': 'Consigli',
  'Review': 'Rivedi',
  'Reviewing': 'In revisione',
  'Review and manage feedback from your team members':
    'Leggi e gestisci i riscontri del team',
  'Performance': 'Prestazioni',
  'Performance Patterns': 'Andamento delle prestazioni',
  'Message': 'Messaggio',
  'Most Popular': 'Più popolari',
  'Most Recent': 'Più recenti',
  'Other': 'Altro',
  'Pinned': 'In evidenza',
  'Planned': 'Pianificato',
  'Praise': 'Complimenti',
  'Praise & Thanks': 'Complimenti e ringraziamenti',
  'Post Announcement': 'Pubblica annuncio',
  'New 30d': 'Nuovi in 30 giorni',
  'Questions or need help? Check the Help Documentation or contact your administrator.':
    'Domande o bisogno di aiuto? Consulta la documentazione o contatta un amministratore.',

  // --- validazioni ---
  'Please enter a message': 'Scrivi un messaggio',
  'Please enter a title': 'Scrivi un titolo',
  'Please enter a valid email address': 'Inserisci un indirizzo email valido',
  'Please provide a description': 'Aggiungi una descrizione',
  'Please provide a title': 'Aggiungi un titolo',
  'Please provide as much detail as possible...': 'Descrivi il più possibile...',
  'PDF report will open in print dialog':
    'Il report PDF si aprirà nella finestra di stampa',

  // --- testi gia in italiano, versione inglese ---
  'Rimossa dalla configurazione una chiave API salvata dalla versione precedente: le chiavi vivono solo lato server.':
    'Removed an API key saved by the previous version: keys live only on the server.',
  'Se stai leggendo questo messaggio, la configurazione di invio lato server funziona.':
    'If you are reading this, server-side email delivery is working.',
  'Sessione scaduta, accedi di nuovo': 'Session expired, sign in again',
  'Serve il ruolo': 'Requires the role',
  'Invio di prova': 'Test send',
  'Indica un indirizzo a cui inviare la prova': 'Enter an address to send the test to',
  'Le funzioni AI non sono attive': 'AI features are not active',
};
