/** Traduzioni, parte 4. Vedi traduzioni.ts per il criterio delle chiavi. */
export const PARTE_4: Record<string, string> = {
  // --- impostazioni ---
  'Settings Version': 'Versione delle impostazioni',
  'Settings reset to defaults': 'Impostazioni riportate ai valori predefiniti',
  'Settings saved successfully!': 'Impostazioni salvate',
  'Size Limits': 'Limiti di dimensione',
  'Slack Webhook URL': 'URL del webhook Slack',
  'Webhook URL': 'URL del webhook',
  'Smart Suggestions': 'Suggerimenti intelligenti',
  'Sort by': 'Ordina per',
  'Spanish': 'Spagnolo',
  'Standard Departments': 'Dipartimenti standard',
  'Start Time': 'Ora di inizio',
  'Storage Information': 'Occupazione dei dati',
  'Sunday': 'Domenica',
  'System Notifications': 'Notifiche di sistema',
  'System Overview': 'Quadro del sistema',
  'System Settings': 'Impostazioni di sistema',
  'System is currently in maintenance mode': 'Il sistema è in modalità di manutenzione',
  'System-wide notification configuration': 'Configurazione generale delle notifiche',
  'Timezone': 'Fuso orario',
  'Tokyo': 'Tokyo',
  'Week Start Day': 'Primo giorno della settimana',
  'YYYY-MM-DD': 'AAAA-MM-GG',
  'Templates': 'Modelli',
  'Template reset to default. Click Save to apply changes.':
    'Modello riportato al valore predefinito. Premi Salva per applicare.',
  'Use Template': 'Usa il modello',
  'Type': 'Tipo',
  'Title': 'Titolo',
  'Subject': 'Oggetto',
  'Subject Line': 'Oggetto',
  'Text Files': 'File di testo',
  'Total': 'Totale',
  'Unsaved Changes': 'Modifiche non salvate',
  'Track all system changes and actions': 'Traccia tutte le modifiche e le azioni',
  'Track and manage department budgets': 'Traccia e gestisci i budget dei dipartimenti',
  'Trends': 'Andamento',
  'Try Again': 'Riprova',
  'Volume': 'Volume',
  'Test Sounds': 'Prova i suoni',
  'Test notification sent!': 'Notifica di prova inviata',
  'Tests Passed': 'Test superati',

  // --- team e analisi ---
  'Team': 'Team',
  'Team Analytics': 'Analisi del team',
  'Team Analytics Report': 'Report di analisi del team',
  'Team Feedback Board': 'Bacheca dei riscontri',
  'Team Lead': 'Responsabile del team',
  'Team Leads': 'Responsabili del team',
  'Team Member Details': 'Dettagli della persona',
  'Team Members': 'Membri del team',
  'Team Performance': 'Prestazioni del team',
  'Team Performance Overview': 'Quadro delle prestazioni del team',
  'Team member updated successfully!': 'Persona aggiornata',
  'Team members will be notified of new comments on their assigned tasks.':
    'Le persone vengono avvisate dei nuovi commenti sulle attività loro assegnate.',
  'Team members with overdue or high-priority tasks':
    'Persone con attività in ritardo o ad alta priorità',
  'Team size distribution': 'Distribuzione della dimensione dei team',
  'Top Performer': 'Miglior risultato',
  'Top Performers': 'Migliori risultati',
  'Top Performing': 'Con i risultati migliori',
  'Total Departments': 'Dipartimenti totali',
  'Total Employees': 'Persone totali',
  'Total Feedback': 'Riscontri totali',
  'Total Members': 'Membri totali',
  'Total Team Members': 'Membri totali del team',
  'Total Sent': 'Inviate in totale',
  'Total tasks per department': 'Attività totali per dipartimento',
  'With Leads': 'Con responsabile',
  'Workload Alerts': 'Avvisi sul carico di lavoro',
  'Workload Analysis': 'Analisi del carico di lavoro',
  'Workload Distribution': 'Distribuzione del carico di lavoro',
  'Workload by Department': 'Carico di lavoro per dipartimento',
  'Target Departments': 'Dipartimenti interessati',
  'Task Distribution by Department': 'Distribuzione delle attività per dipartimento',
  'Task breakdown by team member': 'Ripartizione delle attività per persona',
  'Tasks by priority level': 'Attività per livello di priorità',
  'Tasks completed over the last 7 days': 'Attività completate negli ultimi 7 giorni',
  'Tasks due within 24 hours (priority)': 'Attività in scadenza entro 24 ore (priorità)',
  'Task Completion Trend': 'Andamento dei completamenti',
  'Task Status Distribution': 'Distribuzione degli stati',
  'Super Admin Dashboard': 'Cruscotto del super amministratore',
  'Upcoming Deadlines': 'Prossime scadenze',
  'Unassigned': 'Non assegnata',
  'Unassigned Tasks': 'Attività non assegnate',

  // --- attività, notifiche ed eventi ---
  'Task Creation': 'Creazione di attività',
  'Task Management': 'Gestione delle attività',
  'Task Priority Updated': "Priorità dell'attività aggiornata",
  'Task Questions': 'Domande sulle attività',
  'Task Reassigned to You': 'Attività riassegnata a te',
  'Task Status Updated': "Stato dell'attività aggiornato",
  'Task Updated': 'Attività aggiornata',
  'Task assignments and updates': 'Assegnazioni e aggiornamenti delle attività',
  'Status changes': 'Cambi di stato',
  'This is a reminder that your task is due soon.':
    'Promemoria: la tua attività è in scadenza.',
  'Your task is now overdue and requires immediate attention.':
    'La tua attività è in ritardo e richiede attenzione immediata.',
  'This action cannot be undone. This will permanently delete the task from your workspace.':
    "Questa operazione non è reversibile: l'attività verrà eliminata definitivamente.",
  'Update the task details below.': "Aggiorna i dettagli dell'attività qui sotto.",
  'Upload Attachment': 'Carica un allegato',
  'Urgent': 'Urgente',
  'You Were Mentioned': 'Sei stato menzionato',
  'View Task Now': 'Apri subito',
  'View Comment': 'Vedi il commento',
  'View My Tasks': 'Le mie attività',
  'View All Tasks': 'Tutte le attività',
  'View All': 'Vedi tutto',
  'View Overdue': 'Vedi in ritardo',
  'View': 'Vedi',
  'View details & comments': 'Dettagli e commenti',
  'When you have unassigned tasks, click': 'Quando hai attività non assegnate, premi',

  // --- utenti e permessi ---
  'User Management': 'Gestione utenti',
  'User Role': 'Ruolo utente',
  'User account policies and defaults': 'Regole e impostazioni predefinite degli account',
  'User data exported successfully!': 'Dati degli utenti esportati',
  'User not loaded': 'Utente non caricato',
  'Users': 'Utenti',
  'Users can belong to multiple departments': 'Le persone possono stare in più dipartimenti',
  'Users must be assigned to at least one department':
    'Ogni persona deve appartenere ad almeno un dipartimento',
  'Viewer': 'In sola lettura',
  'View all analytics and reports': 'Vede tutte le analisi e i report',
  'View and update their own tasks': 'Vede e aggiorna le proprie attività',
  'View department analytics': 'Vede le analisi del dipartimento',
  'View your current role and permissions': 'Vedi il tuo ruolo e i tuoi permessi',
  'Your Access Level': 'Il tuo livello di accesso',
  'You do not have permission to manage roles': 'Non hai il permesso di gestire i ruoli',
  'You do not have permission to manage user roles. Only administrators can modify roles and permissions.':
    'Non hai il permesso di gestire i ruoli: solo gli amministratori possono modificarli.',
  'Update department information and settings':
    'Aggiorna informazioni e impostazioni del dipartimento',
  'Update team member information': 'Aggiorna le informazioni della persona',
  'Update Announcement': 'Aggiorna annuncio',
  'Use AI features': 'Usa le funzioni AI',

  // --- riscontri ---
  'Share Feedback Now': 'Lascia un riscontro',
  'Share Your Feedback': 'Dicci cosa ne pensi',
  'Submit Feedback': 'Invia il riscontro',
  'Suggested Deadline': 'Scadenza suggerita',
  'Suggestion applied!': 'Suggerimento applicato',
  'Thank you for your feedback! 🎉': 'Grazie per il tuo riscontro',
  'Thank You for Being Part of Our Launch': 'Grazie per essere con noi al lancio',
  'We Need Your Feedback!': 'Ci serve il tuo parere',
  'Welcome to your new team productivity platform':
    'Benvenuto nella nuova piattaforma di lavoro del team',
  'You must be logged in to submit feedback': 'Devi accedere per inviare un riscontro',
  'You must be logged in to upvote': 'Devi accedere per votare',
  'There are no active announcements for your departments':
    'Non ci sono annunci attivi per i tuoi dipartimenti',
  'Skip Tour': 'Salta la presentazione',
  'Your Achievements': 'I tuoi risultati',

  // --- aiuto ---
  'What are AI Insights?': 'Cosa sono le analisi AI?',
  'What are the different user roles?': 'Quali sono i ruoli utente?',
  'What can the AI Assistant do?': "Cosa può fare l'assistente AI?",
  'Yes! In the analytics view, click the': "Sì. Nella vista analisi, premi",
  'Yes! Open the task details dialog and go to the':
    "Sì. Apri i dettagli dell'attività e vai su",
  'When enabled, task attachments will be included in notification emails':
    'Se attivo, gli allegati delle attività vengono inclusi nelle email di notifica',
  'Total size of all attachments in a single email cannot exceed this limit':
    'La dimensione totale degli allegati di una email non può superare questo limite',
  'Show notifications outside the browser': 'Mostra le notifiche fuori dal browser',
  'Your browser does not support desktop notifications':
    'Il tuo browser non supporta le notifiche desktop',
  'Your data is automatically saved in your browser. Use':
    'I dati vengono salvati automaticamente. Usa',
  'Your data is automatically saved in your browser. Use backup to preserve data before major changes.':
    'I dati vengono salvati automaticamente. Fai un backup prima di modifiche importanti.',
  'This will overwrite all existing data. Make sure to export current data first.':
    'Questa operazione sovrascrive tutti i dati esistenti: esporta prima quelli attuali.',

  // --- errori di runtime ---
  'This spark has encountered a runtime error': "L'applicazione ha incontrato un errore",
  'Something unexpected happened while running the application. The error details are shown below. Contact the spark author and let them know about this issue.':
    "Si è verificato un errore imprevisto. I dettagli sono qui sotto: segnalali a chi gestisce l'applicazione.",
};
