/**
 * Traduzioni, parte 5: le voci sfuggite alla sostituzione automatica.
 *
 * Sono soprattutto testi affiancati a un'icona dentro lo stesso elemento —
 * `<Button><Icona />My Permissions</Button>` — dove il testo non e' delimitato
 * da due tag e quindi non veniva riconosciuto. Sostituite a mano.
 */
export const PARTE_5: Record<string, string> = {
  'My Permissions': 'I miei permessi',
  'Avg Completion Time': 'Tempo medio di completamento',
  'Avg Tasks/Employee': 'Attività medie per persona',
  'Count': 'Numero',
  'Low': 'Bassa',
  'Metric': 'Indicatore',
  'Total Assigned Tasks': 'Attività assegnate in totale',
  'Value': 'Valore',
  'Generated': 'Generato il',
  'days': 'giorni',
  'Joined': 'Iscritto',
  'All': 'Tutti',
  'tasks': 'attività',
  'task': 'attività',
  'more': 'altre',
  'This user has': 'Questa persona ha',
  'assigned task(s). Those tasks will become unassigned.':
    'attività assegnate, che resteranno senza assegnatario.',
  'This action cannot be undone and any assigned tasks will become unassigned.':
    'Operazione non reversibile: le attività assegnate resteranno senza assegnatario.',
  'active': 'attivo',
  'inactive': 'non attivo',
  'Feedback Board': 'Bacheca dei riscontri',
  'Announcements': 'Annunci',
  'Skills (comma-separated)': 'Competenze (separate da virgola)',
  'Task created successfully!': 'Attività creata',
  'Task updated successfully!': 'Attività aggiornata',
  'Task reassigned successfully!': 'Attività riassegnata',
  'Task deleted': 'Attività eliminata',
  'Task completed!': 'Attività completata',
  'Task status distribution across departments':
    'Distribuzione degli stati fra i dipartimenti',
  'Top Clicked Links': 'Link più cliccati',
  'Visual reference for department color coding and icons used throughout the app':
    "Riferimento visivo dei colori e delle icone dei dipartimenti usati nell'applicazione",
  'TaskFlow Help & Documentation': 'Guida e documentazione',
  'TaskFlow is Production Ready!': 'TaskFlow è pronto per la produzione',
  "Get your webhook URL from Slack's Incoming Webhooks app":
    "Trova l'URL del webhook nell'app Incoming Webhooks di Slack",
  'TaskFlow Analytics - Team Performance Report':
    'TaskFlow - Report sulle prestazioni del team',
  'TaskFlow Analytics - Department Performance Report':
    'TaskFlow - Report sulle prestazioni per dipartimento',
  '{n}% complete': '{n}% completato',
  '{n} tasks/user': '{n} attività per utente',
  '{n} announcements': '{n} annunci',
  '{n} unassigned': '{n} senza assegnatario',
  'Last modified: {data} by {autore}': 'Ultima modifica: {data} da {autore}',
  'Variables': 'Variabili',
  'Note:': 'Nota:',
  'Email notifications are sent when enabled in user notification preferences. Variables will be automatically replaced with actual values when emails are sent.': 
    "Le email di notifica partono solo se sono attive nelle preferenze di notifica dell'utente. Le variabili vengono sostituite con i valori reali al momento dell'invio.",
  'Mention a teammate': 'Cita una persona del team',
  'Use the arrow keys to choose, Enter to confirm, Esc to close': 'Frecce per scegliere, Invio per confermare, Esc per chiudere',
  'Press Cmd+Enter to post. Type @ to mention a teammate': 'Cmd+Invio per pubblicare. Scrivi @ per citare una persona',
  'This attachment was blocked because its format is not allowed': 'Allegato bloccato: il formato non e’ consentito',
  'Edit comment': 'Modifica il commento',
  'Delete comment': 'Elimina il commento',
  'Post comment': 'Pubblica il commento',
  'Download attachment': 'Scarica l’allegato',
  'Delete attachment': 'Elimina l’allegato',
  'AI Service': 'Servizio AI',
  'Available': 'Disponibile',
  'Unavailable': 'Non disponibile',
  'Checking...': 'Verifica in corso...',
  'Shown in the application header and used in notification emails.': 'Compare in testata e nelle email di notifica.',
  'Notifications ({count} unread)': 'Notifiche ({count} da leggere)',
  'Delete notification': 'Elimina la notifica',
  'Edit task': 'Modifica l’attività',
  'Delete task': 'Elimina l’attività',
  'Select task': 'Seleziona l’attività',
  'Select {name}': 'Seleziona {name}',
  'Skip tour': 'Salta la presentazione',
  'tasks shown': 'attività mostrate',
  'Show more tasks': 'Mostra altre attività',
  'Calendar': 'Calendario',
  'Previous month': 'Mese precedente',
  'Next month': 'Mese successivo',
  'Today': 'Oggi',
  'Selected day': 'Giorno selezionato',
  'Priority: {priority}': 'Priorità: {priority}',
  'Tasks by due date for {month}': 'Attività per scadenza in {month}',
  '+{count} more': '+{count} altre',
  '{count} tasks': '{count} attività',
  '{count} overdue': '{count} in ritardo',
  '{count} scheduled this month': '{count} in programma questo mese',
  '{count} tasks have no due date and are not shown here': '{count} attività non hanno scadenza e non compaiono qui',
  'Every task has a due date': 'Tutte le attività hanno una scadenza',
  'Nothing due on this day': 'Niente in scadenza in questo giorno',
  'Nothing is due this month': 'Niente in scadenza questo mese',
  'Repeat': 'Ripeti',
  'Does not repeat': 'Non si ripete',
  'Daily': 'Ogni giorno',
  'Weekly': 'Ogni settimana',
  'Monthly': 'Ogni mese',
  'Repeat every': 'Ripeti ogni',
  'weeks': 'settimane',
  'months': 'mesi',
  'Repeat on': 'Ripeti nei giorni',
  'Leave empty to repeat on the same weekday.': 'Lascia vuoto per ripetere nello stesso giorno della settimana.',
  'End date (optional)': 'Data di fine (facoltativa)',
  'No end date': 'Nessuna data di fine',
  'Remove end date': 'Togli la data di fine',
  'Mon': 'Lun',
  'Tue': 'Mar',
  'Wed': 'Mer',
  'Thu': 'Gio',
  'Fri': 'Ven',
  'Sat': 'Sab',
  'Sun': 'Dom',
  'Tuesday': 'Martedì',
  'Wednesday': 'Mercoledì',
  'Thursday': 'Giovedì',
  'Friday': 'Venerdì',
  'Saturday': 'Sabato',
  'Daily summary instead of immediate emails': 'Riepilogo giornaliero al posto delle email immediate',
  'One email a day with the notifications you have not read, instead of one email for every event': 'Una email al giorno con le notifiche che non hai letto, invece di una email per ogni evento',
  'Summary time': 'Ora del riepilogo',
  'Times are in your timezone: {zone}': 'Gli orari sono nel tuo fuso: {zone}',
  'If there is nothing new, no email is sent. In-app notifications stay immediate.': "Se non c'è niente di nuovo, non parte nessuna email. Le notifiche nell'applicazione restano immediate.",
  'Daily summary enabled: one email per day instead of one per event': 'Riepilogo giornaliero attivo: una email al giorno invece di una per evento',
  'Immediate emails enabled: one email per event': 'Email immediate attive: una email per ogni evento',
  'No due date': 'Nessuna scadenza',
  'Blocked': 'Bloccata',
  'Labels': 'Etichette',
  'Search or add a label': 'Cerca o aggiungi un’etichetta',
  'Create label "{name}"': 'Crea l’etichetta "{name}"',
  'Remove label {name}': 'Togli l’etichetta {name}',
  'Label {name} added': 'Etichetta {name} aggiunta',
  'Label {name} removed': 'Etichetta {name} tolta',
  'Label suggestions': 'Etichette suggerite',
  'No matching label in use — type to create one': 'Nessuna etichetta in uso corrisponde — scrivila per crearla',
  'Labels are saved in lowercase so the same one is never created twice.': 'Le etichette si salvano in minuscolo, cosi’ la stessa non viene creata due volte.',
  'Similar labels already exist. Reusing one keeps filters useful.': 'Esistono etichette simili. Riusarne una tiene i filtri utili.',
  'Watchers': 'Osservatori',
  'Add someone who should follow this task': 'Aggiungi chi deve seguire questo task',
  'Nobody follows this task yet': 'Ancora nessuno segue questo task',
  'People who can follow this task': 'Chi puo’ seguire questo task',
  'No one else to add': 'Non c’e’ nessun altro da aggiungere',
  'No people to show': 'Nessuna persona da mostrare',
  'Follow this task': 'Segui questo task',
  'Following this task': 'Segue questo task',
  'Remove {name} from watchers': 'Togli {name} dagli osservatori',
  '{name} now follows this task': '{name} ora segue questo task',
  '{name} no longer follows this task': '{name} non segue piu’ questo task',
  'You are assigned to this task, so you already get every update.': 'Questo task e’ assegnato a te, quindi ricevi gia’ ogni aggiornamento.',
  '(you)': '(tu)',
  'Unknown user': 'Utente sconosciuto',
  'Removed member': 'Persona rimossa',
  'Estimated time': 'Tempo stimato',
  'Time spent': 'Tempo impiegato',
  'Estimated': 'Stimato',
  'No estimate': 'Nessuna stima',
  'Understood as': 'Interpretato come',
  'Not understood. Try 90, 1.5h or 2h 30m.': 'Non interpretato. Prova 90, 1.5h oppure 2h 30m.',
  'Leave empty if you cannot estimate it yet': 'Lascia vuoto se non riesci ancora a stimarlo',
  'Leave empty if not tracked': 'Lascia vuoto se non lo registri',
  'Leave empty if unknown': 'Lascia vuoto se non lo sai',
  'Same as the estimate': 'Come la stima',
  '{tempo} over the estimate': '{tempo} oltre la stima',
  '{tempo} under the estimate': '{tempo} sotto la stima',
  'at least {tempo}': 'almeno {tempo}',
  'Export Tasks': 'Esporta i task',
  'Choose the format, the columns and which tasks to include.': 'Scegli il formato, le colonne e quali task includere.',
  'Format': 'Formato',
  'Columns': 'Colonne',
  'Which tasks': 'Quali task',
  'Only the filtered tasks': 'Solo i task filtrati',
  'All tasks, including archived ones': 'Tutti i task, compresi quelli archiviati',
  'Select at least one column': 'Scegli almeno una colonna',
  '{righe} rows will be exported': 'Verranno esportate {righe} righe',
  'Export failed': 'Esportazione non riuscita',
  'Allow pop-ups to export the PDF': 'Consenti i pop-up per esportare il PDF',
  'Please allow pop-ups to download PDF': 'Consenti i pop-up per scaricare il PDF',
  'Task List': 'Elenco dei task',
  'Person': 'Persona',
  'Open': 'Aperti',
  'Saved filters': 'Filtri salvati',
  'Save current filters': 'Salva i filtri attuali',
  'Current filters are already saved': 'I filtri attuali sono gia’ salvati',
  'Name of this view': 'Nome di questa vista',
  'Rename this view': 'Rinomina questa vista',
  'Rename "{nome}"': 'Rinomina "{nome}"',
  'Delete "{nome}"': 'Elimina "{nome}"',
  'Delete this saved filter?': 'Eliminare questo filtro salvato?',
  '"{nome}" will be removed. The tasks are not affected.': '"{nome}" verra’ rimosso. I task non vengono toccati.',
  'Set some filters above, then save them here': 'Imposta dei filtri qui sopra, poi salvali qui',
  'Save the filters you use often — status, priority, department, assignee — and bring them back with one click.': 'Salva i filtri che usi spesso — stato, priorita’, reparto, assegnatario — e richiamali con un clic.',
  'Search: {testo}': 'Ricerca: {testo}',
  'Clear All': 'Azzera tutto',
  'Workload': 'Carico di lavoro',
  'Open tasks per person, and how much of that work has an estimate.': 'Task aperti per persona, e quanta parte di quel lavoro ha una stima.',
  'All {totale} open tasks have an estimate.': 'Tutti i {totale} task aperti hanno una stima.',
  '{senza} of {totale} open tasks have no estimate: that part of the workload is unknown.': '{senza} task aperti su {totale} non hanno una stima: quella parte del carico non e’ nota.',
  'Remove due date': 'Togli la scadenza',
  'Please enter a task title': 'Inserisci il titolo del task',
  'Task Title': 'Titolo',
  '"Create a task for the upcoming product launch"': '"Crea un\'attività per il lancio del prodotto"',
  '"How can I balance the workload across my team?"': '"Come posso distribuire meglio il carico di lavoro nel team?"',
  '"Which tasks should I prioritize this week?"': '"A quali attività devo dare la precedenza questa settimana?"',
  '1 day': '1 giorno',
  '1 day ago': '1 giorno fa',
  '1. Click "{label}" in the header': '1. Premi "{label}" nell\'intestazione',
  '1. Click the "{label}" button in the header': '1. Premi il pulsante "{label}" nell\'intestazione',
  '1. Navigate to the "{label}" tab': '1. Vai alla scheda "{label}"',
  '100% Tests Passed': '100% dei test superati',
  '150+ Features Built': 'Oltre 150 funzioni realizzate',
  '2. Check the boxes next to tasks you want to modify': '2. Spunta le caselle delle attività da modificare',
  '2. Click "{label}"': '2. Premi "{label}"',
  '2. Fill in the task details:': "2. Compila i dati dell'attività:",
  '2. Type your comment in the text field': '2. Scrivi il commento nel campo di testo',
  '3. Choose an action:': "3. Scegli un'azione:",
  '3. Click "{label}"': '3. Premi "{label}"',
  '3. Click "{label}" to save': '3. Premi "{label}" per salvare',
  '3. Enter their information:': '3. Inserisci i suoi dati:',
  '81 Iterations Completed': '81 iterazioni completate',
  'AI': 'AI',
  'AI Insights appear in the Analytics view and provide:': 'Le analisi AI compaiono nella sezione Analisi e offrono:',
  'AI Integration Active': 'Integrazione AI attiva',
  'AI assistant': 'Assistente AI',
  'AI insights': 'Analisi AI',
  'AI-Powered Features': 'Funzioni basate su AI',
  'Actionable Suggestions:': 'Suggerimenti da mettere in pratica:',
  'Actionable suggestions to improve workflow': 'Suggerimenti concreti per migliorare il flusso di lavoro',
  'Active: {active} • Done: {done}': 'In corso: {active} • Completate: {done}',
  'Activity ({count})': 'Attività registrate ({count})',
  'Add': 'Aggiungi',
  'Add Comment': 'Aggiungi commento',
  'Add and organize team members': 'Aggiungi e organizza i membri del team',
  'Add comments': 'Aggiungere commenti',
  'Add employees': 'Aggiungere persone',
  'Add new employees': 'Aggiungere nuove persone',
  'Admin, Manager, or Member': 'Amministratore, responsabile o membro',
  'All ({count})': 'Tutte ({count})',
  'All analytics': 'Tutte le analisi',
  'All caught up! 🎉': 'Sei in pari! 🎉',
  'All departments on track! 🎉': 'Tutti i dipartimenti sono in linea! 🎉',
  'All existing departments will be replaced with {count} new ones': 'I dipartimenti attuali verranno sostituiti da {count} nuovi',
  'Are you sure you want to clear all audit log entries? This cannot be undone.': "Vuoi davvero svuotare il registro delle attività? L'operazione non si può annullare.",
  'Are you sure you want to delete this comment?': 'Vuoi davvero eliminare questo commento?',
  'Are you sure you want to remove {count} team members from your team?': 'Vuoi davvero togliere {count} persone dal team?',
  'Are you sure you want to remove {name} from your team?': 'Vuoi davvero togliere {name} dal team?',
  'Are you sure you want to reset all settings to default values? This cannot be undone.': "Vuoi davvero riportare tutte le impostazioni ai valori iniziali? L'operazione non si può annullare.",
  'Ask about specific tasks or team status': 'Chiedi di una singola attività o di come sta andando il team',
  'Assign departments to {count} users': 'Assegna dipartimenti a {count} persone',
  'Assign tasks': 'Assegnare attività',
  'Assign tasks to others': 'Assegnare attività ad altri',
  'Assign to:': 'Assegnare a:',
  'Assigned to {name}': 'Assegnata a {name}',
  'Attach File': 'Allega file',
  'Attach files': 'Allegare file',
  'Attach files to tasks': 'Allegare file alle attività',
  'Attachments': 'Allegati',
  'Attachments ({count})': 'Allegati ({count})',
  'Auto-assign': 'Assegnazione automatica',
  'Automated recommendations and trend analysis': 'Suggerimenti automatici e analisi degli andamenti',
  'Bio': 'Biografia',
  'Brand identity and creative direction': 'Identità di marca e direzione creativa',
  'Brand strategy, campaigns, and growth marketing': 'Strategia di marca, campagne e marketing di crescita',
  'Brief description of the task': "Descrizione breve dell'attività",
  'Bright ascending chime': 'Scampanellio acuto crescente',
  'Budget: {amount}': 'Budget: {amount}',
  'Bulk Select': 'Selezione multipla',
  'Bulk operations': 'Operazioni di gruppo',
  'Business': 'Business',
  'Business operations and process management': 'Operations aziendali e gestione dei processi',
  'Celebratory ascending chime': 'Scampanellio festoso crescente',
  'Change status': 'Cambiare stato',
  'Change task status': 'Cambiare lo stato delle attività',
  'Check browser console for errors': 'Controlla la console del browser per eventuali errori',
  'Clear Audit Log ({count} entries)': 'Svuota il registro ({count} voci)',
  'Click "Add Task" to create new tasks. Assign them to team members, set priorities, due dates, and track status. Use bulk operations to manage multiple tasks at once.': 'Premi "Aggiungi attività" per crearne di nuove. Assegnale alle persone del team, imposta priorità e scadenze e segui lo stato. Con le operazioni di gruppo ne gestisci più di una alla volta.',
  'Click "Enable Notifications" to receive desktop alerts.': 'Premi "Attiva le notifiche" per ricevere gli avvisi sul desktop.',
  'Click "Publish" in Spark UI': 'Premi "Publish" nell\'interfaccia di Spark',
  'Click "{label}" in the header to start chatting!': 'Premi "{label}" nell\'intestazione e comincia a chiacchierare.',
  'Click "{label}" to upload documents, images, or other files (max 10MB per file).': 'Premi "{label}" per caricare documenti, immagini o altri file (massimo 10 MB ciascuno).',
  'Click on any task card to open the details dialog, then:': "Premi su una scheda per aprire il dettaglio dell'attività, poi:",
  'Click the "{label}" button in the header to view:': 'Premi il pulsante "{label}" nell\'intestazione per vedere:',
  'Click the "{label}" button to:': 'Premi il pulsante "{label}" per:',
  'Click the edit icon (pencil) on any task card, make your changes, and click "{label}".': 'Premi l\'icona di modifica (la matita) su una scheda, cambia quello che serve e premi "{label}".',
  'Client acquisition and revenue generation': 'Acquisizione clienti e generazione di ricavi',
  'Client relationships and support services': 'Rapporto con i clienti e servizi di assistenza',
  'Comment on tasks': 'Commentare le attività',
  'Comments': 'Commenti',
  'Comments ({count})': 'Commenti ({count})',
  'Common departments:': 'Dipartimenti più comuni:',
  'Complete these final steps before going live:': 'Completa questi ultimi passaggi prima di andare in produzione:',
  'Completed: {done} • Rate: {rate}%': 'Completate: {done} • Percentuale: {rate}%',
  'Completion rates, workload distribution, task trends': 'Percentuali di completamento, distribuzione del carico, andamento delle attività',
  'Confidence: {level}': 'Affidabilità: {level}',
  'Configure access level and permissions for {name}': 'Imposta livello di accesso e permessi di {name}',
  'Configure your notification preferences by clicking the bell icon in the header. You can customize which events trigger notifications, set quiet hours, and choose notification sounds.': "Imposta le preferenze premendo la campanella nell'intestazione. Puoi scegliere quali eventi generano una notifica, definire le ore di silenzio e scegliere i suoni.",
  'Contact email': 'Email di contatto',
  'Content creation, writing, and editorial': 'Creazione di contenuti, scrittura e redazione',
  'Content of a comment': 'Testo di un commento',
  'Create': 'Creare',
  'Create All ({count})': 'Creali tutti ({count})',
  'Create and Assign Tasks': 'Crea e assegna le attività',
  'Create new tasks': 'Creare nuove attività',
  'Create, assign, and track tasks efficiently': 'Crea, assegna e segui le attività senza perdere tempo',
  'Created {count} departments from the {category} template': 'Creati {count} dipartimenti dal modello {category}',
  'Creative': 'Creatività',
  'Current date': 'Data di oggi',
  'Current status of the task': "Stato attuale dell'attività",
  'Current year': 'Anno in corso',
  'Data analysis, machine learning, and analytics': 'Analisi dei dati, machine learning e statistiche',
  'Date when the action occurred': "Data in cui è avvenuta l'azione",
  'Delete announcements': 'Eliminare gli annunci',
  'Delete any task': 'Eliminare qualsiasi attività',
  'Delete employees': 'Eliminare le persone',
  'Delete own tasks': 'Eliminare le proprie attività',
  'Delete {count} users?': 'Vuoi eliminare {count} utenti?',
  'Department "{name}" already exists': 'Il dipartimento "{name}" esiste già',
  'Department "{name}" archived': 'Dipartimento "{name}" archiviato',
  'Department "{name}" created successfully!': 'Dipartimento "{name}" creato',
  'Department "{name}" deleted successfully': 'Dipartimento "{name}" eliminato',
  'Department "{name}" restored': 'Dipartimento "{name}" ripristinato',
  'Department "{name}" updated successfully!': 'Dipartimento "{name}" aggiornato',
  'Department Name *': 'Nome del dipartimento *',
  'Department-specific metrics and comparisons': 'Dati e confronti per singolo dipartimento',
  'Departments added to {users} users: {departments} in total': 'Dipartimenti aggiunti a {users} persone: {departments} in tutto',
  'Departments available: {count}': 'Dipartimenti disponibili: {count}',
  'Departments replaced for {users} users: {departments} in total': 'Dipartimenti sostituiti per {users} persone: {departments} in tutto',
  'Descending alert': 'Avviso discendente',
  'Describe a task naturally and AI will create it': "Descrivi un'attività a parole tue e l'AI la crea",
  'Description of the task': "Descrizione dell'attività",
  'Desktop': 'Computer',
  'Desktop notifications are blocked. Check your browser settings to enable them.': 'Le notifiche sul desktop sono bloccate. Per attivarle, controlla le impostazioni del browser.',
  'Desktop notifications are enabled and working.': 'Le notifiche sul desktop sono attive e funzionano.',
  'Detailed information (optional)': 'Informazioni dettagliate (facoltative)',
  'Due Soon': 'In scadenza',
  'Due date of the task': "Scadenza dell'attività",
  'Due {when}': 'Scade {when}',
  'Early Bird (9 PM - 6 AM)': 'Mattiniero (21:00 - 06:00)',
  'Edit announcements': 'Modificare gli annunci',
  'Edit any task': 'Modificare qualsiasi attività',
  'Edit employee details': 'Modificare i dati delle persone',
  'Edit employees': 'Modificare le persone',
  'Edit own tasks': 'Modificare le proprie attività',
  'Efficiency': 'Efficienza',
  'Email Address *': 'Indirizzo email *',
  'Email address of the recipient': 'Indirizzo email del destinatario',
  'Employee Management': 'Gestione delle persone',
  'Employees: {count}': 'Persone: {count}',
  'Enable Quiet Hours': 'Attiva le ore di silenzio',
  'Enable Sounds': 'Attiva i suoni',
  'Existing departments: {list}': 'Dipartimenti esistenti: {list}',
  'Expires {date}': 'Scade il {date}',
  'Export data backup': 'Esporta un backup dei dati',
  'Failed to generate assignments': 'Non è stato possibile generare le assegnazioni',
  'Failed to get AI response': "Non è stato possibile ottenere una risposta dall'AI",
  'Financial planning, accounting, and reporting': 'Pianificazione finanziaria, contabilità e reportistica',
  'Flag urgent overdue tasks': 'Segnala le attività in ritardo più urgenti',
  'Formatted report with charts': 'Report impaginato con i grafici',
  "From concept to production in 81 iterations. That's persistence!": "Dall'idea alla produzione in 81 iterazioni: questa sì che è costanza.",
  'Full Name *': 'Nome e cognome *',
  'Full name': 'Nome e cognome',
  'Gentle ascending tone': 'Tono crescente leggero',
  'Get AI insights': 'Ottenere le analisi AI',
  'Get AI task estimates': 'Ottenere le stime AI sulle attività',
  'Get Started': 'Cominciamo',
  'Get recommendations for task reassignment or priority changes': 'Ricevi consigli su come riassegnare le attività o cambiarne la priorità',
  'High double ping': 'Doppio ping acuto',
  'High, Medium, or Low': 'Alta, media o bassa',
  'I apologize, but I encountered an error processing your request: {message}': "Mi dispiace, si è verificato un errore nell'elaborare la richiesta: {message}",
  'Identify overloaded team members': 'Individua chi nel team è sovraccarico',
  'Identify overworked team members': 'Individua chi nel team lavora troppo',
  'Importing...': 'Importazione in corso...',
  'Information security and cybersecurity operations': 'Sicurezza delle informazioni e operazioni di cybersicurezza',
  'Infrastructure, deployment, and system operations': 'Infrastruttura, rilasci e gestione dei sistemi',
  'Job Title *': 'Ruolo aziendale *',
  'Job title or position': 'Ruolo o posizione ricoperta',
  'John Doe': 'Mario Rossi',
  'Joined Date': 'Data di ingresso',
  'LAUNCH_CELEBRATION.md - Celebration & stats': 'LAUNCH_CELEBRATION.md - Festeggiamenti e numeri',
  'LAUNCH_READINESS_REPORT.md - Full audit': 'LAUNCH_READINESS_REPORT.md - Verifica completa',
  'Lead: {name}': 'Responsabile: {name}',
  'Legal compliance and contract management': 'Conformità legale e gestione dei contratti',
  "Let's Launch! 🚀": 'Si parte! 🚀',
  'Link to view the task': "Collegamento per aprire l'attività",
  'Manage Your Team': 'Gestisci il tuo team',
  'Manage roles': 'Gestire i ruoli',
  'Manage user roles and permissions': 'Gestire ruoli e permessi degli utenti',
  'Managing: {departments}': 'Dipartimenti che gestisci: {departments}',
  'Mark all as completed': 'Segna tutte come completate',
  'Mentions': 'Menzioni',
  'Mobile': 'Telefono',
  'Monitor team analytics': "Tieni d'occhio le analisi del team",
  'N/A': 'N.D.',
  'Name of the application': "Nome dell'applicazione",
  'Name of the company': "Nome dell'azienda",
  'Name of the email recipient': "Nome del destinatario dell'email",
  'Name of the person assigned': 'Nome della persona assegnataria',
  'Name of the person who performed the action': "Nome di chi ha compiuto l'azione",
  'New': 'Nuovo',
  'New comment added': 'Nuovo commento aggiunto',
  'Night Owl (12 AM - 10 AM)': 'Nottambulo (00:00 - 10:00)',
  'No': 'No',
  'No data': 'Nessun dato',
  'Notification Preferences': 'Preferenze di notifica',
  'Out of {count} total': 'Su {count} in totale',
  'PRODUCTION_DEPLOYMENT.md - Deployment guide': 'PRODUCTION_DEPLOYMENT.md - Guida al rilascio',
  'Perform bulk operations': 'Eseguire operazioni di gruppo',
  'Personal analytics': 'Analisi personali',
  'Phone': 'Telefono',
  'Playing {sound}': 'Riproduzione: {sound}',
  'Preview: This color will be auto-assigned based on the department name': 'Anteprima: questo colore viene assegnato automaticamente in base al nome del dipartimento',
  'Priority Changed': 'Priorità cambiata',
  'Priority changed to {priority}': 'Priorità cambiata in {priority}',
  'Priority level of the task': "Livello di priorità dell'attività",
  'Product strategy and user experience design': "Strategia di prodotto e progettazione dell'esperienza d'uso",
  'Production Ready': 'Pronto per la produzione',
  'Quality assurance and software testing': 'Controllo qualità e test del software',
  'Quick double chirp': 'Doppio trillo rapido',
  'Quick select existing departments:': 'Scegli rapidamente fra i dipartimenti esistenti:',
  'Quiet hours disabled': 'Ore di silenzio disattivate',
  'Quiet hours enabled - notifications paused during sleep times': 'Ore di silenzio attive: durante il riposo le notifiche restano sospese',
  'Quiet hours set: {preset}': 'Ore di silenzio impostate: {preset}',
  'Raw data for further analysis': 'Dati grezzi per analisi successive',
  'Remove all selected tasks': 'Elimina tutte le attività selezionate',
  'Remove employees': 'Rimuovere le persone',
  'Reset all to not-started': 'Riporta tutte a "Da iniziare"',
  'Rising alert tone': 'Avviso crescente',
  'Run final smoke test (30 minutes)': "Esegui l'ultimo giro di prove (30 minuti)",
  'Saving…': 'Salvataggio…',
  'Security Hardened': 'Sicurezza rafforzata',
  'Select at least one department to continue': 'Scegli almeno un dipartimento per continuare',
  "Selected departments will be added to each user's current departments": 'I dipartimenti scelti si aggiungono a quelli che ogni persona ha già',
  'Selected departments will replace all current departments for each user': 'I dipartimenti scelti sostituiscono tutti quelli attuali di ogni persona',
  'Selected users: {count}': 'Persone selezionate: {count}',
  'Set all to in-progress': 'Porta tutte a "In corso"',
  'Share URL with your team': "Condividi l'indirizzo con il tuo team",
  'Single soft ping': 'Ping singolo attenuato',
  'Skills': 'Competenze',
  'Sleep Time (10 PM - 7 AM)': 'Riposo (22:00 - 07:00)',
  'Smart suggestions and automated workflows': 'Suggerimenti intelligenti e flussi di lavoro automatici',
  'Smart task management': 'Gestione intelligente delle attività',
  'Social media management and community engagement': 'Gestione dei social e rapporto con la community',
  'Software development and technical implementation': 'Sviluppo software e realizzazione tecnica',
  'Spot trends in completion rates': 'Coglie gli andamenti nelle percentuali di completamento',
  'Start by adding your team members. Click the "Users" button in the header to add employees, assign departments, and set roles (Admin, Manager, or Member).': 'Comincia aggiungendo le persone del team. Premi "Utenti" nell\'intestazione per aggiungerle, assegnare i dipartimenti e scegliere il ruolo (amministratore, responsabile o membro).',
  'Status Changed': 'Stato cambiato',
  'Status changed to {status}': 'Stato cambiato in {status}',
  'Switch to the Analytics view to see team performance metrics, workload distribution, and department insights. Export reports as PDF or CSV.': 'Passa alla sezione Analisi per vedere le prestazioni del team, la distribuzione del carico e i dati per dipartimento. I report si esportano in PDF o CSV.',
  'Tablet': 'Tablet',
  'Talent management and employee relations': 'Gestione dei talenti e relazioni con il personale',
  'Task Assigned': 'Attività assegnata',
  'Task Completed': 'Attività completata',
  'Task Reassigned': 'Attività riassegnata',
  'Task created': 'Attività creata',
  'Task estimates': 'Stime delle attività',
  'Task updated': 'Attività aggiornata',
  'Tasks assigned: {count}': 'Attività assegnate: {count}',
  'Tasks: {count}': 'Attività: {count}',
  'Tasks: {done}/{total}': 'Attività: {done}/{total}',
  'Team Collaboration': 'Collaborazione nel team',
  'Team analytics': 'Analisi del team',
  'Team member responsible': 'Persona del team che se ne occupa',
  'Team members: {count}': 'Membri del team: {count}',
  'Team members: {members} · Tasks: {tasks}': 'Membri del team: {members} · Attività: {tasks}',
  'Technical support and system maintenance': 'Assistenza tecnica e manutenzione dei sistemi',
  'Technology': 'Tecnologia',
  'Template applied! Review and create "{name}"': 'Modello applicato: controlla i dati e crea "{name}"',
  'Test on mobile device': 'Prova su un dispositivo mobile',
  'The AI Assistant helps you with:': "L'assistente AI ti aiuta a:",
  'The departments in the {category} template already exist': 'I dipartimenti del modello {category} esistono già',
  'This department cannot be archived: it still has {count} assigned people': 'Non puoi archiviare questo dipartimento: ha ancora {count} persone assegnate',
  'This department cannot be deleted: it still has {count} assigned people': 'Non puoi eliminare questo dipartimento: ha ancora {count} persone assegnate',
  'This is a test notification from TaskFlow!': 'Questa è una notifica di prova di TaskFlow.',
  'This user has {count} assigned tasks. Those tasks will become unassigned.': 'Questa persona ha {count} attività assegnate, che resteranno senza assegnatario.',
  'This will permanently delete "{name}". This action cannot be undone.': '"{name}" verrà eliminato definitivamente. L\'operazione non si può annullare.',
  'Three warning tones': 'Tre toni di avviso',
  'Tips for great feedback:': 'Consigli per un feedback utile:',
  'Title of the task': "Titolo dell'attività",
  'Total clicks: {count}': 'Clic totali: {count}',
  'Total tasks: {count}': 'Attività totali: {count}',
  'Track Performance': "Segui l'andamento",
  'Try asking:': 'Prova a chiedere:',
  'Two-tone notification': 'Notifica a due toni',
  'Type of action performed': 'Tipo di azione compiuta',
  'UI/UX design and visual design work': "Progettazione di interfacce, esperienza d'uso e grafica",
  'Unique: {count}': 'Univoci: {count}',
  'Unknown': 'Sconosciuto',
  'Unread ({count})': 'Da leggere ({count})',
  'Updated {time}': 'Aggiornato alle {time}',
  'Use AI Assistant for intelligent task suggestions, auto-assignment based on workload, and insights about team performance and bottlenecks.': "Usa l'assistente AI per ricevere proposte sulle attività, assegnarle in automatico in base al carico e capire come va il team e dove si blocca.",
  'Use AI assistant': "Usare l'assistente AI",
  'Use AI auto-assign': "Usare l'assegnazione automatica AI",
  'Users affected: {count}': 'Persone coinvolte: {count}',
  'Users removed: {count}': 'Persone rimosse: {count}',
  'Verify all critical paths working': 'Verifica che i percorsi critici funzionino',
  'Video creation, editing, and multimedia': 'Realizzazione video, montaggio e multimedia',
  'View all tasks': 'Vedere tutte le attività',
  'View announcements': 'Vedere gli annunci',
  'View employee list': "Vedere l'elenco delle persone",
  'View employees': 'Vedere le persone',
  'View organization analytics': "Vedere le analisi dell'organizzazione",
  'View own tasks': 'Vedere le proprie attività',
  'View personal analytics': 'Vedere le analisi personali',
  'View team analytics': 'Vedere le analisi del team',
  'View team tasks': 'Vedere le attività del team',
  'Visualize team performance and insights': 'Guarda le prestazioni del team e cosa dicono i dati',
  'Warning:': 'Attenzione:',
  'Warning: this department has {count} assigned people.': 'Attenzione: a questo dipartimento sono assegnate {count} persone.',
  "We'll notify you when something important happens": 'Ti avvisiamo quando succede qualcosa di importante',
  "We've built TaskFlow to help teams work smarter, collaborate better, and achieve more together. Your feedback during this launch phase is invaluable and will help us shape the future of this platform.": 'Abbiamo costruito TaskFlow per aiutare i team a lavorare meglio, collaborare di più e ottenere di più insieme. In questa fase di lancio il tuo parere vale moltissimo e ci aiuta a decidere come far crescere la piattaforma.',
  'Welcome back, {name}!': 'Bentornato, {name}.',
  'Welcome to TaskFlow! 🎉': 'Benvenuto in TaskFlow! 🎉',
  'When a task becomes overdue': "Quando un'attività va in ritardo",
  'When a task is assigned to you': "Quando ti viene assegnata un'attività",
  'When a task is due within 24 hours': "Quando un'attività scade entro 24 ore",
  'When a task is marked as complete': "Quando un'attività viene segnata come completata",
  'When a task is reassigned to you': "Quando un'attività viene riassegnata a te",
  'When someone comments on your task': 'Quando qualcuno commenta una tua attività',
  'When task details are modified': "Quando cambiano i dati di un'attività",
  'When task priority is modified': "Quando cambia la priorità di un'attività",
  'When task status is updated': "Quando cambia lo stato di un'attività",
  'When the task should be completed': "Entro quando va completata l'attività",
  'When you are mentioned in comments': 'Quando vieni menzionato in un commento',
  'When you have unassigned tasks, click "{label}" to:': 'Quando hai attività senza assegnatario, premi "{label}" per:',
  'Which teams they belong to': 'A quali team appartiene',
  'Work together with departments and roles': 'Lavorate insieme, per dipartimenti e ruoli',
  'Working Hours (6 PM - 9 AM)': 'Fuori orario (18:00 - 09:00)',
  'Yes': 'Sì',
  'Yes! In the analytics view, click the "{label}" button to download reports as:': 'Sì. Nella sezione delle analisi premi il pulsante "{label}" per scaricare i report come:',
  'Yes! Open the task details dialog and go to the "{label}" tab.': 'Sì. Apri il dettaglio dell\'attività e vai alla scheda "{label}".',
  'You Did It! 🎊': "Ce l'hai fatta! 🎊",
  'You will now receive desktop notifications for important updates!': "D'ora in poi riceverai una notifica sul desktop per gli aggiornamenti importanti.",
  "You'll receive desktop notifications for:": 'Riceverai una notifica sul desktop per:',
  "You're all caught up!": 'Non ti sei perso niente.',
  'Your complete employee task management solution': 'La tua soluzione completa per gestire il lavoro del team',
  'Your data is automatically saved in your browser. Use "{label}" to export your data before making major changes. You can also import data from previous backups.': 'I dati vengono salvati automaticamente nel browser. Usa "{label}" per esportarli prima di grossi cambiamenti; puoi anche reimportare un backup precedente.',
  'Your experience matters! Please take a moment to share your thoughts, report any issues, or suggest improvements. Every piece of feedback helps us make TaskFlow better for everyone.': 'La tua esperienza conta. Prenditi un momento per dirci come ti trovi, segnalare problemi o proporre miglioramenti: ogni commento ci aiuta a rendere TaskFlow migliore per tutti.',
  'added a comment': 'ha aggiunto un commento',
  'assigned to {name}': "l'ha assegnata a {name}",
  'attached {file}': 'ha allegato {file}',
  'by {name}': 'da {name}',
  'changed due date from {old} to {new}': 'ha spostato la scadenza da {old} a {new}',
  'changed priority from {old} to {new}': 'ha cambiato la priorità da {old} a {new}',
  'changed status from {old} to {new}': 'ha cambiato lo stato da {old} a {new}',
  'completion': 'completamento',
  'created this task': 'ha creato questa attività',
  'in 1 day': 'fra 1 giorno',
  'in 1 hour': 'fra 1 ora',
  'in {count} days': 'fra {count} giorni',
  'in {count} hours': 'fra {count} ore',
  'made a change': 'ha fatto una modifica',
  'reassigned from {old} to {new}': "l'ha riassegnata da {old} a {new}",
  'removed attachment {file}': "ha rimosso l'allegato {file}",
  'tasks/person': 'attività a testa',
  'today': 'oggi',
  'updated the description': 'ha aggiornato la descrizione',
  'updated the title': 'ha aggiornato il titolo',
  'yesterday': 'ieri',
  '{count} In Progress': '{count} in corso',
  '{count} Overdue': '{count} in ritardo',
  '{count} active': '{count} in forza',
  '{count} already created': '{count} già creati',
  '{count} bounced': '{count} respinte',
  '{count} clicked': '{count} con clic',
  '{count} days': '{count} giorni',
  '{count} days ago': '{count} giorni fa',
  '{count} days from now': 'fra {count} giorni',
  '{count} departments will be added to the existing ones': '{count} dipartimenti si aggiungeranno a quelli attuali',
  '{count} high priority': '{count} ad alta priorità',
  '{count} not started': '{count} da iniziare',
  '{count} opened': '{count} aperte',
  '{count} sent': '{count} inviate',
  '{count} tasks/person': '{count} attività a testa',
  '{count} unassigned': '{count} senza assegnatario',
  '{count} users set to {status}': '{count} persone portate allo stato {status}',
  '{count}% completion': '{count}% di completamento',
  '{name} department': 'Dipartimento {name}',
  '~{hours}h per day': 'circa {hours} h al giorno',
  '• Be specific about what you experienced': '• Racconta con precisione cosa ti è successo',
  '• Describe the impact on your workflow': '• Spiega che effetto ha sul tuo lavoro',
  '• Include steps to reproduce (for bugs)': '• Se è un errore, indica come riprodurlo',
  '• Suggest potential solutions if you have ideas': "• Se hai un'idea per risolvere, proponila",
  '🎉 Desktop Notifications Enabled': '🎉 Notifiche sul desktop attive',
  '🎉 TaskFlow is Now Live! 🎉': '🎉 TaskFlow è online! 🎉',
  '🎉 Time to Celebrate!': '🎉 È il momento di festeggiare!',
  '📊 By The Numbers:': '📊 In numeri:',
  '📋 Launch Checklist': '📋 Lista di controllo per il lancio',
  '📚 Documentation Ready:': '📚 Documentazione pronta:',
  '🔔 Test Notification': '🔔 Notifica di prova',
  '🔴 Needs Attention': "🔴 Da tenere d'occhio",
  '🚀 Ready for Launch!': '🚀 Pronti al lancio!',
  '🟠 Fair': '🟠 Così così',
  '🟡 Good': '🟡 Buono',
  '🟢 Excellent': '🟢 Ottimo',
  'Awaiting approval': 'In attesa di approvazione',
  'Approved': 'Approvato',
  'Requires approval': 'Richiede approvazione',
  'This task is completed but still needs approval': 'Questa attività è completata ma deve ancora essere approvata',
  'Once completed, this task must be approved before it closes': 'Una volta completata, questa attività deve essere approvata prima di chiudersi',
  'Approved by {name} on {date}': 'Approvato da {name} il {date}',
  'Approved on {date}': 'Approvato il {date}',
  'Approve': 'Approva',
  'Request changes': 'Chiedi modifiche',
  'Send back to in progress': 'Rimanda in lavorazione',
  'What needs to change? (optional)': 'Che cosa va corretto? (facoltativo)',
  'Reason for sending the task back': "Motivo per cui l'attività viene rimandata indietro",
  'Waiting for someone else to approve your work': 'In attesa che qualcun altro approvi il tuo lavoro',
  '{name} marked this task as done and is waiting for approval': "{name} ha segnato questa attività come conclusa e attende l'approvazione",
  'This task is marked as done and is waiting for approval': "Questa attività è segnata come conclusa e attende l'approvazione",
  'Require approval before this task can be closed': "Richiedi un'approvazione prima che questa attività possa essere chiusa",
  'Task approved': 'Attività approvata',
  'Task sent back for changes': 'Attività rimandata indietro per modifiche',
  'Marked as done, waiting for approval': 'Segnata come conclusa, in attesa di approvazione',
  'Awaiting my approval': 'In attesa della mia approvazione',
  'Loading tasks': 'Caricamento delle attività',
  'Loading statistics': 'Caricamento delle statistiche',
  'Loading dashboard': 'Caricamento del cruscotto',
  'No tasks yet': 'Nessuna attività',
  'Get started by creating your first task': 'Inizia creando la tua prima attività',
  'Try adjusting your filters': 'Prova a modificare i filtri',
  "Organize your team's work": "Organizza il lavoro del tuo team",
  "TaskFlow helps teams organize work, track progress, and collaborate effectively. Let's take a quick tour of the key features.": "TaskFlow aiuta i team a organizzare il lavoro, seguirne l'avanzamento e collaborare meglio. Facciamo un giro veloce delle funzioni principali.",
  'approved this task': 'ha approvato questa attività',
  'sent it back for changes': 'l’ha rimandata indietro per delle modifiche',
  'sent it back for changes: {reason}': 'l’ha rimandata indietro: {reason}',
  'Exit Bulk Mode': 'Esci dalla selezione multipla',
  'Selected tasks: {count}': 'Attività selezionate: {count}',
  'All Tasks ({count})': 'Tutte le attività ({count})',
  'Unassigned ({count})': 'Senza assegnatario ({count})',
  'When the assignee marks it done, a manager has to approve it.': 'Quando l’assegnatario la segna come fatta, un responsabile deve approvarla.',
  'This task is waiting for approval: approve it or send it back to change this.': 'Questa attività aspetta un’approvazione: approvala o rimandala indietro per cambiare questa impostazione.',
  'Generated on {date}': 'Generato il {date}',
  "Reset {name}'s password": 'Reimposta la password di {name}',
  'Edit {name}': 'Modifica {name}',
  'Remove from team': 'Rimuovi dal team',
  'Remove {name}': 'Rimuovi {name}',
  'No team members yet': 'Nessuna persona nel team',
  'Add your first team member to get started': 'Aggiungi la prima persona per iniziare',
  'Try adjusting your search or filters': 'Prova a cambiare la ricerca o i filtri',
  'Removed an API key saved by the previous version: keys live only on the server.': 'Rimossa dalla configurazione una chiave API salvata dalla versione precedente: le chiavi vivono solo lato server.',
  'TaskFlow — test email': 'TaskFlow — email di prova',
  'This is a test email sent by TaskFlow. If you are reading it, the server-side setup works.': "Questa è un'email di prova inviata da TaskFlow. Se la stai leggendo, la configurazione lato server funziona.",
  'If you are reading this message, server-side email delivery works.': 'Se stai leggendo questo messaggio, la configurazione di invio lato server funziona.',
  'Sending failed: {reason}': 'Invio fallito: {reason}',
  'Test email sent to {address}': 'Email di prova inviata a {address}',
  'Network error': 'Errore di rete',
  'Email delivery': 'Invio email',
  'Delivery provider and test send': 'Provider di consegna e prova di invio',
  'The API key and the sender address are configured on the server only, in the project environment variables ({keyVariables}, {fromVariable}).': "La chiave API e l'indirizzo mittente si configurano solo lato server, nelle variabili d'ambiente del progetto ({keyVariables}, {fromVariable}).",
  'Do not enter them here: they would be stored in clear text in the organisation database and loaded into the browser of anyone who opens the application.': "Non inserirle qui: finirebbero in chiaro nel database dell'organizzazione e nel browser di chiunque apra l'applicazione.",
  'Preferred provider': 'Provider preferito',
  'Used when the matching key is configured on the server; otherwise the available one is chosen automatically.': 'Usato se sul server è configurata la chiave corrispondente; altrimenti viene scelto automaticamente quello disponibile.',
  'Provider': 'Provider',
  'The recipient must be a member of this organisation: the endpoint rejects external addresses, so that it cannot become a relay for the verified domain.': "Il destinatario deve essere un membro di questa organizzazione: l'endpoint rifiuta gli indirizzi esterni, per non trasformarsi in un relay a nome del dominio verificato.",
  'colleague@company.com': 'collega@azienda.it',
  'Sending…': 'Invio…',
  'Send test': 'Invia prova',
  'You need the manager role or higher.': 'Serve il ruolo manager o superiore.',
  'Actual delivery outcomes are shown in "{section}".': 'Gli esiti di consegna reali sono in "{section}".',
  'Test send': 'Invio di prova',
  'Enter an address to send the test to': 'Indica un indirizzo a cui inviare la prova',
  'The file contains no data to restore': 'Il file non contiene dati da ripristinare',
  'AI features are not active': 'Le funzioni AI non sono attive',
  'Could not create the user': 'Creazione utente non riuscita',
  'Could not remove': 'Rimozione non riuscita',
  'Could not reset the password': 'Reimpostazione della password non riuscita',
  'Could not generate insights': 'Non è stato possibile generare le analisi',
  'Could not update the role': 'Aggiornamento del ruolo non riuscito',
  'Unknown error': 'Errore sconosciuto',
  'invalid format': 'formato non valido',
  'Could not load your tasks': 'Non è stato possibile caricare le attività',
  'Check your connection and try again. Nothing has been lost.': 'Controlla la connessione e riprova. Non è andato perso niente.',
  'Try again': 'Riprova',
  'Waiting for these tasks': 'In attesa di queste attività',
  'Task no longer available': 'Attività non più disponibile',
  'This task now waits for {title}': 'Questa attività ora aspetta {title}',
  'This task no longer waits for {title}': 'Questa attività non aspetta più {title}',
  'Done — no longer holds this task': 'Chiusa: non trattiene più questa attività',
  'Still open': 'Ancora aperta',
  'Stop waiting for {title}': 'Smetti di aspettare {title}',
  'This task does not wait for anything': 'Questa attività non aspetta nulla',
  'Search a task that must be done first': "Cerca un'attività da chiudere prima di questa",
  'Tasks that can come first': 'Attività che possono venire prima',
  'No other task to wait for': "Nessun'altra attività da aspettare",
  'Not available: that task is already waiting for this one': "Non disponibile: quell'attività sta già aspettando questa",
  'A task can be completed only after everything it waits for is done.': "Un'attività si può completare solo dopo che è chiuso tutto ciò che aspetta.",
  'Waiting for one other task to be done': "In attesa che si chiuda un'altra attività",
  'Waiting for {count} other tasks to be done': 'In attesa che si chiudano altre {count} attività',
  'Blocked by other tasks': 'Bloccata da altre attività',
  'Open {title}': 'Apri {title}',
  'This task can be completed once those are done.': 'Questa attività si potrà completare quando quelle saranno chiuse.',
  'Finish these first: {tasks}': 'Prima devi chiudere: {tasks}',
  'Steps': 'Passi',
  '{done} of {total} done': '{done} di {total} fatti',
  'No steps yet': 'Nessun passo',
  'Add a step': 'Aggiungi un passo',
  'Add step': 'Aggiungi il passo',
  'Step text': 'Testo del passo',
  'Step added: {name}': 'Passo aggiunto: {name}',
  'Step deleted: {name}': 'Passo eliminato: {name}',
  'Step moved to position {position} of {total}': 'Passo spostato in posizione {position} di {total}',
  'Move step up: {name}': 'Sposta su il passo: {name}',
  'Move step down: {name}': 'Sposta giù il passo: {name}',
  'Rename step: {name}': 'Rinomina il passo: {name}',
  'Delete step: {name}': 'Elimina il passo: {name}',
  'A task can have at most {max} steps. For more, create separate tasks.': "Un'attività può avere al massimo {max} passi. Per fare di più, crea attività separate.",
  'Only a manager can remove the approval requirement, and not on their own task.': 'Solo un responsabile può togliere la richiesta di approvazione, e non sul proprio lavoro.',
  'To enable notifications, please allow them in your browser settings:': 'Per ricevere le notifiche, autorizzale nelle impostazioni del browser:',
  'Settings → Privacy → Site Settings → Notifications': 'Impostazioni → Privacy → Impostazioni sito → Notifiche',
  'Enabled': 'Attiva',
  'Not Set': 'Non impostata',
  'Improvement': 'Miglioramento',
  'Department details and team members': 'Dettagli del dipartimento e membri del team',
  'Blue': 'Blu',
  'Green': 'Verde',
  'Purple': 'Viola',
  'Orange': 'Arancione',
  'Red': 'Rosso',
  'Teal': 'Turchese',
  'Pink': 'Rosa',
  'Yellow': 'Giallo',
  'Indigo': 'Indaco',
  'Cyan': 'Ciano',
  'View details for department {name}': 'Mostra i dettagli del dipartimento {name}',
  'Edit department {name}': 'Modifica il dipartimento {name}',
  'Archive department {name}': 'Archivia il dipartimento {name}',
  'Delete department {name}': 'Elimina il dipartimento {name}',
  'Filter by category': 'Filtra per categoria',
  'Filter by status': 'Filtra per stato',
  'Filter by department': 'Filtra per dipartimento',
  'Filter by role': 'Filtra per ruolo',
  'Change status for {title}': 'Cambia lo stato di {title}',
  'Upvote {title}': 'Vota {title}',
  'List view': 'Vista a elenco',
  'Grid view': 'Vista a griglia',
  'Search team members': 'Cerca tra i membri del team',
  'Import Backup': 'Importa il backup',
  'Error Details:': "Dettagli dell'errore:",
  'Open Rate %': 'Percentuale di apertura %',
  'Click Rate %': 'Percentuale di clic %',
  'HTML content...': 'Contenuto HTML...',
  'Plain text content...': 'Contenuto in testo semplice...',
  'Real delivery outcomes recorded by the server. Opens and clicks are not tracked: those values stay at zero.': 'Esiti di consegna reali registrati dal server. Aperture e clic non sono tracciati: quei valori restano a zero.',
  'Logs not readable: {reason}': 'Log non leggibili: {reason}',
  'Time range': 'Intervallo di tempo',
  'Email type': 'Tipo di email',
  'No active organization': 'Nessuna organizzazione attiva',
  'Backup exported: {chiavi} keys and {task} tasks': 'Backup esportato: {chiavi} chiavi e {task} attività',
  'Export failed: {reason}': 'Esportazione fallita: {reason}',
  'Restore failed: {reason}': 'Ripristino fallito: {reason}',
  'and they stay hidden from users. Reason reported by the server:': 'e restano nascoste agli utenti. Motivo riportato dal server:',
  'not specified': 'non specificato',
  'If the key is not tied to a workspace, set the ANTHROPIC_WORKSPACE_ID environment variable or use a key already associated with a workspace.': "Se la chiave non è legata a un workspace, imposta la variabile d'ambiente ANTHROPIC_WORKSPACE_ID oppure usa una chiave già associata a un workspace.",
  'Send': 'Invia',
  'e.g. 90, 1.5h, 2h 30m': 'es. 90, 1,5h, 2h 30m',
  'sorted descending, activate to sort ascending': 'ordinato in modo decrescente, attiva per ordinare in modo crescente',
  'sorted ascending, activate to sort descending': 'ordinato in modo crescente, attiva per ordinare in modo decrescente',
  'activate to sort by this column': 'attiva per ordinare per questa colonna',
  'Estimate': 'Stima',
  'Time Spent': 'Tempo impiegato',
  'Created': 'Creato il',
  'Completed On': 'Completato il',
  'Departments: {departments} · Assigned tasks: {tasks}': 'Reparti: {departments} · Attività assegnate: {tasks}',
  'A new version is available': 'È disponibile una versione nuova',
  'Reload to get the latest version.': 'Ricarica per passare all’ultima versione.',
  'Reload': 'Ricarica',
  'Completed tasks: {count}': 'Attività completate: {count}',
  '{count} could not be closed: they are waiting for other tasks': '{count} non si sono potute chiudere: aspettano altre attività',
  'Tasks moved to {status}: {count}': 'Attività portate a {status}: {count}',
};
