/** Traduzioni, parte 2. Vedi traduzioni.ts per il criterio delle chiavi. */
export const PARTE_2: Record<string, string> = {
  // --- dati e backup ---
  'Data': 'Dati',
  'Data Management': 'Gestione dei dati',
  'Data Retention (days)': 'Conservazione dei dati (giorni)',
  'Data Safety': 'Sicurezza dei dati',
  'Data exported successfully!': 'Dati esportati',
  'Data imported successfully! Refresh to see changes.':
    'Dati importati. Ricarica per vedere le modifiche.',
  'Download a backup of all tasks, employees, and settings':
    'Scarica un backup di attività, persone e impostazioni',
  'Download a complete backup of all system data including tasks, users, settings, and audit logs.':
    'Scarica un backup completo: attività, utenti, impostazioni e registro delle attività.',
  'Export': 'Esporta',
  'Export Backup': 'Esporta backup',
  'Export Data': 'Esporta dati',
  'Export Report': 'Esporta report',
  'Export as CSV': 'Esporta in CSV',
  'Export as PDF': 'Esporta in PDF',
  'Export, import, or clear your TaskFlow data': 'Esporta, importa o cancella i dati',
  'Import Data': 'Importa dati',
  'Failed to clear data': 'Cancellazione dei dati fallita',
  'Failed to export data': 'Esportazione fallita',
  'Failed to export CSV report': 'Esportazione del report CSV fallita',
  'Failed to export PDF report': 'Esportazione del report PDF fallita',
  'Failed to import data. Please check the file format.':
    'Importazione fallita. Controlla il formato del file.',
  'Failed to read file': 'Lettura del file fallita',
  'File attached successfully!': 'File allegato',
  'File size must be less than 10MB': 'Il file deve essere inferiore a 10 MB',
  'Files are stored securely and can be downloaded or deleted by authorized users.':
    'I file sono conservati in modo sicuro e possono essere scaricati o eliminati da chi ne ha il permesso.',

  // --- eliminazioni e conferme ---
  'Delete Department?': 'Eliminare il dipartimento?',
  'Delete Task?': "Eliminare l'attività?",
  'Delete Team Member?': 'Rimuovere la persona dal team?',
  'Delete Task': 'Elimina attività',
  'Discard Changes': 'Annulla le modifiche',
  'Deselect All': 'Deseleziona tutto',
  'Disable All': 'Disattiva tutto',
  'Enable All': 'Attiva tutto',
  'Declined': 'Rifiutato',

  // --- dipartimenti ---
  'Department': 'Dipartimento',
  'Department Admin Dashboard': 'Cruscotto del responsabile di dipartimento',
  'Department Analytics': 'Analisi per dipartimento',
  'Department Analytics Report': 'Report di analisi per dipartimento',
  'Department Announcements': 'Annunci del dipartimento',
  'Department Color': 'Colore del dipartimento',
  'Department Color Guide': 'Guida ai colori dei dipartimenti',
  'Department Colors': 'Colori dei dipartimenti',
  'Department Details': 'Dettagli del dipartimento',
  'Department Health': 'Salute del dipartimento',
  'Department Information': 'Informazioni sul dipartimento',
  'Department Lead': 'Responsabile del dipartimento',
  'Department Management': 'Gestione dei dipartimenti',
  'Department Performance': 'Prestazioni per dipartimento',
  'Department Performance Overview': 'Quadro delle prestazioni per dipartimento',
  'Department Performance Radar': 'Radar delle prestazioni per dipartimento',
  'Department Settings': 'Impostazioni dei dipartimenti',
  'Department Summary': 'Riepilogo del dipartimento',
  'Department Tasks': 'Attività del dipartimento',
  'Department Templates': 'Modelli di dipartimento',
  'Department name is required': 'Il nome del dipartimento è obbligatorio',
  'Department organization and policies': 'Organizzazione e regole dei dipartimenti',
  'Departments with issues': 'Dipartimenti con problemi',
  'Edit Department': 'Modifica dipartimento',
  'Enable Department Budgets': 'Abilita i budget di dipartimento',
  'Employee Count by Department': 'Numero di persone per dipartimento',
  'Filter tasks by department': 'Filtra le attività per dipartimento',
  'Engineering, Sales, Marketing...': 'Ingegneria, Vendite, Marketing...',
  'Enter department name or select existing':
    'Scrivi il nome del dipartimento o scegline uno esistente',
  'Lead': 'Responsabile',
  'Leads': 'Responsabili',

  // --- persone ---
  'Default User Role': 'Ruolo predefinito',
  'Designate as Team Lead': 'Indica come responsabile del team',
  'Edit Team Member': 'Modifica la persona',
  'Employees': 'Persone',
  'Employee Performance': 'Prestazioni delle persone',
  'Email Address': 'Indirizzo email',
  'Email is required: the account is created from this address':
    "L'email è obbligatoria: l'account viene creato da questo indirizzo",
  'Invalid name or role': 'Nome o ruolo non validi',
  'Full system access': 'Accesso completo al sistema',
  'Highest workload per employee': 'Carico di lavoro più alto per persona',
  'Highest completion rates': 'Percentuali di completamento più alte',
  'Highest Rated': 'Valutazione più alta',
  'Health Score': 'Indice di salute',
  'Inactive': 'Non attivo',

  // --- attività ---
  'Edit Task': 'Modifica attività',
  'Enter task title...': "Titolo dell'attività...",
  'Due Date': 'Scadenza',
  'Default Task Duration (days)': "Durata predefinita di un'attività (giorni)",
  'Escalate Overdue After (days)': 'Segnala le attività in ritardo dopo (giorni)',
  'Estimated Duration': 'Durata stimata',
  'Enable Subtasks': 'Abilita le sotto-attività',
  'Enable Task Dependencies': 'Abilita le dipendenze fra attività',
  'High Priority Tasks': 'Attività ad alta priorità',
  'In Progress Tasks': 'Attività in corso',
  'From creation to completion': 'Dalla creazione al completamento',
  'Key Factors': 'Fattori principali',
  'Generate Estimate': 'Genera la stima',
  'Generate optimal assignment suggestions': 'Genera proposte di assegnazione ottimali',
  'Get intelligent insights and suggestions for your tasks':
    'Analisi e suggerimenti sulle tue attività',
  'Enable Auto-Assignment': "Abilita l'assegnazione automatica",
  'Enable Smart Suggestions': 'Abilita i suggerimenti intelligenti',
  'Enable AI Features': 'Abilita le funzioni AI',
  'Enable all AI-powered features': 'Abilita tutte le funzioni basate su AI',
  'Insights updated!': 'Analisi aggiornate',

  // --- annunci ---
  'Edit announcement': 'Modifica annuncio',
  'Editing announcement': "Modifica dell'annuncio",
  'Enter announcement title': "Titolo dell'annuncio",
  'Enter your announcement message...': "Testo dell'annuncio...",
  'Invalid title or message': 'Titolo o messaggio non validi',
  'Important': 'Importante',
  'Info': 'Informazione',

  // --- notifiche ---
  'Delivery Frequency': 'Frequenza di consegna',
  'Desktop Alerts': 'Avvisi sul desktop',
  'Desktop Notifications': 'Notifiche desktop',
  'Desktop notifications enabled!': 'Notifiche desktop attivate',
  'Desktop notifications were blocked. Please enable them in your browser settings.':
    'Le notifiche desktop sono bloccate. Attivale nelle impostazioni del browser.',
  'Enable Notifications': 'Abilita le notifiche',
  'Enable System Notifications': 'Abilita le notifiche di sistema',
  'Enable Email Notifications': 'Abilita le notifiche via email',
  'Email Notifications': 'Notifiche via email',
  'Get notified via email about task updates':
    'Ricevi via email gli aggiornamenti sulle attività',
  'End Time': 'Ora di fine',
  'Hourly': 'Ogni ora',
  'Last 7 days': 'Ultimi 7 giorni',
  'Last 30 days': 'Ultimi 30 giorni',
  'Last 90 days': 'Ultimi 90 giorni',

  // --- email ---
  'Delivery Logs': 'Registro delle consegne',
  'Device': 'Dispositivo',
  'Device Distribution': 'Distribuzione per dispositivo',
  'Email': 'Email',
  'Email Activity Over Time': 'Attività email nel tempo',
  'Email Analytics': 'Analisi delle email',
  'Email Attachments': 'Allegati delle email',
  'Email Attachment Settings': 'Impostazioni degli allegati',
  'Email Delivery Analytics': 'Analisi di consegna delle email',
  'Email Template Customization': 'Personalizzazione dei modelli email',
  'Email Templates': 'Modelli email',
  'Email Types Distribution': 'Distribuzione per tipo di email',
  'Email attachment settings saved': 'Impostazioni degli allegati salvate',
  'Email subject...': 'Oggetto...',
  'Email template saved successfully!': 'Modello email salvato',
  'Engagement': 'Coinvolgimento',
  'Engagement Metrics': 'Indicatori di coinvolgimento',
  'Exclusion Notifications': 'Avvisi di esclusione',
  'Executable files (.exe, .bat, .sh) are automatically excluded for security reasons':
    'I file eseguibili (.exe, .bat, .sh) sono esclusi automaticamente per sicurezza',
  'Include a note in the email when some attachments exceed size limits':
    "Aggiungi una nota all'email quando alcuni allegati superano il limite",
  'Include attachments in emails': 'Includi gli allegati nelle email',
  'Individual files larger than this will be excluded from emails':
    'I file più grandi di questa soglia vengono esclusi dalle email',
  'Images': 'Immagini',
  'HTML Template': 'Modello HTML',
  'Latest email delivery activity': 'Ultime consegne',
  'Editor': 'Editor',

  // --- sistema ---
  'Date Format': 'Formato della data',
  'Eastern Time': 'Fuso orario orientale',
  'Enable API Access': "Abilita l'accesso API",
  'Enable Audit Log': 'Abilita il registro delle attività',
  'Enable IP Whitelist': "Abilita l'elenco di IP consentiti",
  'Enable Slack Integration': "Abilita l'integrazione con Slack",
  'Enable Two-Factor Authentication': "Abilita l'autenticazione a due fattori",
  'Enforce password complexity rules': 'Imponi regole di complessità della password',
  'Expiration Date': 'Data di scadenza',
  'External service connections': 'Collegamenti a servizi esterni',
  'General': 'Generale',
  'General Settings': 'Impostazioni generali',
  'Integrations': 'Integrazioni',
  'Invalid IP address format': "Formato dell'indirizzo IP non valido",
  'IP address added': 'Indirizzo IP aggiunto',
  'IP address removed': 'Indirizzo IP rimosso',
  'Last 10 system changes': 'Ultime 10 modifiche di sistema',
  'Iterations': 'Iterazioni',
  'Launch Info': 'Informazioni sul lancio',
  'Language': 'Lingua',
  'English': 'Inglese',
  'Italian': 'Italiano',
  'French': 'Francese',
  'German': 'Tedesco',
  'GPT-4o (More capable)': 'GPT-4o (più capace)',
  'GPT-4o-mini (Faster)': 'GPT-4o-mini (più veloce)',

  // --- aiuto e riscontri ---
  'Help': 'Aiuto',
  'Help us improve TaskFlow by sharing your thoughts, suggestions, or reporting issues.':
    'Aiutaci a migliorare TaskFlow: raccontaci cosa pensi, suggerisci o segnala un problema.',
  'Everything you need to know about using TaskFlow effectively':
    'Tutto quello che serve per usare bene TaskFlow',
  'Feature Request': 'Richiesta di funzionalità',
  'Feature Requests': 'Richieste di funzionalità',
  'Features': 'Funzionalità',
  'Feedback Type': 'Tipo di riscontro',
  'Feedback status updated': 'Stato del riscontro aggiornato',
  'Give Feedback': 'Lascia un riscontro',
  'How would you rate your experience?': 'Come valuti la tua esperienza?',
  'How do I access analytics?': 'Come accedo alle analisi?',
  'How do I add comments to tasks?': "Come aggiungo commenti a un'attività?",
  'How do I add team members?': 'Come aggiungo persone al team?',
  'How do I create a new task?': 'Come creo una nuova attività?',
  'How do I edit an existing task?': "Come modifico un'attività esistente?",
  'How do I manage departments?': 'Come gestisco i dipartimenti?',
  'How do bulk operations work?': 'Come funzionano le operazioni multiple?',
  'How does AI Auto-Assignment work?': "Come funziona l'assegnazione automatica AI?",
  'Improvement Suggestion': 'Suggerimento di miglioramento',
  'Improvements': 'Miglioramenti',
  "I'll Do It Later": 'Lo farò più tardi',
  'Detailed Performance Metrics': 'Indicatori dettagliati delle prestazioni',
  'Il file non contiene dati da ripristinare': 'The file contains no data to restore',
};
