/** Traduzioni francesi. Chiavi identiche a quelle italiane/inglesi. */
export const TESTI_FR: Record<string, string> = {
  // --- chiavi semantiche (partendo dall'italiano di i18n.ts) ---
  // accesso
  'app.sottotitolo': 'Gérez le travail de votre équipe',
  'login.titolo': 'Se connecter',
  'login.descrizione': 'Saisissez vos identifiants pour continuer.',
  'login.email': 'E-mail',
  'login.password': 'Mot de passe',
  'login.entra': 'Se connecter',
  'login.inCorso': 'Connexion en cours...',
  'login.emailObbligatoria': "L'e-mail est obligatoire",
  'login.emailNonValida': 'Saisissez une adresse e-mail valide',
  'login.passwordObbligatoria': 'Le mot de passe est obligatoire',
  'login.erroreGenerico': "Une erreur inattendue s'est produite",
  'login.operazioneFallita': "L'opération a échoué",
  'login.accountDaAmministratore': "Les comptes sont créés par l'administrateur.",
  'login.contattaAmministratore': 'Si vous ne parvenez pas à vous connecter, contactez-le.',
  'login.passwordDimenticata': 'Mot de passe oublié ?',
  'login.invioInCorso': 'Envoi en cours...',
  'login.inserisciEmailPerRipristino':
    'Saisissez votre e-mail, puis demandez la réinitialisation',
  'login.ripristinoInviato':
    "Si l'adresse correspond à un compte, vous recevrez un lien pour réinitialiser votre mot de passe. Vérifiez aussi vos spams.",

  // nuova password
  'password.sottotitolo': 'Choisissez un nouveau mot de passe',
  'password.titolo': 'Nouveau mot de passe',
  'password.descrizione':
    'Définissez le mot de passe que vous utiliserez désormais pour vous connecter.',
  'password.nuova': 'Nouveau mot de passe',
  'password.ripeti': 'Répétez le mot de passe',
  'password.minimo': 'Au moins 8 caractères.',
  'password.troppoCorta': 'Le mot de passe doit contenir au moins 8 caractères',
  'password.nonCoincidono': 'Les deux mots de passe ne correspondent pas',
  'password.salva': 'Enregistrer le nouveau mot de passe',
  'password.salvataggio': 'Enregistrement...',
  'password.annullaEsci': 'Annuler et se déconnecter',

  // organizzazioni
  'org.nessuna': 'Aucune organisation associée à ce compte',
  'org.creaTitolo': 'Créez votre organisation',
  'org.creaDescrizione':
    "Si vous configurez l'application pour la première fois, créez ici votre espace de travail : vous en deviendrez le propriétaire et pourrez inviter les autres. Si vous devez rejoindre une organisation existante, demandez à un administrateur de vous ajouter.",
  'org.nome': "Nom de l'organisation",
  'org.crea': 'Créer une organisation',
  'org.creazione': 'Création...',
  'org.nuovaTitolo': 'Nouvelle organisation',
  'org.nuovaDescrizione':
    "Vous deviendrez le propriétaire du nouvel espace de travail, qui démarre vide. Les données de l'organisation actuelle ne sont pas modifiées.",
  'org.attiva': 'Organisation active',
  'org.creaNuova': 'Créer une nouvelle organisation',
  'org.creata': 'Organisation "{nome}" créée',
  'org.creazioneFallita': 'Échec de la création',

  // account disattivato
  'account.disattivato': 'Compte désactivé',
  'account.disattivatoDescrizione':
    "Ce compte a été désactivé par un administrateur. Contactez-le si vous pensez qu'il s'agit d'une erreur.",

  // credenziali
  'credenziali.titolo': 'Identifiants de connexion',
  'credenziali.descrizione':
    "Remettez ces identifiants à l'utilisateur : le mot de passe provisoire n'est pas envoyé par e-mail et ne sera plus visible après la fermeture de cette fenêtre.",
  'credenziali.annotate': "J'ai noté les identifiants",

  // comuni
  'comune.esci': 'Se déconnecter',
  'comune.annulla': 'Annuler',
  'comune.caricamento': 'Chargement…',
  'comune.lingua': 'Langue',
  'comune.nessunaOrganizzazione': 'Aucune organisation active',
  'comune.sessioneScaduta': 'Session expirée, reconnectez-vous',
  'comune.inizializzazioneFallita': "Échec de l'initialisation",
  'comune.richiestaFallita': 'Échec de la requête ({stato})',
  'comune.modificaNonSalvata': 'Modification non enregistrée',
  'ai.nonConfigurata': "Les fonctions IA ne sont pas configurées. Réessayer ne sert à rien : contactez un administrateur.",
  'ai.nonDisponibile': 'Le service IA est injoignable pour le moment. Réessayez dans un instant.',
  'ai.tempoScaduto': 'Le service IA a mis trop de temps. Réessayez.',
  'ai.limiteRaggiunto': 'Vous avez atteint la limite de requêtes IA. Réessayez plus tard.',
  'ai.testoTroppoLungo': 'Le texte est trop long pour être traité.',
  'ai.rifiutata': "Le service IA n'a pas accepté cette requête.",
  'email.nonPartita': "Notification enregistrée, mais l'e-mail n'est pas parti",

  // --- chiavi = stringa inglese (partendo dall'inglese) ---
  // generale, azioni ricorrenti
  'Cancel': 'Annuler',
  'Close': 'Fermer',
  'Save': 'Enregistrer',
  'Delete': 'Supprimer',
  'Edit': 'Modifier',
  'Apply': 'Appliquer',
  'Back': 'Retour',
  'Next': 'Suivant',
  'Clear': 'Vider',
  'Clear all': 'Tout vider',
  'Create New': 'Créer',
  'Complete': 'Terminer',
  'Bulk': 'Sélection multiple',
  'Analysis': 'Analyse',
  'Analytics': 'Analyses',
  'Dashboard': 'Tableau de bord',
  'Category': 'Catégorie',
  'Custom': 'Personnalisé',
  'Archived': 'Archivé',
  'Already exists': 'Existe déjà',
  'Confirm Delete': 'Confirmer la suppression',
  'Are you sure? This action cannot be undone!':
    'Êtes-vous sûr ? Cette action est irréversible.',
  'Are you sure you want to remove': 'Voulez-vous vraiment supprimer',
  'All time': 'Depuis le début',
  'All types': 'Tous les types',
  'All Categories': 'Toutes les catégories',
  'All Departments': 'Tous les services',
  'All Departments Selected': 'Tous les services sélectionnés',
  'All Members': 'Tous les membres',
  'All Priority': 'Toutes les priorités',
  'All Status': 'Tous les statuts',
  'No data available': 'Aucune donnée disponible',

  // stati e priorità
  'Active': 'Actif',
  'Completed': 'Terminée',
  'In Progress': 'En cours',
  'Not Started': 'À commencer',
  'Overdue': 'En retard',
  'Priority': 'Priorité',
  'Status': 'Statut',
  'High': 'Haute',
  'High Priority': 'Priorité haute',
  'Description': 'Description',

  // attività
  'Task': 'Tâche',
  'Tasks': 'Tâches',
  'Add Task': 'Ajouter une tâche',
  'Create Task': 'Créer une tâche',
  'Create New Task': 'Nouvelle tâche',
  'Total Tasks': 'Tâches totales',
  'Active Tasks': 'Tâches actives',
  'Completed Tasks': 'Tâches terminées',
  'Assigned Tasks': 'Tâches assignées',
  'View Task': 'Ouvrir la tâche',
  'Assign To': 'Assigner à',
  'Assignee': 'Responsable',
  'Add task details...': 'Ajoutez les détails...',
  'Add a comment...': 'Écrivez un commentaire...',
  'Add comments and attachments': 'Ajoutez des commentaires et des pièces jointes',
  "Add a new task to your team's workflow. Fill in the details below.":
    "Ajoutez une nouvelle tâche au travail de l'équipe. Remplissez les détails ci-dessous.",
  "All changes are automatically tracked in the task's activity history.":
    "Toutes les modifications sont enregistrées dans l'historique de la tâche.",
  'Comment added!': 'Commentaire ajouté',
  'Comment deleted': 'Commentaire supprimé',
  'Comment updated!': 'Commentaire mis à jour',
  'Comments and mentions': 'Commentaires et mentions',
  'Attachment removed': 'Pièce jointe supprimée',
  'Completion Rate': 'Taux de réalisation',
  'Average Completion Time': 'Temps moyen de réalisation',
  'Avg. Completion Time': 'Temps moyen de réalisation',
  'Avg Time': 'Temps moyen',
  'Avg Tasks': 'Tâches moyennes',
  'Avg Tasks per Member': 'Tâches moyennes par membre',
  'Avg/Employee': 'Moyenne par personne',
  'Avg/User': 'Moyenne par utilisateur',
  'Current state of all tasks': 'État actuel de toutes les tâches',
  'Consider task priorities and deadlines': 'Tient compte des priorités et des échéances',
  'Auto-archive Completed After (days)': 'Archiver les tâches terminées après (jours)',
  'Allow Task Deletion': 'Autoriser la suppression des tâches',
  'Configure task behavior and policies': 'Comportement et règles des tâches',

  // persone e servizi
  'Admin': 'Administrateur',
  'Admin (Super Admin)': 'Administrateur (super administrateur)',
  'Add User': 'Ajouter un utilisateur',
  'Add Team Member': 'Ajouter un membre',
  'Add a new member to your team': 'Ajoutez une personne à votre équipe',
  'Active Members': 'Membres actifs',
  'Active Users': 'Utilisateurs actifs',
  'Active Team Members': "Membres actifs de l'équipe",
  'Avatar URL': "URL de l'image",
  'Brief description about the team member...': 'Brève description de la personne...',
  'Departments': 'Services',
  'Department already added': 'Service déjà ajouté',
  'Active Departments': 'Services actifs',
  'Active departments': 'Services actifs',
  'Archived Departments': 'Services archivés',
  'Archive inactive departments': 'Archiver les services inactifs',
  'Add Department': 'Ajouter un service',
  'Add New Department': 'Nouveau service',
  'Create Department': 'Créer un service',
  'Custom Departments': 'Services personnalisés',
  'Assign Departments': 'Assigner des services',
  'Add to existing departments': 'Ajouter aux services existants',
  'Allow Multiple Departments': 'Autoriser plusieurs services',
  'Assign employees to multiple departments':
    'Assigner les personnes à plusieurs services',
  'A department with this name already exists': 'Un service portant ce nom existe déjà',
  'Brief description of this department...': 'Brève description du service...',
  'Busiest Department': 'Service le plus chargé',
  'Busiest Departments': 'Services les plus chargés',
  'Choose departments to assign to the selected team members':
    'Choisissez les services à assigner aux personnes sélectionnées',
  'Create a new department to organize your team structure':
    "Créez un service pour organiser la structure de l'équipe",
  'Create and manage departments, assign leads, and track team organization':
    "Créez et gérez les services, désignez les responsables et suivez l'organisation",
  'Create new departments with details (name, description, color, lead, budget)':
    'Créez de nouveaux services avec nom, description, couleur, responsable et budget',
  'Create your first department to start organizing your team':
    "Créez le premier service pour commencer à organiser l'équipe",
  'Add departments to team members to see department analytics':
    'Assignez des services aux personnes pour voir les analyses par service',
  'Analytics across all departments': 'Analyses sur tous les services',
  'Complete breakdown by department': 'Détail complet par service',
  'Auto-assign color': 'Couleur attribuée automatiquement',
  'Annual Budget': 'Budget annuel',
  'Analyze team member workloads': "Analysez la charge de travail de l'équipe",
  'Custom Permissions': 'Autorisations personnalisées',
  'Contact your administrator to request changes to your role or permissions.':
    'Contactez un administrateur pour demander une modification de votre rôle ou de vos autorisations.',

  // analisi
  'Analytics Dashboard': "Tableau de bord d'analyse",
  'Average Engagement': 'Engagement moyen',
  'Avg Rating': 'Note moyenne',
  'Comprehensive analytics for your team': 'Analyses complètes de votre équipe',
  'Comprehensive performance insights': 'Vue complète des performances',
  'Complete performance breakdown': 'Détail complet des performances',
  'Complete system overview and analytics': "Vue d'ensemble du système et analyses",
  'Analyzing...': 'Analyse en cours...',
  'CSV report downloaded successfully!': 'Rapport CSV téléchargé',
  'Can I export analytics reports?': "Puis-je exporter les rapports d'analyse ?",
  'Can I attach files to tasks?': 'Puis-je joindre des fichiers aux tâches ?',

  // IA
  'AI Assistant': 'Assistant IA',
  'AI Auto-Assign': 'Attribution automatique IA',
  'AI Features': 'Fonctions IA',
  'AI Insights': 'Analyses IA',
  'AI Model': 'Modèle IA',
  'AI Recommendation': 'Recommandation IA',
  'AI Assignment Suggestions': "Propositions d'attribution IA",
  'AI Duration & Deadline Estimate': "Estimation IA de durée et d'échéance",
  'AI estimate generated!': 'Estimation IA générée',
  'Applied AI suggestion!': 'Suggestion IA appliquée',
  'Apply All Assignments': 'Appliquer toutes les attributions',
  'Apply This Suggestion': 'Appliquer cette suggestion',
  'Assignment Mode': "Mode d'attribution",
  'Ask me anything about your tasks and team!':
    "Posez-moi vos questions sur les tâches et l'équipe",
  'Ask me anything about your tasks...': 'Posez-moi une question sur vos tâches...',
  'Configure AI-powered capabilities': "Configurez les fonctions basées sur l'IA",

  // annunci e riscontri
  'Announcement': 'Annonce',
  'Announcement deleted': 'Annonce supprimée',
  'Announcement posted!': 'Annonce publiée',
  'Announcement updated!': 'Annonce mise à jour',
  'Announcement updated successfully!': 'Annonce mise à jour',
  'Create announcements': 'Créer des annonces',
  'Be the first to share your thoughts!': 'Soyez le premier à donner votre avis',
  'Brief summary of your feedback': 'Bref résumé de votre retour',
  'Bug Report': "Signalement d'un problème",
  'Bug Reports': 'Signalements de problèmes',

  // notifiche
  'Choose which events trigger notifications':
    'Choisissez les événements qui déclenchent une notification',
  'Control how often you receive notifications':
    'À quelle fréquence recevoir les notifications',
  'Control when and how you receive notifications':
    'Quand et comment recevoir les notifications',
  'All notification types disabled': 'Tous les types de notification désactivés',
  'All notification types enabled': 'Tous les types de notification activés',
  'Batched (every 15 min)': 'Groupées (toutes les 15 minutes)',
  'Daily digest': 'Résumé quotidien',
  'Daily Digest Time': 'Heure du résumé quotidien',

  // e-mail
  'Bounce Rate': 'Taux de non-remise',
  'Click': 'Clic',
  'Clicks': 'Clics',
  'Click Rate': 'Taux de clic',
  'Click-to-Open Rate': 'Clics sur les e-mails ouverts',
  'Combined open and click rate average': 'Moyenne des ouvertures et des clics',
  'Attachment Inclusion': 'Inclusion des pièces jointes',
  'Allowed File Types': 'Types de fichiers autorisés',
  'Currently allowed file types for email attachments':
    'Types de fichiers actuellement autorisés en pièce jointe',
  'Alert users when attachments cannot be included':
    "Avertir lorsqu'une pièce jointe ne peut pas être incluse",
  'Configure how task attachments are included in email notifications':
    'Comment inclure les pièces jointes des tâches dans les e-mails de notification',
  'Control whether task attachments are sent with email notifications':
    'Décide si les pièces jointes des tâches sont envoyées avec les e-mails',
  'Customize email notifications sent to users for various task events':
    'Personnalisez les e-mails envoyés pour les différents événements des tâches',
  'Available Variables': 'Variables disponibles',
  'Click a variable to insert it at cursor position':
    "Cliquez sur une variable pour l'insérer à la position du curseur",
  'Best regards,': 'Cordialement,',

  // amministrazione
  'Access email settings and system configuration':
    'Accédez aux paramètres e-mail et à la configuration du système',
  'Active Settings Summary': 'Résumé des paramètres actifs',
  'Application Name': "Nom de l'application",
  'Company Name': "Nom de l'entreprise",
  'Basic application configuration': "Configuration de base de l'application",
  'Configure system-wide settings and preferences':
    'Configurez les paramètres généraux du système',
  'Current system status and statistics': 'État actuel du système et statistiques',
  'Current data usage across all collections': 'Espace occupé par les données',
  'Audit Entries': 'Entrées du journal',
  'Audit Log': "Journal d'activité",
  'Audit Logging': "Enregistrement de l'activité",
  'Audit log cleared': 'Journal vidé',
  'Clear Audit Log': 'Vider le journal',
  'Clear All Data': 'Effacer toutes les données',
  'All data cleared successfully': 'Toutes les données ont été effacées',
  'Backup & Restore': 'Sauvegarde et restauration',
  'Backup, restore, and manage system data':
    'Sauvegarde, restauration et gestion des données',
  'Changes discarded': 'Modifications annulées',
  'Allow Self Registration': "Autoriser l'inscription autonome",
  'Allowed IP Addresses': 'Adresses IP autorisées',
  'Add IP Address': 'Ajouter une adresse IP',
  'Central Time': 'Fuseau horaire du Centre',
  'Custom Time Range': 'Période personnalisée',
  'DD/MM/YYYY': 'JJ/MM/AAAA',
  'After 81 iterations, your application is ready to deploy.':
    'Après 81 itérations, votre application est prête à être déployée.',
  'Click the': 'Cliquez sur',

  // dati e sauvegarde
  'Data': 'Données',
  'Data Management': 'Gestion des données',
  'Data Retention (days)': 'Conservation des données (jours)',
  'Data Safety': 'Sécurité des données',
  'Data exported successfully!': 'Données exportées',
  'Data imported successfully! Refresh to see changes.':
    'Données importées. Actualisez pour voir les modifications.',
  'Download a backup of all tasks, employees, and settings':
    'Téléchargez une sauvegarde des tâches, des personnes et des paramètres',
  'Download a complete backup of all system data including tasks, users, settings, and audit logs.':
    "Téléchargez une sauvegarde complète : tâches, utilisateurs, paramètres et journal d'activité.",
  'Export': 'Exporter',
  'Export Backup': 'Exporter la sauvegarde',
  'Export Data': 'Exporter les données',
  'Export Report': 'Exporter le rapport',
  'Export as CSV': 'Exporter en CSV',
  'Export as PDF': 'Exporter en PDF',
  'Export, import, or clear your TaskFlow data':
    'Exportez, importez ou effacez vos données',
  'Import Data': 'Importer des données',
  'Failed to clear data': "Échec de l'effacement des données",
  'Failed to export data': "Échec de l'exportation",
  'Failed to export CSV report': "Échec de l'exportation du rapport CSV",
  'Failed to export PDF report': "Échec de l'exportation du rapport PDF",
  'Failed to import data. Please check the file format.':
    "Échec de l'importation. Vérifiez le format du fichier.",
  'Failed to read file': 'Échec de la lecture du fichier',
  'File attached successfully!': 'Fichier joint',
  'File size must be less than 10MB': 'Le fichier doit faire moins de 10 Mo',
  'Files are stored securely and can be downloaded or deleted by authorized users.':
    'Les fichiers sont conservés de façon sécurisée et peuvent être téléchargés ou supprimés par les personnes autorisées.',

  // eliminazioni e conferme
  'Delete Department?': 'Supprimer le service ?',
  'Delete Task?': 'Supprimer la tâche ?',
  'Delete Team Member?': "Retirer la personne de l'équipe ?",
  'Delete Task': 'Supprimer la tâche',
  'Discard Changes': 'Annuler les modifications',
  'Deselect All': 'Tout désélectionner',
  'Disable All': 'Tout désactiver',
  'Enable All': 'Tout activer',
  'Declined': 'Refusé',

  // servizi
  'Department': 'Service',
  'Department Admin Dashboard': 'Tableau de bord du responsable de service',
  'Department Analytics': 'Analyses par service',
  'Department Analytics Report': "Rapport d'analyse par service",
  'Department Announcements': 'Annonces du service',
  'Department Color': 'Couleur du service',
  'Department Color Guide': 'Guide des couleurs des services',
  'Department Colors': 'Couleurs des services',
  'Department Details': 'Détails du service',
  'Department Health': 'Santé du service',
  'Department Information': 'Informations sur le service',
  'Department Lead': 'Responsable du service',
  'Department Management': 'Gestion des services',
  'Department Performance': 'Performances par service',
  'Department Performance Overview': "Vue d'ensemble des performances par service",
  'Department Performance Radar': 'Radar des performances par service',
  'Department Settings': 'Paramètres des services',
  'Department Summary': 'Résumé du service',
  'Department Tasks': 'Tâches du service',
  'Department Templates': 'Modèles de service',
  'Department name is required': 'Le nom du service est obligatoire',
  'Department organization and policies': 'Organisation et règles des services',
  'Departments with issues': 'Services avec des problèmes',
  'Edit Department': 'Modifier le service',
  'Enable Department Budgets': 'Activer les budgets de service',
  'Employee Count by Department': 'Nombre de personnes par service',
  'Filter tasks by department': 'Filtrer les tâches par service',
  'Engineering, Sales, Marketing...': 'Ingénierie, Ventes, Marketing...',
  'Enter department name or select existing':
    'Saisissez le nom du service ou choisissez-en un existant',
  'Lead': 'Responsable',
  'Leads': 'Responsables',

  // persone
  'Default User Role': 'Rôle par défaut',
  'Designate as Team Lead': "Désigner comme responsable de l'équipe",
  'Edit Team Member': 'Modifier la personne',
  'Employees': 'Personnes',
  'Employee Performance': 'Performances des personnes',
  'Email Address': 'Adresse e-mail',
  'Email is required: the account is created from this address':
    "L'e-mail est obligatoire : le compte est créé à partir de cette adresse",
  'Invalid name or role': 'Nom ou rôle non valides',
  'Full system access': 'Accès complet au système',
  'Highest workload per employee': 'Charge de travail la plus élevée par personne',
  'Highest completion rates': 'Taux de réalisation les plus élevés',
  'Highest Rated': 'Mieux noté',
  'Health Score': 'Indice de santé',
  'Inactive': 'Inactif',

  // attività
  'Edit Task': 'Modifier la tâche',
  'Enter task title...': 'Titre de la tâche...',
  'Due Date': 'Échéance',
  'Default Task Duration (days)': "Durée par défaut d'une tâche (jours)",
  'Escalate Overdue After (days)': 'Signaler les tâches en retard après (jours)',
  'Estimated Duration': 'Durée estimée',
  'Enable Subtasks': 'Activer les sous-tâches',
  'Enable Task Dependencies': 'Activer les dépendances entre tâches',
  'High Priority Tasks': 'Tâches à priorité haute',
  'In Progress Tasks': 'Tâches en cours',
  'From creation to completion': 'De la création à la réalisation',
  'Key Factors': 'Facteurs principaux',
  'Generate Estimate': "Générer l'estimation",
  'Generate optimal assignment suggestions':
    "Générer des propositions d'attribution optimales",
  'Get intelligent insights and suggestions for your tasks':
    'Analyses et suggestions sur vos tâches',
  'Enable Auto-Assignment': "Activer l'attribution automatique",
  'Enable Smart Suggestions': 'Activer les suggestions intelligentes',
  'Enable AI Features': 'Activer les fonctions IA',
  'Enable all AI-powered features': "Activer toutes les fonctions basées sur l'IA",
  'Insights updated!': 'Analyses mises à jour',

  // annunci
  'Edit announcement': "Modifier l'annonce",
  'Editing announcement': "Modification de l'annonce",
  'Enter announcement title': "Titre de l'annonce",
  'Enter your announcement message...': "Texte de l'annonce...",
  'Invalid title or message': 'Titre ou message non valides',
  'Important': 'Important',
  'Info': 'Information',

  // notifiche
  'Delivery Frequency': 'Fréquence de remise',
  'Desktop Alerts': 'Alertes sur le bureau',
  'Desktop Notifications': 'Notifications sur le bureau',
  'Desktop notifications enabled!': 'Notifications sur le bureau activées',
  'Desktop notifications were blocked. Please enable them in your browser settings.':
    'Les notifications sur le bureau sont bloquées. Activez-les dans les paramètres de votre navigateur.',
  'Enable Notifications': 'Activer les notifications',
  'Enable System Notifications': 'Activer les notifications système',
  'Enable Email Notifications': 'Activer les notifications par e-mail',
  'Email Notifications': 'Notifications par e-mail',
  'Get notified via email about task updates':
    'Recevez par e-mail les mises à jour des tâches',
  'End Time': 'Heure de fin',
  'Hourly': 'Toutes les heures',
  'Last 7 days': 'Les 7 derniers jours',
  'Last 30 days': 'Les 30 derniers jours',
  'Last 90 days': 'Les 90 derniers jours',

  // e-mail
  'Delivery Logs': 'Journal des remises',
  'Device': 'Appareil',
  'Device Distribution': 'Répartition par appareil',
  'Email': 'E-mail',
  'Email Activity Over Time': 'Activité e-mail dans le temps',
  'Email Analytics': 'Analyses des e-mails',
  'Email Attachments': 'Pièces jointes des e-mails',
  'Email Attachment Settings': 'Paramètres des pièces jointes',
  'Email Delivery Analytics': 'Analyses de remise des e-mails',
  'Email Template Customization': "Personnalisation des modèles d'e-mail",
  'Email Templates': "Modèles d'e-mail",
  'Email Types Distribution': "Répartition par type d'e-mail",
  'Email attachment settings saved': 'Paramètres des pièces jointes enregistrés',
  'Email subject...': 'Objet...',
  'Email template saved successfully!': "Modèle d'e-mail enregistré",
  'Engagement': 'Engagement',
  'Engagement Metrics': "Indicateurs d'engagement",
  'Exclusion Notifications': "Avis d'exclusion",
  'Executable files (.exe, .bat, .sh) are automatically excluded for security reasons':
    'Les fichiers exécutables (.exe, .bat, .sh) sont exclus automatiquement pour des raisons de sécurité',
  'Include a note in the email when some attachments exceed size limits':
    "Ajouter une note à l'e-mail lorsque certaines pièces jointes dépassent la limite",
  'Include attachments in emails': 'Inclure les pièces jointes dans les e-mails',
  'Individual files larger than this will be excluded from emails':
    'Les fichiers plus volumineux que ce seuil sont exclus des e-mails',
  'Images': 'Images',
  'HTML Template': 'Modèle HTML',
  'Latest email delivery activity': 'Dernières remises',
  'Editor': 'Éditeur',

  // sistema
  'Date Format': 'Format de la date',
  'Eastern Time': "Fuseau horaire de l'Est",
  'Enable API Access': "Activer l'accès API",
  'Enable Audit Log': "Activer le journal d'activité",
  'Enable IP Whitelist': 'Activer la liste des IP autorisées',
  'Enable Slack Integration': "Activer l'intégration Slack",
  'Enable Two-Factor Authentication': "Activer l'authentification à deux facteurs",
  'Enforce password complexity rules':
    'Imposer des règles de complexité du mot de passe',
  'Expiration Date': "Date d'expiration",
  'External service connections': 'Connexions à des services externes',
  'General': 'Général',
  'General Settings': 'Paramètres généraux',
  'Integrations': 'Intégrations',
  'Invalid IP address format': "Format d'adresse IP non valide",
  'IP address added': 'Adresse IP ajoutée',
  'IP address removed': 'Adresse IP supprimée',
  'Last 10 system changes': 'Les 10 dernières modifications du système',
  'Iterations': 'Itérations',
  'Launch Info': 'Informations sur le lancement',
  'Language': 'Langue',
  'English': 'Anglais',
  'Italian': 'Italien',
  'French': 'Français',
  'German': 'Allemand',
  'GPT-4o (More capable)': 'GPT-4o (plus performant)',
  'GPT-4o-mini (Faster)': 'GPT-4o-mini (plus rapide)',

  // aiuto e riscontri
  'Help': 'Aide',
  'Help us improve TaskFlow by sharing your thoughts, suggestions, or reporting issues.':
    'Aidez-nous à améliorer TaskFlow : dites-nous ce que vous en pensez, proposez une idée ou signalez un problème.',
  'Everything you need to know about using TaskFlow effectively':
    "Tout ce qu'il faut savoir pour bien utiliser TaskFlow",
  'Feature Request': 'Demande de fonctionnalité',
  'Feature Requests': 'Demandes de fonctionnalités',
  'Features': 'Fonctionnalités',
  'Feedback Type': 'Type de retour',
  'Feedback status updated': 'Statut du retour mis à jour',
  'Give Feedback': 'Donner un retour',
  'How would you rate your experience?': 'Comment évaluez-vous votre expérience ?',
  'How do I access analytics?': 'Comment accéder aux analyses ?',
  'How do I add comments to tasks?': 'Comment ajouter des commentaires à une tâche ?',
  'How do I add team members?': "Comment ajouter des personnes à l'équipe ?",
  'How do I create a new task?': 'Comment créer une nouvelle tâche ?',
  'How do I edit an existing task?': 'Comment modifier une tâche existante ?',
  'How do I manage departments?': 'Comment gérer les services ?',
  'How do bulk operations work?': 'Comment fonctionnent les opérations multiples ?',
  'How does AI Auto-Assignment work?': "Comment fonctionne l'attribution automatique IA ?",
  'Improvement Suggestion': "Suggestion d'amélioration",
  'Improvements': 'Améliorations',
  "I'll Do It Later": 'Je le ferai plus tard',
  'Detailed Performance Metrics': 'Indicateurs détaillés des performances',
  'Il file non contiene dati da ripristinare':
    'Le fichier ne contient aucune donnée à restaurer',

  // anagrafica e ruoli
  'Leave blank to auto-generate an avatar': 'Laissez vide pour générer une image',
  'Location': 'Lieu',
  'Manage': 'Gérer',
  'Manage Role & Permissions': 'Gérer le rôle et les autorisations',
  'Manage Team': "Gérer l'équipe",
  'Manage Users': 'Gérer les utilisateurs',
  'Manage all users and departments': 'Gérer tous les utilisateurs et les services',
  'Manage tasks within their department(s)': 'Gère les tâches de ses services',
  'Manage your team members, roles, and departments':
    "Gérez les membres de l'équipe, les rôles et les services",
  "Manage your team's work efficiently": 'Organisez le travail de votre équipe',
  'Manager': 'Manager',
  'Manager (Department Admin)': 'Manager (responsable de service)',
  'Member': 'Membre',
  'Name': 'Nom',
  'Name and role are required': 'Le nom et le rôle sont obligatoires',
  'Phone Number': 'Numéro de téléphone',
  'Role': 'Rôle',
  'Role and permissions updated successfully': 'Rôle et autorisations mis à jour',
  'Need different permissions?': "Besoin d'autorisations différentes ?",
  'Override default role permissions with custom settings':
    'Remplacez les autorisations par défaut du rôle par des réglages personnalisés',
  'Permission Status': 'État des autorisations',
  'Search by name, role, email, department, skills...':
    'Rechercher par nom, rôle, e-mail, service, compétences...',
  'Select All': 'Tout sélectionner',
  'Set Active': 'Marquer comme actif',
  'Set Inactive': 'Marquer comme inactif',
  'Senior Developer': 'Développeur senior',
  'San Francisco, CA': 'Lyon, France',
  'New York, Remote...': 'Paris, à distance...',
  'React, TypeScript, Node.js': 'React, TypeScript, Node.js',

  // servizi
  'No Department Data': 'Aucune donnée sur les services',
  'No department data available': 'Aucune donnée disponible sur les services',
  'No departments selected. Add departments above.':
    'Aucun service sélectionné. Ajoutez-en un ci-dessus.',
  'No departments yet': 'Aucun service pour le moment',
  'No employees assigned to this department': 'Aucune personne assignée à ce service',
  'Multi-metric comparison across departments':
    'Comparaison sur plusieurs indicateurs entre services',
  'Quick insights for your departments': 'Aperçu rapide de vos services',
  'Quick-start templates for common department types. Choose individual departments or create entire categories at once.':
    "Modèles prêts à l'emploi pour les services les plus courants. Choisissez un service ou créez des catégories entières en une fois.",
  'Replace all departments': 'Remplacer tous les services',
  'Require Department Assignment': "Exiger l'assignation à un service",
  'Select All Departments': 'Sélectionner tous les services',
  'Select a team lead (optional)': 'Choisissez un responsable (facultatif)',
  'Set department leads': 'Définir les responsables des services',
  'Please select at least one department': 'Sélectionnez au moins un service',

  // attività
  'Low Priority': 'Priorité basse',
  'Medium': 'Moyenne',
  'Medium Priority': 'Priorité moyenne',
  'My Dashboard': 'Mon tableau de bord',
  'My Tasks': 'Mes tâches',
  'Match skills and departments': 'Fait correspondre compétences et services',
  'New Task Assigned': 'Nouvelle tâche assignée',
  'New Comment': 'Nouveau commentaire',
  'New Announcement': 'Nouvelle annonce',
  'Not Started Tasks': 'Tâches à commencer',
  'No task data available yet': 'Aucune donnée sur les tâches pour le moment',
  'No tasks found': 'Aucune tâche trouvée',
  'No unassigned tasks to assign': 'Aucune tâche à assigner',
  'No upcoming deadlines in the next 3 days':
    'Aucune échéance dans les 3 prochains jours',
  'Overdue Tasks': 'Tâches en retard',
  'Overdue tasks (priority)': 'Tâches en retard (priorité)',
  'Priority Breakdown': 'Répartition par priorité',
  'Priority Distribution': 'Distribution des priorités',
  'Priority Warnings': 'Alertes de priorité',
  'Please enter a task title first': "Saisissez d'abord le titre de la tâche",
  'Reminder Before Due (days)': "Rappel avant l'échéance (jours)",
  'Require Task Approval': "Exiger l'approbation des tâches",
  'Requiring immediate attention': 'Nécessitent une attention immédiate',
  'Needs Attention': 'Nécessite une attention',
  'Need attention': 'Nécessitent une attention',
  'Review the suggested task assignments below. These are optimized for workload balance and task requirements.':
    'Vérifiez les attributions proposées ci-dessous : elles tiennent compte de la charge de travail et des exigences des tâches.',
  'Review the suggestions before applying them.':
    'Vérifiez les suggestions avant de les appliquer.',

  // messaggi vuoti
  'No active employees available': 'Aucune personne active disponible',
  'No activity yet': 'Aucune activité pour le moment',
  'No announcements': 'Aucune annonce',
  'No attachments yet': 'Aucune pièce jointe pour le moment',
  'No audit entries yet': 'Aucune entrée dans le journal pour le moment',
  'No click data available': 'Aucune donnée sur les clics',
  'No comments yet': 'Aucun commentaire pour le moment',
  'No feedback yet': 'Aucun retour pour le moment',
  'No insights available yet': 'Aucune analyse disponible pour le moment',
  'No notifications': 'Aucune notification',
  'No performance data available': 'Aucune donnée sur les performances',
  'No team members found': 'Aucune personne trouvée',
  'No team members yet. Add team members to see analytics.':
    "Aucune personne dans l'équipe pour le moment. Ajoutez-en pour voir les analyses.",
  'None': 'Aucun',

  // notifiche
  'Mark all read': 'Tout marquer comme lu',
  'Mark as read': 'Marquer comme lu',
  'Muted': 'Silencieuses',
  'Notification Frequency': 'Fréquence des notifications',
  'Notification Retention (days)': 'Conservation des notifications (jours)',
  'Notification Settings': 'Paramètres des notifications',
  'Notification Sounds': 'Sons des notifications',
  'Notification Type': 'Type de notification',
  'Notification Types': 'Types de notification',
  'Notifications': 'Notifications',
  'Notifications will be paused between these times':
    'Les notifications seront suspendues pendant cette plage horaire',
  'Notify when attachments are excluded':
    "Avertir lorsqu'une pièce jointe est exclue",
  'Pause notifications during specific times':
    'Suspendre les notifications à certaines heures',
  'Play sounds when notifications arrive':
    "Émettre un son à l'arrivée d'une notification",
  'Quiet Hours': 'Heures silencieuses',
  'Quiet Hours Active': 'Heures silencieuses actives',
  'Real-time': 'En temps réel',
  'Receive notifications': 'Recevoir les notifications',
  'Receive notifications via email': 'Recevoir les notifications par e-mail',
  'Receive real-time alerts on your desktop for important task updates':
    'Recevez des alertes immédiates sur votre bureau pour les mises à jour importantes',
  'Send Test Notification': 'Envoyer une notification de test',

  // e-mail
  'Max Attachment Size (MB)': 'Taille maximale par pièce jointe (Mo)',
  'Maximum single attachment size': "Taille maximale d'une pièce jointe",
  'Maximum total attachment size per email':
    'Taille totale maximale des pièces jointes',
  'Most email providers have attachment size limits. SendGrid and Resend both support up to 25MB total.':
    "Presque tous les fournisseurs limitent la taille des pièces jointes : SendGrid et Resend acceptent jusqu'à 25 Mo au total.",
  'Most popular links in your emails': 'Liens les plus cliqués dans vos e-mails',
  'Office Documents': 'Documents Office',
  'PDF Documents': 'Documents PDF',
  'Open Rate': "Taux d'ouverture",
  'Opened': 'Ouvertes',
  'Open and click rates for different email types':
    "Ouvertures et clics par type d'e-mail",
  'Percentage of opened emails that received clicks':
    'Pourcentage des e-mails ouverts ayant reçu un clic',
  'Performance by Email Type': "Performances par type d'e-mail",
  'Plain Text': 'Texte brut',
  'Preview': 'Aperçu',
  'Recent Deliveries': 'Remises récentes',
  'Recipient': 'Destinataire',
  'Resend': 'Resend',
  'SendGrid': 'SendGrid',
  'Sent': 'Envoyées',
  'Set maximum file sizes for email attachments':
    'Définissez la taille maximale des pièces jointes',
  'Save Template': 'Enregistrer le modèle',

  // sistema
  'MM/DD/YYYY': 'MM/JJ/AAAA',
  'Maintenance Mode': 'Mode maintenance',
  'Max AI Requests Per Day': 'Requêtes IA maximales par jour',
  'Max Login Attempts': 'Tentatives de connexion maximales',
  'Monday': 'Lundi',
  'Mountain Time': 'Fuseau horaire des Rocheuses',
  'Pacific Time': 'Fuseau horaire du Pacifique',
  'London': 'Londres',
  'Paris': 'Paris',
  'Password Expiry (days)': 'Expiration du mot de passe (jours)',
  'Permanently delete all audit log entries. This action cannot be undone.':
    'Supprime définitivement toutes les entrées du journal. Cette action est irréversible.',
  'Permanently delete all tasks, employees, and settings':
    'Supprime définitivement les tâches, les personnes et les paramètres',
  'Require 2FA for all users':
    "Exiger l'authentification à deux facteurs pour tous",
  'Require Email Verification': "Exiger la vérification de l'e-mail",
  'Require Strong Passwords': 'Exiger des mots de passe robustes',
  'Reset': 'Réinitialiser',
  'Reset to Default': 'Rétablir la valeur par défaut',
  'Reset to Defaults': 'Rétablir les valeurs par défaut',
  'Restore': 'Restaurer',
  'Restore from a previous backup file':
    "Restaurez à partir d'un fichier de sauvegarde",
  'Restore system data from a previously exported backup file.':
    "Restaurez les données à partir d'une sauvegarde exportée précédemment.",
  'Save Changes': 'Enregistrer les modifications',
  'Save Settings': 'Enregistrer les paramètres',
  'Security': 'Sécurité',
  'Security Settings': 'Paramètres de sécurité',
  'Security Status': 'État de la sécurité',
  'Security policies and audit configuration':
    'Règles de sécurité et configuration du journal',
  'Session Timeout (minutes)': 'Expiration de la session (minutes)',
  'Set expiration date': "Définir une date d'expiration",
  'Please set an expiry date': "Définissez une date d'expiration",
  'Overview': 'Vue générale',
  'Overall Summary': 'Résumé général',
  'Quick Actions': 'Actions rapides',
  'Quick Info': 'Informations rapides',
  'Quick Presets': 'Préréglages',
  'Recent Activity': 'Activité récente',
  'Recent Audit Log': 'Journal récent',
  'Refresh': 'Actualiser',
  'Previous': 'Précédent',
  'Rate': 'Évaluer',
  'Recommendations': 'Recommandations',
  'Review': 'Examiner',
  'Reviewing': "En cours d'examen",
  'Review and manage feedback from your team members':
    "Lisez et gérez les retours de l'équipe",
  'Performance': 'Performances',
  'Performance Patterns': 'Évolution des performances',
  'Message': 'Message',
  'Most Popular': 'Les plus populaires',
  'Most Recent': 'Les plus récents',
  'Other': 'Autre',
  'Pinned': 'Épinglé',
  'Planned': 'Planifié',
  'Praise': 'Félicitations',
  'Praise & Thanks': 'Félicitations et remerciements',
  'Post Announcement': "Publier l'annonce",
  'New 30d': 'Nouveaux sur 30 jours',
  'Questions or need help? Check the Help Documentation or contact your administrator.':
    "Des questions ou besoin d'aide ? Consultez la documentation ou contactez un administrateur.",

  // validazioni
  'Please enter a message': 'Saisissez un message',
  'Please enter a title': 'Saisissez un titre',
  'Please enter a valid email address': 'Saisissez une adresse e-mail valide',
  'Please provide a description': 'Ajoutez une description',
  'Please provide a title': 'Ajoutez un titre',
  'Please provide as much detail as possible...':
    'Décrivez le plus précisément possible...',
  'PDF report will open in print dialog':
    "Le rapport PDF s'ouvrira dans la fenêtre d'impression",

  // testi gia in italiano
  'Rimossa dalla configurazione una chiave API salvata dalla versione precedente: le chiavi vivono solo lato server.':
    'Une clé API enregistrée par la version précédente a été retirée de la configuration : les clés ne vivent que côté serveur.',
  'Se stai leggendo questo messaggio, la configurazione di invio lato server funziona.':
    "Si vous lisez ce message, la configuration d'envoi côté serveur fonctionne.",
  'Sessione scaduta, accedi di nuovo': 'Session expirée, reconnectez-vous',
  'Serve il ruolo': 'Rôle requis',
  'Invio di prova': 'Envoi de test',
  'Indica un indirizzo a cui inviare la prova':
    'Indiquez une adresse à laquelle envoyer le test',
  'Le funzioni AI non sono attive': 'Les fonctions IA ne sont pas actives',

  // impostazioni
  'Settings Version': 'Version des paramètres',
  'Settings reset to defaults': 'Paramètres rétablis aux valeurs par défaut',
  'Settings saved successfully!': 'Paramètres enregistrés',
  'Size Limits': 'Limites de taille',
  'Slack Webhook URL': 'URL du webhook Slack',
  'Webhook URL': 'URL du webhook',
  'Smart Suggestions': 'Suggestions intelligentes',
  'Sort by': 'Trier par',
  'Spanish': 'Espagnol',
  'Standard Departments': 'Services standard',
  'Start Time': 'Heure de début',
  'Storage Information': 'Espace occupé',
  'Sunday': 'Dimanche',
  'System Notifications': 'Notifications système',
  'System Overview': "Vue d'ensemble du système",
  'System Settings': 'Paramètres du système',
  'System is currently in maintenance mode': 'Le système est en mode maintenance',
  'System-wide notification configuration': 'Configuration générale des notifications',
  'Timezone': 'Fuseau horaire',
  'Tokyo': 'Tokyo',
  'Week Start Day': 'Premier jour de la semaine',
  'YYYY-MM-DD': 'AAAA-MM-JJ',
  'Templates': 'Modèles',
  'Template reset to default. Click Save to apply changes.':
    'Modèle rétabli à sa valeur par défaut. Cliquez sur Enregistrer pour appliquer.',
  'Use Template': 'Utiliser le modèle',
  'Type': 'Type',
  'Title': 'Titre',
  'Subject': 'Objet',
  'Subject Line': 'Objet',
  'Text Files': 'Fichiers texte',
  'Total': 'Total',
  'Unsaved Changes': 'Modifications non enregistrées',
  'Track all system changes and actions':
    'Suivez toutes les modifications et actions',
  'Track and manage department budgets': 'Suivez et gérez les budgets des services',
  'Trends': 'Tendances',
  'Try Again': 'Réessayer',
  'Volume': 'Volume',
  'Test Sounds': 'Tester les sons',
  'Test notification sent!': 'Notification de test envoyée',
  'Tests Passed': 'Tests réussis',

  // team e analisi
  'Team': 'Équipe',
  'Team Analytics': "Analyses de l'équipe",
  'Team Analytics Report': "Rapport d'analyse de l'équipe",
  'Team Feedback Board': 'Tableau des retours',
  'Team Lead': "Responsable de l'équipe",
  'Team Leads': "Responsables d'équipe",
  'Team Member Details': 'Détails de la personne',
  'Team Members': "Membres de l'équipe",
  'Team Performance': "Performances de l'équipe",
  'Team Performance Overview': "Vue d'ensemble des performances de l'équipe",
  'Team member updated successfully!': 'Personne mise à jour',
  'Team members will be notified of new comments on their assigned tasks.':
    'Les personnes sont averties des nouveaux commentaires sur les tâches qui leur sont assignées.',
  'Team members with overdue or high-priority tasks':
    'Personnes ayant des tâches en retard ou à priorité haute',
  'Team size distribution': 'Répartition de la taille des équipes',
  'Top Performer': 'Meilleur résultat',
  'Top Performers': 'Meilleurs résultats',
  'Top Performing': 'Les meilleurs résultats',
  'Total Departments': 'Services au total',
  'Total Employees': 'Personnes au total',
  'Total Feedback': 'Retours au total',
  'Total Members': 'Membres au total',
  'Total Team Members': "Membres de l'équipe au total",
  'Total Sent': 'Envoyées au total',
  'Total tasks per department': 'Tâches totales par service',
  'With Leads': 'Avec responsable',
  'Workload Alerts': 'Alertes de charge de travail',
  'Workload Analysis': 'Analyse de la charge de travail',
  'Workload Distribution': 'Répartition de la charge de travail',
  'Workload by Department': 'Charge de travail par service',
  'Target Departments': 'Services concernés',
  'Task Distribution by Department': 'Répartition des tâches par service',
  'Task breakdown by team member': 'Répartition des tâches par personne',
  'Tasks by priority level': 'Tâches par niveau de priorité',
  'Tasks completed over the last 7 days':
    'Tâches terminées au cours des 7 derniers jours',
  'Tasks due within 24 hours (priority)':
    'Tâches à échéance sous 24 heures (priorité)',
  'Task Completion Trend': 'Évolution des tâches terminées',
  'Task Status Distribution': 'Répartition des statuts',
  'Super Admin Dashboard': 'Tableau de bord du super administrateur',
  'Upcoming Deadlines': 'Prochaines échéances',
  'Unassigned': 'Non assignée',
  'Unassigned Tasks': 'Tâches non assignées',

  // attività, notifiche ed eventi
  'Task Creation': 'Création de tâches',
  'Task Management': 'Gestion des tâches',
  'Task Priority Updated': 'Priorité de la tâche mise à jour',
  'Task Questions': 'Questions sur les tâches',
  'Task Reassigned to You': 'Tâche réassignée à vous',
  'Task Status Updated': 'Statut de la tâche mis à jour',
  'Task Updated': 'Tâche mise à jour',
  'Task assignments and updates': 'Attributions et mises à jour des tâches',
  'Status changes': 'Changements de statut',
  'This is a reminder that your task is due soon.':
    'Rappel : votre tâche arrive à échéance.',
  'Your task is now overdue and requires immediate attention.':
    'Votre tâche est en retard et exige une attention immédiate.',
  'This action cannot be undone. This will permanently delete the task from your workspace.':
    'Cette action est irréversible : la tâche sera définitivement supprimée de votre espace de travail.',
  'Update the task details below.':
    'Mettez à jour les détails de la tâche ci-dessous.',
  'Upload Attachment': 'Ajouter une pièce jointe',
  'Urgent': 'Urgent',
  'You Were Mentioned': 'Vous avez été mentionné',
  'View Task Now': 'Ouvrir maintenant',
  'View Comment': 'Voir le commentaire',
  'View My Tasks': 'Mes tâches',
  'View All Tasks': 'Toutes les tâches',
  'View All': 'Tout voir',
  'View Overdue': 'Voir les tâches en retard',
  'View': 'Voir',
  'View details & comments': 'Détails et commentaires',
  'When you have unassigned tasks, click':
    'Lorsque vous avez des tâches non assignées, cliquez sur',

  // utenti e permessi
  'User Management': 'Gestion des utilisateurs',
  'User Role': 'Rôle utilisateur',
  'User account policies and defaults':
    'Règles et valeurs par défaut des comptes',
  'User data exported successfully!': 'Données des utilisateurs exportées',
  'User not loaded': 'Utilisateur non chargé',
  'Users': 'Utilisateurs',
  'Users can belong to multiple departments':
    'Les personnes peuvent appartenir à plusieurs services',
  'Users must be assigned to at least one department':
    'Chaque personne doit appartenir à au moins un service',
  'Viewer': 'Lecture seule',
  'View all analytics and reports': 'Voit toutes les analyses et tous les rapports',
  'View and update their own tasks': 'Voit et met à jour ses propres tâches',
  'View department analytics': 'Voit les analyses du service',
  'View your current role and permissions':
    'Consultez votre rôle et vos autorisations',
  'Your Access Level': "Votre niveau d'accès",
  'You do not have permission to manage roles':
    "Vous n'avez pas l'autorisation de gérer les rôles",
  'You do not have permission to manage user roles. Only administrators can modify roles and permissions.':
    "Vous n'avez pas l'autorisation de gérer les rôles : seuls les administrateurs peuvent les modifier.",
  'Update department information and settings':
    'Mettez à jour les informations et les paramètres du service',
  'Update team member information':
    'Mettez à jour les informations de la personne',
  'Update Announcement': "Mettre à jour l'annonce",
  'Use AI features': 'Utiliser les fonctions IA',

  // riscontri
  'Share Feedback Now': 'Donner un retour',
  'Share Your Feedback': 'Dites-nous ce que vous en pensez',
  'Submit Feedback': 'Envoyer le retour',
  'Suggested Deadline': 'Échéance suggérée',
  'Suggestion applied!': 'Suggestion appliquée',
  'Thank you for your feedback! 🎉': 'Merci pour votre retour',
  'Thank You for Being Part of Our Launch':
    "Merci d'être avec nous pour le lancement",
  'We Need Your Feedback!': 'Votre avis nous est utile',
  'Welcome to your new team productivity platform':
    "Bienvenue sur votre nouvelle plateforme de travail d'équipe",
  'You must be logged in to submit feedback':
    'Vous devez être connecté pour envoyer un retour',
  'You must be logged in to upvote': 'Vous devez être connecté pour voter',
  'There are no active announcements for your departments':
    "Il n'y a aucune annonce active pour vos services",
  'Skip Tour': 'Passer la présentation',
  'Your Achievements': 'Vos résultats',

  // aiuto
  'What are AI Insights?': 'Que sont les analyses IA ?',
  'What are the different user roles?': 'Quels sont les rôles utilisateur ?',
  'What can the AI Assistant do?': "Que peut faire l'assistant IA ?",
  'Yes! In the analytics view, click the': 'Oui. Dans la vue analyses, cliquez sur',
  'Yes! Open the task details dialog and go to the':
    'Oui. Ouvrez les détails de la tâche et allez dans',
  'When enabled, task attachments will be included in notification emails':
    'Si activé, les pièces jointes des tâches sont incluses dans les e-mails de notification',
  'Total size of all attachments in a single email cannot exceed this limit':
    "La taille totale des pièces jointes d'un e-mail ne peut pas dépasser cette limite",
  'Show notifications outside the browser':
    'Afficher les notifications en dehors du navigateur',
  'Your browser does not support desktop notifications':
    'Votre navigateur ne prend pas en charge les notifications sur le bureau',
  'Your data is automatically saved in your browser. Use':
    'Les données sont enregistrées automatiquement. Utilisez',
  'Your data is automatically saved in your browser. Use backup to preserve data before major changes.':
    'Les données sont enregistrées automatiquement. Faites une sauvegarde avant toute modification importante.',
  'This will overwrite all existing data. Make sure to export current data first.':
    'Cette opération écrase toutes les données existantes : exportez-les au préalable.',

  // errori di runtime
  'This spark has encountered a runtime error':
    "L'application a rencontré une erreur",
  'Something unexpected happened while running the application. The error details are shown below. Contact the spark author and let them know about this issue.':
    "Une erreur inattendue s'est produite. Les détails sont ci-dessous : signalez-les au responsable de l'application.",

  // voci sfuggite alla sostituzione automatica
  'My Permissions': 'Mes autorisations',
  'Avg Completion Time': 'Temps moyen de réalisation',
  'Avg Tasks/Employee': 'Tâches moyennes par personne',
  'Count': 'Nombre',
  'Low': 'Basse',
  'Metric': 'Indicateur',
  'Total Assigned Tasks': 'Tâches assignées au total',
  'Value': 'Valeur',
  'Generated': 'Généré le',
  'days': 'jours',
  'Joined': 'Inscrit le',
  'All': 'Tous',
  'tasks': 'tâches',
  'task': 'tâche',
  'more': 'autres',
  'This user has': 'Cette personne a',
  'assigned task(s). Those tasks will become unassigned.':
    'tâche(s) assignée(s), qui resteront sans responsable.',
  'This action cannot be undone and any assigned tasks will become unassigned.':
    'Action irréversible : les tâches assignées resteront sans responsable.',
  'active': 'actif',
  'inactive': 'inactif',
  'Feedback Board': 'Tableau des retours',
  'Announcements': 'Annonces',
  'Skills (comma-separated)': 'Compétences (séparées par des virgules)',
  'Task created successfully!': 'Tâche créée',
  'Task updated successfully!': 'Tâche mise à jour',
  'Task reassigned successfully!': 'Tâche réassignée',
  'Task deleted': 'Tâche supprimée',
  'Task completed!': 'Tâche terminée',
  'Task status distribution across departments':
    'Répartition des statuts entre les services',
  'Top Clicked Links': 'Liens les plus cliqués',
  'Visual reference for department color coding and icons used throughout the app':
    "Référence visuelle des couleurs et des icônes des services utilisés dans l'application",
  'TaskFlow Help & Documentation': 'Aide et documentation',
  'TaskFlow is Production Ready!': 'TaskFlow est prêt pour la production',
  "Get your webhook URL from Slack's Incoming Webhooks app":
    "Trouvez l'URL du webhook dans l'application Incoming Webhooks de Slack",
  'TaskFlow Analytics - Team Performance Report':
    "TaskFlow - Rapport sur les performances de l'équipe",
  'TaskFlow Analytics - Department Performance Report':
    'TaskFlow - Rapport sur les performances par service',

  // testi la cui lingua di partenza e' l'italiano
  'Accesso revocato e membro rimosso': 'Accès révoqué et membre supprimé',
  'Apri TaskFlow per vedere i dettagli.': 'Ouvrez TaskFlow pour voir les détails.',
  'Assegna una nuova password provvisoria':
    'Définir un nouveau mot de passe provisoire',
  'Backup ripristinato. Ricarico la pagina...':
    'Sauvegarde restaurée. Rechargement de la page...',
  '{n}% complete': '{n}% terminé',
  '{n} tasks/user': '{n} tâches par utilisateur',
  '{n} announcements': '{n} annonces',
  '{n} unassigned': '{n} sans responsable',
  'Last modified: {data} by {autore}': 'Dernière modification : {data} par {autore}',
  'Variables': 'Variables',
  'Note:': 'Remarque :',
  'Email notifications are sent when enabled in user notification preferences. Variables will be automatically replaced with actual values when emails are sent.': 
    "Les e-mails de notification ne partent que s'ils sont activés dans les préférences de notification de l'utilisateur. Les variables sont remplacées par les valeurs réelles au moment de l'envoi.",
  'Mention a teammate': 'Mentionner un membre de l’équipe',
  'Use the arrow keys to choose, Enter to confirm, Esc to close': 'Flèches pour choisir, Entrée pour confirmer, Échap pour fermer',
  'Press Cmd+Enter to post. Type @ to mention a teammate': 'Cmd+Entrée pour publier. Tapez @ pour mentionner quelqu’un',
  'This attachment was blocked because its format is not allowed': 'Pièce jointe bloquée : ce format n’est pas autorisé',
  'Edit comment': 'Modifier le commentaire',
  'Delete comment': 'Supprimer le commentaire',
  'Post comment': 'Publier le commentaire',
  'Download attachment': 'Télécharger la pièce jointe',
  'Delete attachment': 'Supprimer la pièce jointe',
  'AI Service': 'Service IA',
  'Available': 'Disponible',
  'Unavailable': 'Indisponible',
  'Checking...': 'Vérification...',
  'Shown in the application header and used in notification emails.': 'Apparaît dans l’en-tête et dans les e-mails de notification.',
  'Notifications ({count} unread)': 'Notifications ({count} non lues)',
  'Delete notification': 'Supprimer la notification',
  'Edit task': 'Modifier la tâche',
  'Delete task': 'Supprimer la tâche',
  'Select task': 'Sélectionner la tâche',
  'Select {name}': 'Sélectionner {name}',
  'Skip tour': 'Passer la présentation',
  'tasks shown': 'tâches affichées',
  'Show more tasks': 'Afficher plus de tâches',
  'Calendar': 'Calendrier',
  'Previous month': 'Mois précédent',
  'Next month': 'Mois suivant',
  'Today': "Aujourd'hui",
  'Selected day': 'Jour sélectionné',
  'Priority: {priority}': 'Priorité : {priority}',
  'Tasks by due date for {month}': 'Tâches par échéance pour {month}',
  '+{count} more': '+{count} autres',
  '{count} tasks': '{count} tâches',
  '{count} overdue': '{count} en retard',
  '{count} scheduled this month': '{count} prévues ce mois-ci',
  '{count} tasks have no due date and are not shown here': "{count} tâches n'ont pas d'échéance et n'apparaissent pas ici",
  'Every task has a due date': 'Toutes les tâches ont une échéance',
  'Nothing due on this day': 'Rien à échéance ce jour-là',
  'Nothing is due this month': 'Rien à échéance ce mois-ci',
  'Repeat': 'Répéter',
  'Does not repeat': 'Ne se répète pas',
  'Daily': 'Tous les jours',
  'Weekly': 'Toutes les semaines',
  'Monthly': 'Tous les mois',
  'Repeat every': 'Répéter tous les',
  'weeks': 'semaines',
  'months': 'mois',
  'Repeat on': 'Répéter les',
  'Leave empty to repeat on the same weekday.': 'Laissez vide pour répéter le même jour de la semaine.',
  'End date (optional)': 'Date de fin (facultative)',
  'No end date': 'Pas de date de fin',
  'Remove end date': 'Retirer la date de fin',
  'Mon': 'Lun',
  'Tue': 'Mar',
  'Wed': 'Mer',
  'Thu': 'Jeu',
  'Fri': 'Ven',
  'Sat': 'Sam',
  'Sun': 'Dim',
  'Tuesday': 'Mardi',
  'Wednesday': 'Mercredi',
  'Thursday': 'Jeudi',
  'Friday': 'Vendredi',
  'Saturday': 'Samedi',
  'Daily summary instead of immediate emails': 'Résumé quotidien au lieu des e-mails immédiats',
  'One email a day with the notifications you have not read, instead of one email for every event': "Un e-mail par jour avec les notifications non lues, au lieu d'un e-mail par événement",
  'Summary time': 'Heure du résumé',
  'Times are in your timezone: {zone}': 'Les heures sont dans votre fuseau : {zone}',
  'If there is nothing new, no email is sent. In-app notifications stay immediate.': "S'il n'y a rien de nouveau, aucun e-mail n'est envoyé. Les notifications dans l'application restent immédiates.",
  'Daily summary enabled: one email per day instead of one per event': "Résumé quotidien activé : un e-mail par jour au lieu d'un par événement",
  'Immediate emails enabled: one email per event': 'E-mails immédiats activés : un e-mail par événement',
  'No due date': "Pas d'échéance",
  'Blocked': 'Bloquée',
  'Labels': 'Étiquettes',
  'Search or add a label': 'Rechercher ou ajouter une étiquette',
  'Create label "{name}"': 'Créer l’étiquette "{name}"',
  'Remove label {name}': 'Retirer l’étiquette {name}',
  'Label {name} added': 'Étiquette {name} ajoutée',
  'Label {name} removed': 'Étiquette {name} retirée',
  'Label suggestions': 'Suggestions d’étiquettes',
  'No matching label in use — type to create one': 'Aucune étiquette utilisée ne correspond — saisissez-la pour la créer',
  'Labels are saved in lowercase so the same one is never created twice.': 'Les étiquettes sont enregistrées en minuscules, pour ne jamais créer deux fois la même.',
  'Similar labels already exist. Reusing one keeps filters useful.': 'Des étiquettes similaires existent déjà. En réutiliser une garde les filtres utiles.',
  'Watchers': 'Observateurs',
  'Add someone who should follow this task': 'Ajoutez qui doit suivre cette tâche',
  'Nobody follows this task yet': 'Personne ne suit encore cette tâche',
  'People who can follow this task': 'Qui peut suivre cette tâche',
  'No one else to add': 'Personne d’autre à ajouter',
  'No people to show': 'Aucune personne à afficher',
  'Follow this task': 'Suivre cette tâche',
  'Following this task': 'Suit cette tâche',
  'Remove {name} from watchers': 'Retirer {name} des observateurs',
  '{name} now follows this task': '{name} suit désormais cette tâche',
  '{name} no longer follows this task': '{name} ne suit plus cette tâche',
  'You are assigned to this task, so you already get every update.': 'Cette tâche vous est assignée : vous recevez déjà chaque mise à jour.',
  '(you)': '(vous)',
  'Unknown user': 'Utilisateur inconnu',
  'Removed member': 'Membre retiré',
  'Estimated time': 'Temps estimé',
  'Time spent': 'Temps passé',
  'Estimated': 'Estimé',
  'No estimate': 'Pas d’estimation',
  'Understood as': 'Compris comme',
  'Not understood. Try 90, 1.5h or 2h 30m.': 'Non compris. Essayez 90, 1.5h ou 2h 30m.',
  'Leave empty if you cannot estimate it yet': 'Laissez vide si vous ne pouvez pas encore estimer',
  'Leave empty if not tracked': 'Laissez vide si non suivi',
  'Leave empty if unknown': 'Laissez vide si inconnu',
  'Same as the estimate': 'Comme l’estimation',
  '{tempo} over the estimate': '{tempo} de plus que l’estimation',
  '{tempo} under the estimate': '{tempo} de moins que l’estimation',
  'at least {tempo}': 'au moins {tempo}',
  'Export Tasks': 'Exporter les tâches',
  'Choose the format, the columns and which tasks to include.': 'Choisissez le format, les colonnes et les tâches à inclure.',
  'Format': 'Format',
  'Columns': 'Colonnes',
  'Which tasks': 'Quelles tâches',
  'Only the filtered tasks': 'Seulement les tâches filtrées',
  'All tasks, including archived ones': 'Toutes les tâches, y compris archivées',
  'Select at least one column': 'Sélectionnez au moins une colonne',
  '{righe} rows will be exported': '{righe} lignes seront exportées',
  'Export failed': 'Échec de l’export',
  'Allow pop-ups to export the PDF': 'Autorisez les pop-ups pour exporter le PDF',
  'Please allow pop-ups to download PDF': 'Autorisez les pop-ups pour télécharger le PDF',
  'Task List': 'Liste des tâches',
  'Person': 'Personne',
  'Open': 'Ouvertes',
  'Saved filters': 'Filtres enregistrés',
  'Save current filters': 'Enregistrer les filtres actuels',
  'Current filters are already saved': 'Les filtres actuels sont déjà enregistrés',
  'Name of this view': 'Nom de cette vue',
  'Rename this view': 'Renommer cette vue',
  'Rename "{nome}"': 'Renommer "{nome}"',
  'Delete "{nome}"': 'Supprimer "{nome}"',
  'Delete this saved filter?': 'Supprimer ce filtre enregistré ?',
  '"{nome}" will be removed. The tasks are not affected.': '"{nome}" sera supprimé. Les tâches ne sont pas affectées.',
  'Set some filters above, then save them here': 'Définissez des filtres ci-dessus, puis enregistrez-les ici',
  'Save the filters you use often — status, priority, department, assignee — and bring them back with one click.': 'Enregistrez les filtres que vous utilisez souvent — statut, priorité, service, assigné — et rappelez-les en un clic.',
  'Search: {testo}': 'Recherche : {testo}',
  'Clear All': 'Tout effacer',
  'Workload': 'Charge de travail',
  'Open tasks per person, and how much of that work has an estimate.': 'Tâches ouvertes par personne, et quelle part de ce travail est estimée.',
  'All {totale} open tasks have an estimate.': 'Les {totale} tâches ouvertes ont toutes une estimation.',
  '{senza} of {totale} open tasks have no estimate: that part of the workload is unknown.': '{senza} tâches ouvertes sur {totale} n’ont pas d’estimation : cette part de la charge est inconnue.',
  'Remove due date': 'Retirer l’échéance',
  'Please enter a task title': 'Saisissez le titre de la tâche',
  'Task Title': 'Titre',
  '"Create a task for the upcoming product launch"': '« Crée une tâche pour le lancement du produit »',
  '"How can I balance the workload across my team?"': '« Comment mieux répartir la charge de travail dans mon équipe ? »',
  '"Which tasks should I prioritize this week?"': '« Quelles tâches dois-je traiter en priorité cette semaine ? »',
  '1 day': '1 jour',
  '1 day ago': 'il y a 1 jour',
  '1. Click "{label}" in the header': "1. Cliquez sur « {label} » dans l'en-tête",
  '1. Click the "{label}" button in the header': "1. Cliquez sur le bouton « {label} » dans l'en-tête",
  '1. Navigate to the "{label}" tab': "1. Ouvrez l'onglet « {label} »",
  '100% Tests Passed': '100 % des tests réussis',
  '150+ Features Built': 'Plus de 150 fonctionnalités livrées',
  '2. Check the boxes next to tasks you want to modify': '2. Cochez les cases des tâches à modifier',
  '2. Click "{label}"': '2. Cliquez sur « {label} »',
  '2. Fill in the task details:': '2. Renseignez les informations de la tâche :',
  '2. Type your comment in the text field': '2. Saisissez votre commentaire dans le champ de texte',
  '3. Choose an action:': '3. Choisissez une action :',
  '3. Click "{label}"': '3. Cliquez sur « {label} »',
  '3. Click "{label}" to save': '3. Cliquez sur « {label} » pour enregistrer',
  '3. Enter their information:': '3. Saisissez ses informations :',
  '81 Iterations Completed': '81 itérations terminées',
  'AI': 'IA',
  'AI Insights appear in the Analytics view and provide:': 'Les analyses IA apparaissent dans la vue Analyses et fournissent :',
  'AI Integration Active': 'Intégration IA active',
  'AI assistant': 'Assistant IA',
  'AI insights': 'Analyses IA',
  'AI-Powered Features': "Fonctionnalités propulsées par l'IA",
  'Actionable Suggestions:': 'Suggestions concrètes :',
  'Actionable suggestions to improve workflow': 'Des suggestions concrètes pour améliorer le flux de travail',
  'Active: {active} • Done: {done}': 'En cours : {active} • Terminées : {done}',
  'Activity ({count})': 'Historique ({count})',
  'Add': 'Ajouter',
  'Add Comment': 'Ajouter un commentaire',
  'Add and organize team members': "Ajoutez et organisez les membres de l'équipe",
  'Add comments': 'Ajouter des commentaires',
  'Add employees': 'Ajouter des collaborateurs',
  'Add new employees': 'Ajouter de nouveaux collaborateurs',
  'Admin, Manager, or Member': 'Administrateur, responsable ou membre',
  'All ({count})': 'Toutes ({count})',
  'All analytics': 'Toutes les analyses',
  'All caught up! 🎉': 'Vous êtes à jour ! 🎉',
  'All departments on track! 🎉': 'Tous les départements sont dans les temps ! 🎉',
  'All existing departments will be replaced with {count} new ones': 'Les départements actuels seront remplacés par {count} nouveaux',
  'Are you sure you want to clear all audit log entries? This cannot be undone.': "Voulez-vous vraiment vider le journal d'audit ? Cette action est irréversible.",
  'Are you sure you want to delete this comment?': 'Voulez-vous vraiment supprimer ce commentaire ?',
  'Are you sure you want to remove {count} team members from your team?': "Voulez-vous vraiment retirer {count} personnes de l'équipe ?",
  'Are you sure you want to remove {name} from your team?': "Voulez-vous vraiment retirer {name} de l'équipe ?",
  'Are you sure you want to reset all settings to default values? This cannot be undone.': 'Voulez-vous vraiment rétablir tous les réglages par défaut ? Cette action est irréversible.',
  'Ask about specific tasks or team status': "Posez des questions sur une tâche précise ou sur l'état de l'équipe",
  'Assign departments to {count} users': 'Affecter des départements à {count} personnes',
  'Assign tasks': 'Attribuer des tâches',
  'Assign tasks to others': "Attribuer des tâches à d'autres personnes",
  'Assign to:': 'Attribuer à :',
  'Assigned to {name}': 'Attribuée à {name}',
  'Attach File': 'Joindre un fichier',
  'Attach files': 'Joindre des fichiers',
  'Attach files to tasks': 'Joindre des fichiers aux tâches',
  'Attachments': 'Pièces jointes',
  'Attachments ({count})': 'Pièces jointes ({count})',
  'Auto-assign': 'Attribution automatique',
  'Automated recommendations and trend analysis': 'Recommandations automatiques et analyse des tendances',
  'Bio': 'Biographie',
  'Brand identity and creative direction': 'Identité de marque et direction créative',
  'Brand strategy, campaigns, and growth marketing': 'Stratégie de marque, campagnes et marketing de croissance',
  'Brief description of the task': 'Description brève de la tâche',
  'Bright ascending chime': 'Carillon clair ascendant',
  'Budget: {amount}': 'Budget : {amount}',
  'Bulk Select': 'Sélection multiple',
  'Bulk operations': 'Opérations groupées',
  'Business': 'Gestion',
  'Business operations and process management': 'Opérations et gestion des processus',
  'Celebratory ascending chime': 'Carillon festif ascendant',
  'Change status': 'Changer le statut',
  'Change task status': 'Changer le statut des tâches',
  'Check browser console for errors': 'Vérifier les erreurs dans la console du navigateur',
  'Clear Audit Log ({count} entries)': 'Vider le journal ({count} entrées)',
  'Click "Add Task" to create new tasks. Assign them to team members, set priorities, due dates, and track status. Use bulk operations to manage multiple tasks at once.': "Cliquez sur « Ajouter une tâche » pour en créer. Attribuez-les aux membres de l'équipe, définissez priorités et échéances et suivez leur statut. Les opérations groupées permettent d'en gérer plusieurs à la fois.",
  'Click "Enable Notifications" to receive desktop alerts.': 'Cliquez sur « Activer les notifications » pour recevoir les alertes sur le bureau.',
  'Click "Publish" in Spark UI': "Cliquer sur « Publish » dans l'interface Spark",
  'Click "{label}" in the header to start chatting!': "Cliquez sur « {label} » dans l'en-tête pour commencer à discuter.",
  'Click "{label}" to upload documents, images, or other files (max 10MB per file).': "Cliquez sur « {label} » pour téléverser des documents, des images ou d'autres fichiers (10 Mo maximum par fichier).",
  'Click on any task card to open the details dialog, then:': 'Cliquez sur une carte pour ouvrir le détail de la tâche, puis :',
  'Click the "{label}" button in the header to view:': "Cliquez sur le bouton « {label} » dans l'en-tête pour consulter :",
  'Click the "{label}" button to:': 'Cliquez sur le bouton « {label} » pour :',
  'Click the edit icon (pencil) on any task card, make your changes, and click "{label}".': "Cliquez sur l'icône de modification (le crayon) d'une carte, apportez vos changements puis cliquez sur « {label} ».",
  'Client acquisition and revenue generation': 'Acquisition de clients et génération de revenus',
  'Client relationships and support services': "Relation client et services d'assistance",
  'Comment on tasks': 'Commenter les tâches',
  'Comments': 'Commentaires',
  'Comments ({count})': 'Commentaires ({count})',
  'Common departments:': 'Départements courants :',
  'Complete these final steps before going live:': 'Effectuez ces dernières étapes avant la mise en ligne :',
  'Completed: {done} • Rate: {rate}%': 'Terminées : {done} • Taux : {rate} %',
  'Completion rates, workload distribution, task trends': "Taux d'achèvement, répartition de la charge, tendances des tâches",
  'Confidence: {level}': 'Fiabilité : {level}',
  'Configure access level and permissions for {name}': "Définissez le niveau d'accès et les autorisations de {name}",
  'Configure your notification preferences by clicking the bell icon in the header. You can customize which events trigger notifications, set quiet hours, and choose notification sounds.': "Réglez vos préférences en cliquant sur la cloche dans l'en-tête. Vous pouvez choisir les événements qui déclenchent une notification, définir des heures calmes et choisir les sons.",
  'Contact email': 'Adresse e-mail de contact',
  'Content creation, writing, and editorial': 'Création de contenu, rédaction et édition',
  'Content of a comment': "Contenu d'un commentaire",
  'Create': 'Créer',
  'Create All ({count})': 'Tout créer ({count})',
  'Create and Assign Tasks': 'Créer et attribuer des tâches',
  'Create new tasks': 'Créer de nouvelles tâches',
  'Create, assign, and track tasks efficiently': 'Créez, attribuez et suivez les tâches sans perdre de temps',
  'Created {count} departments from the {category} template': '{count} départements créés à partir du modèle {category}',
  'Creative': 'Création',
  'Current date': 'Date du jour',
  'Current status of the task': 'Statut actuel de la tâche',
  'Current year': 'Année en cours',
  'Data analysis, machine learning, and analytics': 'Analyse de données, apprentissage automatique et statistiques',
  'Date when the action occurred': "Date à laquelle l'action a eu lieu",
  'Delete announcements': 'Supprimer des annonces',
  'Delete any task': "Supprimer n'importe quelle tâche",
  'Delete employees': 'Supprimer des collaborateurs',
  'Delete own tasks': 'Supprimer ses propres tâches',
  'Delete {count} users?': 'Supprimer {count} utilisateurs ?',
  'Department "{name}" already exists': 'Le département « {name} » existe déjà',
  'Department "{name}" archived': 'Département « {name} » archivé',
  'Department "{name}" created successfully!': 'Département « {name} » créé',
  'Department "{name}" deleted successfully': 'Département « {name} » supprimé',
  'Department "{name}" restored': 'Département « {name} » restauré',
  'Department "{name}" updated successfully!': 'Département « {name} » mis à jour',
  'Department Name *': 'Nom du département *',
  'Department-specific metrics and comparisons': 'Indicateurs et comparaisons par département',
  'Departments added to {users} users: {departments} in total': 'Départements ajoutés à {users} personnes : {departments} au total',
  'Departments available: {count}': 'Départements disponibles : {count}',
  'Departments replaced for {users} users: {departments} in total': 'Départements remplacés pour {users} personnes : {departments} au total',
  'Descending alert': 'Alerte descendante',
  'Describe a task naturally and AI will create it': "Décrivez une tâche avec vos mots et l'IA la crée",
  'Description of the task': 'Description de la tâche',
  'Desktop': 'Ordinateur',
  'Desktop notifications are blocked. Check your browser settings to enable them.': 'Les notifications sur le bureau sont bloquées. Vérifiez les réglages de votre navigateur pour les activer.',
  'Desktop notifications are enabled and working.': 'Les notifications sur le bureau sont actives et fonctionnent.',
  'Detailed information (optional)': 'Informations détaillées (facultatif)',
  'Due Soon': 'Bientôt à échéance',
  'Due date of the task': 'Échéance de la tâche',
  'Due {when}': 'Échéance {when}',
  'Early Bird (9 PM - 6 AM)': 'Lève-tôt (21 h - 6 h)',
  'Edit announcements': 'Modifier des annonces',
  'Edit any task': "Modifier n'importe quelle tâche",
  'Edit employee details': 'Modifier les informations des collaborateurs',
  'Edit employees': 'Modifier des collaborateurs',
  'Edit own tasks': 'Modifier ses propres tâches',
  'Efficiency': 'Efficacité',
  'Email Address *': 'Adresse e-mail *',
  'Email address of the recipient': 'Adresse e-mail du destinataire',
  'Employee Management': 'Gestion des collaborateurs',
  'Employees: {count}': 'Personnes : {count}',
  'Enable Quiet Hours': 'Activer les heures calmes',
  'Enable Sounds': 'Activer les sons',
  'Existing departments: {list}': 'Départements existants : {list}',
  'Expires {date}': 'Expire le {date}',
  'Export data backup': 'Exporter une sauvegarde des données',
  'Failed to generate assignments': 'Impossible de générer les attributions',
  'Failed to get AI response': "Impossible d'obtenir une réponse de l'IA",
  'Financial planning, accounting, and reporting': 'Planification financière, comptabilité et reporting',
  'Flag urgent overdue tasks': 'Signale les tâches en retard les plus urgentes',
  'Formatted report with charts': 'Rapport mis en page avec les graphiques',
  "From concept to production in 81 iterations. That's persistence!": "De l'idée à la production en 81 itérations : voilà de la persévérance !",
  'Full Name *': 'Nom et prénom *',
  'Full name': 'Nom et prénom',
  'Gentle ascending tone': 'Ton ascendant léger',
  'Get AI insights': 'Obtenir les analyses IA',
  'Get AI task estimates': 'Obtenir les estimations IA des tâches',
  'Get Started': "C'est parti",
  'Get recommendations for task reassignment or priority changes': 'Recevez des conseils pour réattribuer des tâches ou changer leur priorité',
  'High double ping': 'Double bip aigu',
  'High, Medium, or Low': 'Haute, moyenne ou basse',
  'I apologize, but I encountered an error processing your request: {message}': "Désolé, une erreur s'est produite lors du traitement de votre demande : {message}",
  'Identify overloaded team members': "Repère les personnes surchargées dans l'équipe",
  'Identify overworked team members': 'Repère les personnes surchargées de travail',
  'Importing...': 'Importation en cours...',
  'Information security and cybersecurity operations': "Sécurité de l'information et cybersécurité",
  'Infrastructure, deployment, and system operations': 'Infrastructure, déploiement et exploitation des systèmes',
  'Job Title *': 'Intitulé du poste *',
  'Job title or position': 'Intitulé du poste ou fonction',
  'John Doe': 'Jean Dupont',
  'Joined Date': "Date d'arrivée",
  'LAUNCH_CELEBRATION.md - Celebration & stats': 'LAUNCH_CELEBRATION.md - Célébration et chiffres',
  'LAUNCH_READINESS_REPORT.md - Full audit': 'LAUNCH_READINESS_REPORT.md - Audit complet',
  'Lead: {name}': 'Responsable : {name}',
  'Legal compliance and contract management': 'Conformité juridique et gestion des contrats',
  "Let's Launch! 🚀": "C'est parti ! 🚀",
  'Link to view the task': 'Lien pour ouvrir la tâche',
  'Manage Your Team': 'Gérez votre équipe',
  'Manage roles': 'Gérer les rôles',
  'Manage user roles and permissions': 'Gérer les rôles et les autorisations des utilisateurs',
  'Managing: {departments}': 'Départements que vous gérez : {departments}',
  'Mark all as completed': 'Marquer toutes comme terminées',
  'Mentions': 'Mentions',
  'Mobile': 'Téléphone',
  'Monitor team analytics': "Suivez les analyses de l'équipe",
  'N/A': 'N. d.',
  'Name of the application': "Nom de l'application",
  'Name of the company': "Nom de l'entreprise",
  'Name of the email recipient': "Nom du destinataire de l'e-mail",
  'Name of the person assigned': 'Nom de la personne assignée',
  'Name of the person who performed the action': "Nom de la personne qui a effectué l'action",
  'New': 'Nouveau',
  'New comment added': 'Nouveau commentaire ajouté',
  'Night Owl (12 AM - 10 AM)': 'Couche-tard (0 h - 10 h)',
  'No': 'Non',
  'No data': 'Aucune donnée',
  'Notification Preferences': 'Préférences de notification',
  'Out of {count} total': 'Sur {count} au total',
  'PRODUCTION_DEPLOYMENT.md - Deployment guide': 'PRODUCTION_DEPLOYMENT.md - Guide de déploiement',
  'Perform bulk operations': 'Effectuer des opérations groupées',
  'Personal analytics': 'Analyses personnelles',
  'Phone': 'Téléphone',
  'Playing {sound}': 'Lecture : {sound}',
  'Preview: This color will be auto-assigned based on the department name': "Aperçu : cette couleur est attribuée automatiquement d'après le nom du département",
  'Priority Changed': 'Priorité modifiée',
  'Priority changed to {priority}': 'Priorité passée à {priority}',
  'Priority level of the task': 'Niveau de priorité de la tâche',
  'Product strategy and user experience design': "Stratégie produit et conception de l'expérience utilisateur",
  'Production Ready': 'Prêt pour la production',
  'Quality assurance and software testing': 'Assurance qualité et tests logiciels',
  'Quick double chirp': 'Double trille rapide',
  'Quick select existing departments:': 'Sélection rapide parmi les départements existants :',
  'Quiet hours disabled': 'Heures calmes désactivées',
  'Quiet hours enabled - notifications paused during sleep times': 'Heures calmes activées : les notifications sont suspendues pendant le repos',
  'Quiet hours set: {preset}': 'Heures calmes définies : {preset}',
  'Raw data for further analysis': 'Données brutes pour des analyses ultérieures',
  'Remove all selected tasks': 'Supprimer toutes les tâches sélectionnées',
  'Remove employees': 'Retirer des collaborateurs',
  'Reset all to not-started': 'Remettre toutes à « À commencer »',
  'Rising alert tone': 'Alerte ascendante',
  'Run final smoke test (30 minutes)': 'Effectuer le dernier test de fumée (30 minutes)',
  'Saving…': 'Enregistrement…',
  'Security Hardened': 'Sécurité renforcée',
  'Select at least one department to continue': 'Sélectionnez au moins un département pour continuer',
  "Selected departments will be added to each user's current departments": "Les départements choisis s'ajoutent à ceux que chaque personne a déjà",
  'Selected departments will replace all current departments for each user': 'Les départements choisis remplacent tous ceux de chaque personne',
  'Selected users: {count}': 'Personnes sélectionnées : {count}',
  'Set all to in-progress': 'Passer toutes à « En cours »',
  'Share URL with your team': "Partager l'adresse avec votre équipe",
  'Single soft ping': 'Bip unique atténué',
  'Skills': 'Compétences',
  'Sleep Time (10 PM - 7 AM)': 'Repos (22 h - 7 h)',
  'Smart suggestions and automated workflows': 'Suggestions intelligentes et flux de travail automatisés',
  'Smart task management': 'Gestion intelligente des tâches',
  'Social media management and community engagement': 'Gestion des réseaux sociaux et animation de la communauté',
  'Software development and technical implementation': 'Développement logiciel et réalisation technique',
  'Spot trends in completion rates': "Repère les tendances des taux d'achèvement",
  'Start by adding your team members. Click the "Users" button in the header to add employees, assign departments, and set roles (Admin, Manager, or Member).': "Commencez par ajouter les membres de l'équipe. Cliquez sur « Utilisateurs » dans l'en-tête pour les ajouter, leur affecter des départements et choisir leur rôle (administrateur, responsable ou membre).",
  'Status Changed': 'Statut modifié',
  'Status changed to {status}': 'Statut passé à {status}',
  'Switch to the Analytics view to see team performance metrics, workload distribution, and department insights. Export reports as PDF or CSV.': "Passez à la vue Analyses pour consulter les performances de l'équipe, la répartition de la charge et les données par département. Les rapports s'exportent en PDF ou en CSV.",
  'Tablet': 'Tablette',
  'Talent management and employee relations': 'Gestion des talents et relations avec le personnel',
  'Task Assigned': 'Tâche attribuée',
  'Task Completed': 'Tâche terminée',
  'Task Reassigned': 'Tâche réattribuée',
  'Task created': 'Tâche créée',
  'Task estimates': 'Estimations des tâches',
  'Task updated': 'Tâche mise à jour',
  'Tasks assigned: {count}': 'Tâches attribuées : {count}',
  'Tasks: {count}': 'Tâches : {count}',
  'Tasks: {done}/{total}': 'Tâches : {done}/{total}',
  'Team Collaboration': 'Collaboration en équipe',
  'Team analytics': "Analyses de l'équipe",
  'Team member responsible': "Personne de l'équipe qui s'en charge",
  'Team members: {count}': "Membres de l'équipe : {count}",
  'Team members: {members} · Tasks: {tasks}': "Membres de l'équipe : {members} · Tâches : {tasks}",
  'Technical support and system maintenance': 'Assistance technique et maintenance des systèmes',
  'Technology': 'Technologie',
  'Template applied! Review and create "{name}"': 'Modèle appliqué : vérifiez les informations et créez « {name} »',
  'Test on mobile device': 'Tester sur un appareil mobile',
  'The AI Assistant helps you with:': "L'assistant IA vous aide à :",
  'The departments in the {category} template already exist': 'Les départements du modèle {category} existent déjà',
  'This department cannot be archived: it still has {count} assigned people': "Impossible d'archiver ce département : {count} personnes y sont encore affectées",
  'This department cannot be deleted: it still has {count} assigned people': 'Impossible de supprimer ce département : {count} personnes y sont encore affectées',
  'This is a test notification from TaskFlow!': 'Ceci est une notification de test de TaskFlow.',
  'This user has {count} assigned tasks. Those tasks will become unassigned.': 'Cette personne a {count} tâches attribuées, qui se retrouveront sans responsable.',
  'This will permanently delete "{name}". This action cannot be undone.': '« {name} » sera supprimé définitivement. Cette action est irréversible.',
  'Three warning tones': "Trois tonalités d'alerte",
  'Tips for great feedback:': 'Conseils pour un retour utile :',
  'Title of the task': 'Titre de la tâche',
  'Total clicks: {count}': 'Clics au total : {count}',
  'Total tasks: {count}': 'Tâches au total : {count}',
  'Track Performance': 'Suivez les performances',
  'Try asking:': 'Essayez de demander :',
  'Two-tone notification': 'Notification à deux tons',
  'Type of action performed': "Type d'action effectuée",
  'UI/UX design and visual design work': "Conception d'interfaces, expérience utilisateur et graphisme",
  'Unique: {count}': 'Uniques : {count}',
  'Unknown': 'Inconnu',
  'Unread ({count})': 'Non lues ({count})',
  'Updated {time}': 'Mis à jour à {time}',
  'Use AI Assistant for intelligent task suggestions, auto-assignment based on workload, and insights about team performance and bottlenecks.': "Utilisez l'assistant IA pour obtenir des propositions de tâches, une attribution automatique selon la charge et des analyses sur les performances et les blocages de l'équipe.",
  'Use AI assistant': "Utiliser l'assistant IA",
  'Use AI auto-assign': "Utiliser l'attribution automatique IA",
  'Users affected: {count}': 'Personnes concernées : {count}',
  'Users removed: {count}': 'Personnes retirées : {count}',
  'Verify all critical paths working': 'Vérifier que les parcours critiques fonctionnent',
  'Video creation, editing, and multimedia': 'Réalisation vidéo, montage et multimédia',
  'View all tasks': 'Voir toutes les tâches',
  'View announcements': 'Voir les annonces',
  'View employee list': 'Voir la liste des collaborateurs',
  'View employees': 'Voir les collaborateurs',
  'View organization analytics': "Voir les analyses de l'organisation",
  'View own tasks': 'Voir ses propres tâches',
  'View personal analytics': 'Voir les analyses personnelles',
  'View team analytics': "Voir les analyses de l'équipe",
  'View team tasks': "Voir les tâches de l'équipe",
  'Visualize team performance and insights': "Visualisez les performances de l'équipe et ce que disent les données",
  'Warning:': 'Attention :',
  'Warning: this department has {count} assigned people.': 'Attention : {count} personnes sont affectées à ce département.',
  "We'll notify you when something important happens": "Nous vous préviendrons dès qu'il se passe quelque chose d'important",
  "We've built TaskFlow to help teams work smarter, collaborate better, and achieve more together. Your feedback during this launch phase is invaluable and will help us shape the future of this platform.": 'Nous avons conçu TaskFlow pour aider les équipes à mieux travailler, mieux collaborer et accomplir davantage ensemble. Pendant cette phase de lancement, votre avis compte énormément et nous aide à faire évoluer la plateforme.',
  'Welcome back, {name}!': 'Bon retour, {name} !',
  'Welcome to TaskFlow! 🎉': 'Bienvenue dans TaskFlow ! 🎉',
  'When a task becomes overdue': 'Quand une tâche est en retard',
  'When a task is assigned to you': 'Quand une tâche vous est attribuée',
  'When a task is due within 24 hours': 'Quand une tâche arrive à échéance dans les 24 heures',
  'When a task is marked as complete': 'Quand une tâche est marquée comme terminée',
  'When a task is reassigned to you': 'Quand une tâche vous est réattribuée',
  'When someone comments on your task': "Quand quelqu'un commente une de vos tâches",
  'When task details are modified': "Quand les informations d'une tâche changent",
  'When task priority is modified': "Quand la priorité d'une tâche change",
  'When task status is updated': "Quand le statut d'une tâche change",
  'When the task should be completed': 'Date à laquelle la tâche doit être terminée',
  'When you are mentioned in comments': 'Quand vous êtes mentionné dans un commentaire',
  'When you have unassigned tasks, click "{label}" to:': 'Quand des tâches ne sont attribuées à personne, cliquez sur « {label} » pour :',
  'Which teams they belong to': 'Les équipes auxquelles la personne appartient',
  'Work together with departments and roles': 'Travaillez ensemble, par départements et par rôles',
  'Working Hours (6 PM - 9 AM)': 'Hors heures de bureau (18 h - 9 h)',
  'Yes': 'Oui',
  'Yes! In the analytics view, click the "{label}" button to download reports as:': 'Oui. Dans la vue des analyses, cliquez sur le bouton « {label} » pour télécharger les rapports au format :',
  'Yes! Open the task details dialog and go to the "{label}" tab.': "Oui. Ouvrez le détail de la tâche et allez dans l'onglet « {label} ».",
  'You Did It! 🎊': "Vous l'avez fait ! 🎊",
  'You will now receive desktop notifications for important updates!': 'Vous recevrez désormais une notification sur le bureau pour les mises à jour importantes.',
  "You'll receive desktop notifications for:": 'Vous recevrez une notification sur le bureau pour :',
  "You're all caught up!": 'Vous êtes à jour.',
  'Your complete employee task management solution': "Votre solution complète pour gérer le travail de l'équipe",
  'Your data is automatically saved in your browser. Use "{label}" to export your data before making major changes. You can also import data from previous backups.': 'Les données sont enregistrées automatiquement dans le navigateur. Utilisez « {label} » pour les exporter avant des changements importants ; vous pouvez aussi réimporter une sauvegarde précédente.',
  'Your experience matters! Please take a moment to share your thoughts, report any issues, or suggest improvements. Every piece of feedback helps us make TaskFlow better for everyone.': 'Votre expérience compte. Prenez un instant pour nous dire ce que vous en pensez, signaler un problème ou proposer une amélioration : chaque retour nous aide à améliorer TaskFlow pour tout le monde.',
  'added a comment': 'a ajouté un commentaire',
  'assigned to {name}': "l'a attribuée à {name}",
  'attached {file}': 'a joint {file}',
  'by {name}': 'par {name}',
  'changed due date from {old} to {new}': "a déplacé l'échéance de {old} à {new}",
  'changed priority from {old} to {new}': 'a changé la priorité de {old} à {new}',
  'changed status from {old} to {new}': 'a changé le statut de {old} à {new}',
  'completion': 'achèvement',
  'created this task': 'a créé cette tâche',
  'in 1 day': 'dans 1 jour',
  'in 1 hour': 'dans 1 heure',
  'in {count} days': 'dans {count} jours',
  'in {count} hours': 'dans {count} heures',
  'made a change': 'a effectué une modification',
  'reassigned from {old} to {new}': "l'a réattribuée de {old} à {new}",
  'removed attachment {file}': 'a retiré la pièce jointe {file}',
  'tasks/person': 'tâches par personne',
  'today': "aujourd'hui",
  'updated the description': 'a mis à jour la description',
  'updated the title': 'a mis à jour le titre',
  'yesterday': 'hier',
  '{count} In Progress': '{count} en cours',
  '{count} Overdue': '{count} en retard',
  '{count} active': '{count} en poste',
  '{count} already created': '{count} déjà créés',
  '{count} bounced': '{count} rejetés',
  '{count} clicked': '{count} cliqués',
  '{count} days': '{count} jours',
  '{count} days ago': 'il y a {count} jours',
  '{count} days from now': 'dans {count} jours',
  '{count} departments will be added to the existing ones': "{count} départements s'ajouteront à ceux déjà en place",
  '{count} high priority': '{count} en priorité haute',
  '{count} not started': '{count} à commencer',
  '{count} opened': '{count} ouverts',
  '{count} sent': '{count} envoyés',
  '{count} tasks/person': '{count} tâches par personne',
  '{count} unassigned': '{count} sans responsable',
  '{count} users set to {status}': '{count} personnes passées au statut {status}',
  '{count}% completion': "{count} % d'achèvement",
  '{name} department': 'Département {name}',
  '~{hours}h per day': 'environ {hours} h par jour',
  '• Be specific about what you experienced': '• Décrivez précisément ce que vous avez rencontré',
  '• Describe the impact on your workflow': "• Expliquez l'effet sur votre travail",
  '• Include steps to reproduce (for bugs)': "• S'il s'agit d'un bug, indiquez comment le reproduire",
  '• Suggest potential solutions if you have ideas': '• Si vous avez une idée de solution, proposez-la',
  '🎉 Desktop Notifications Enabled': '🎉 Notifications sur le bureau activées',
  '🎉 TaskFlow is Now Live! 🎉': '🎉 TaskFlow est en ligne ! 🎉',
  '🎉 Time to Celebrate!': "🎉 C'est le moment de fêter ça !",
  '📊 By The Numbers:': '📊 En chiffres :',
  '📋 Launch Checklist': '📋 Liste de contrôle avant lancement',
  '📚 Documentation Ready:': '📚 Documentation prête :',
  '🔔 Test Notification': '🔔 Notification de test',
  '🔴 Needs Attention': '🔴 À surveiller',
  '🚀 Ready for Launch!': '🚀 Prêt pour le lancement !',
  '🟠 Fair': '🟠 Passable',
  '🟡 Good': '🟡 Bon',
  '🟢 Excellent': '🟢 Excellent',
  'Awaiting approval': "En attente d'approbation",
  'Approved': 'Approuvé',
  'Requires approval': 'Nécessite une approbation',
  'This task is completed but still needs approval': 'Cette tâche est terminée mais doit encore être approuvée',
  'Once completed, this task must be approved before it closes': "Une fois terminée, cette tâche doit être approuvée avant d'être clôturée",
  'Approved by {name} on {date}': 'Approuvé par {name} le {date}',
  'Approved on {date}': 'Approuvé le {date}',
  'Approve': 'Approuver',
  'Request changes': 'Demander des modifications',
  'Send back to in progress': 'Renvoyer en cours',
  'What needs to change? (optional)': 'Que faut-il modifier ? (facultatif)',
  'Reason for sending the task back': 'Motif du renvoi de la tâche',
  'Waiting for someone else to approve your work': "En attente de l'approbation de votre travail par quelqu'un d'autre",
  '{name} marked this task as done and is waiting for approval': "{name} a marqué cette tâche comme terminée et attend l'approbation",
  'This task is marked as done and is waiting for approval': "Cette tâche est marquée comme terminée et attend l'approbation",
  'Require approval before this task can be closed': 'Exiger une approbation avant la clôture de cette tâche',
  'Task approved': 'Tâche approuvée',
  'Task sent back for changes': 'Tâche renvoyée pour modifications',
  'Marked as done, waiting for approval': "Marquée comme terminée, en attente d'approbation",
  'Awaiting my approval': 'En attente de mon approbation',
  'Loading tasks': 'Chargement des tâches',
  'Loading statistics': 'Chargement des statistiques',
  'Loading dashboard': 'Chargement du tableau de bord',
  'No tasks yet': "Aucune tâche pour l'instant",
  'Get started by creating your first task': 'Commencez par créer votre première tâche',
  'Try adjusting your filters': 'Essayez de modifier vos filtres',
  "Organize your team's work": "Organisez le travail de votre équipe",
  "TaskFlow helps teams organize work, track progress, and collaborate effectively. Let's take a quick tour of the key features.": "TaskFlow aide les équipes à organiser le travail, en suivre l'avancement et mieux collaborer. Faisons un tour rapide des fonctions principales.",
  'approved this task': 'a approuvé cette tâche',
  'sent it back for changes': 'l’a renvoyée pour modifications',
  'sent it back for changes: {reason}': 'l’a renvoyée pour modifications : {reason}',
  'Exit Bulk Mode': 'Quitter la sélection multiple',
  'Selected tasks: {count}': 'Tâches sélectionnées : {count}',
  'All Tasks ({count})': 'Toutes les tâches ({count})',
  'Unassigned ({count})': 'Non assignées ({count})',
};
