/**
 * Traduzioni, parte 5: le voci sfuggite alla sostituzione automatica.
 *
 * Sono soprattutto testi affiancati a un'icona dentro lo stesso elemento —
 * `<Button><Icona />My Permissions</Button>` — dove il testo non e' delimitato
 * da due tag e quindi non veniva riconosciuto. Sostituite a mano.
 */
export const PARTE_5: Record<string, string> = {
  'My Permissions': 'I miei permessi',
  'Avg Completion Time': 'Tempo medio di completamento',
  'Avg Tasks/Employee': 'Attività medie per persona',
  'Count': 'Numero',
  'Low': 'Bassa',
  'Metric': 'Indicatore',
  'Total Assigned Tasks': 'Attività assegnate in totale',
  'Value': 'Valore',
  'Generated': 'Generato il',
  'days': 'giorni',
  'Joined': 'Iscritto',
  'All': 'Tutti',
  'tasks': 'attività',
  'task': 'attività',
  'more': 'altre',
  'This user has': 'Questa persona ha',
  'assigned task(s). Those tasks will become unassigned.':
    'attività assegnate, che resteranno senza assegnatario.',
  'This action cannot be undone and any assigned tasks will become unassigned.':
    'Operazione non reversibile: le attività assegnate resteranno senza assegnatario.',
  'active': 'attivo',
  'inactive': 'non attivo',
  'Feedback Board': 'Bacheca dei riscontri',
  'Announcements': 'Annunci',
  'Skills (comma-separated)': 'Competenze (separate da virgola)',
  'Task created successfully!': 'Attività creata',
  'Task updated successfully!': 'Attività aggiornata',
  'Task reassigned successfully!': 'Attività riassegnata',
  'Task deleted': 'Attività eliminata',
  'Task completed!': 'Attività completata',
  'Task status distribution across departments':
    'Distribuzione degli stati fra i dipartimenti',
  'Top Clicked Links': 'Link più cliccati',
  'Visual reference for department color coding and icons used throughout the app':
    "Riferimento visivo dei colori e delle icone dei dipartimenti usati nell'applicazione",
  'TaskFlow Help & Documentation': 'Guida e documentazione',
  'TaskFlow is Production Ready!': 'TaskFlow è pronto per la produzione',
  "Get your webhook URL from Slack's Incoming Webhooks app":
    "Trova l'URL del webhook nell'app Incoming Webhooks di Slack",
  'TaskFlow Analytics - Team Performance Report':
    'TaskFlow - Report sulle prestazioni del team',
  'TaskFlow Analytics - Department Performance Report':
    'TaskFlow - Report sulle prestazioni per dipartimento',
  '{n}% complete': '{n}% completato',
  '{n} tasks/user': '{n} attività per utente',
  '{n} announcements': '{n} annunci',
  '{n} unassigned': '{n} senza assegnatario',
  'Last modified: {data} by {autore}': 'Ultima modifica: {data} da {autore}',
  'Variables': 'Variabili',
  'Note:': 'Nota:',
  'Email notifications are sent when enabled in user notification preferences. Variables will be automatically replaced with actual values when emails are sent.': 
    "Le email di notifica partono solo se sono attive nelle preferenze di notifica dell'utente. Le variabili vengono sostituite con i valori reali al momento dell'invio.",
  'Mention a teammate': 'Cita una persona del team',
  'Use the arrow keys to choose, Enter to confirm, Esc to close': 'Frecce per scegliere, Invio per confermare, Esc per chiudere',
  'Press Cmd+Enter to post. Type @ to mention a teammate': 'Cmd+Invio per pubblicare. Scrivi @ per citare una persona',
  'This attachment was blocked because its format is not allowed': 'Allegato bloccato: il formato non e’ consentito',
  'Edit comment': 'Modifica il commento',
  'Delete comment': 'Elimina il commento',
  'Post comment': 'Pubblica il commento',
  'Download attachment': 'Scarica l’allegato',
  'Delete attachment': 'Elimina l’allegato',
  'AI Service': 'Servizio AI',
  'Available': 'Disponibile',
  'Unavailable': 'Non disponibile',
  'Checking...': 'Verifica in corso...',
  'Shown in the application header and used in notification emails.': 'Compare in testata e nelle email di notifica.',
  'Notifications ({count} unread)': 'Notifiche ({count} da leggere)',
  'Delete notification': 'Elimina la notifica',
  'Edit task': 'Modifica l’attività',
  'Delete task': 'Elimina l’attività',
  'Select task': 'Seleziona l’attività',
  'Select {name}': 'Seleziona {name}',
  'Skip tour': 'Salta la presentazione',
  'tasks shown': 'attività mostrate',
  'Show more tasks': 'Mostra altre attività',
  'Calendar': 'Calendario',
  'Previous month': 'Mese precedente',
  'Next month': 'Mese successivo',
  'Today': 'Oggi',
  'Selected day': 'Giorno selezionato',
  'Priority: {priority}': 'Priorità: {priority}',
  'Tasks by due date for {month}': 'Attività per scadenza in {month}',
  '+{count} more': '+{count} altre',
  '{count} tasks': '{count} attività',
  '{count} overdue': '{count} in ritardo',
  '{count} scheduled this month': '{count} in programma questo mese',
  '{count} tasks have no due date and are not shown here': '{count} attività non hanno scadenza e non compaiono qui',
  'Every task has a due date': 'Tutte le attività hanno una scadenza',
  'Nothing due on this day': 'Niente in scadenza in questo giorno',
  'Nothing is due this month': 'Niente in scadenza questo mese',
  'Repeat': 'Ripeti',
  'Does not repeat': 'Non si ripete',
  'Daily': 'Ogni giorno',
  'Weekly': 'Ogni settimana',
  'Monthly': 'Ogni mese',
  'Repeat every': 'Ripeti ogni',
  'weeks': 'settimane',
  'months': 'mesi',
  'Repeat on': 'Ripeti nei giorni',
  'Leave empty to repeat on the same weekday.': 'Lascia vuoto per ripetere nello stesso giorno della settimana.',
  'End date (optional)': 'Data di fine (facoltativa)',
  'No end date': 'Nessuna data di fine',
  'Remove end date': 'Togli la data di fine',
  'Mon': 'Lun',
  'Tue': 'Mar',
  'Wed': 'Mer',
  'Thu': 'Gio',
  'Fri': 'Ven',
  'Sat': 'Sab',
  'Sun': 'Dom',
  'Tuesday': 'Martedì',
  'Wednesday': 'Mercoledì',
  'Thursday': 'Giovedì',
  'Friday': 'Venerdì',
  'Saturday': 'Sabato',
  'Daily summary instead of immediate emails': 'Riepilogo giornaliero al posto delle email immediate',
  'One email a day with the notifications you have not read, instead of one email for every event': 'Una email al giorno con le notifiche che non hai letto, invece di una email per ogni evento',
  'Summary time': 'Ora del riepilogo',
  'Times are in your timezone: {zone}': 'Gli orari sono nel tuo fuso: {zone}',
  'If there is nothing new, no email is sent. In-app notifications stay immediate.': "Se non c'è niente di nuovo, non parte nessuna email. Le notifiche nell'applicazione restano immediate.",
  'Daily summary enabled: one email per day instead of one per event': 'Riepilogo giornaliero attivo: una email al giorno invece di una per evento',
  'Immediate emails enabled: one email per event': 'Email immediate attive: una email per ogni evento',
  'No due date': 'Nessuna scadenza',
  'Blocked': 'Bloccata',
  'Labels': 'Etichette',
  'Search or add a label': 'Cerca o aggiungi un’etichetta',
  'Create label "{name}"': 'Crea l’etichetta "{name}"',
  'Remove label {name}': 'Togli l’etichetta {name}',
  'Label {name} added': 'Etichetta {name} aggiunta',
  'Label {name} removed': 'Etichetta {name} tolta',
  'Label suggestions': 'Etichette suggerite',
  'No matching label in use — type to create one': 'Nessuna etichetta in uso corrisponde — scrivila per crearla',
  'Labels are saved in lowercase so the same one is never created twice.': 'Le etichette si salvano in minuscolo, cosi’ la stessa non viene creata due volte.',
  'Similar labels already exist. Reusing one keeps filters useful.': 'Esistono etichette simili. Riusarne una tiene i filtri utili.',
  'Watchers': 'Osservatori',
  'Add someone who should follow this task': 'Aggiungi chi deve seguire questo task',
  'Nobody follows this task yet': 'Ancora nessuno segue questo task',
  'People who can follow this task': 'Chi puo’ seguire questo task',
  'No one else to add': 'Non c’e’ nessun altro da aggiungere',
  'No people to show': 'Nessuna persona da mostrare',
  'Follow this task': 'Segui questo task',
  'Following this task': 'Segue questo task',
  'Remove {name} from watchers': 'Togli {name} dagli osservatori',
  '{name} now follows this task': '{name} ora segue questo task',
  '{name} no longer follows this task': '{name} non segue piu’ questo task',
  'You are assigned to this task, so you already get every update.': 'Questo task e’ assegnato a te, quindi ricevi gia’ ogni aggiornamento.',
  '(you)': '(tu)',
  'Unknown user': 'Utente sconosciuto',
  'Removed member': 'Persona rimossa',
  'Estimated time': 'Tempo stimato',
  'Time spent': 'Tempo impiegato',
  'Estimated': 'Stimato',
  'No estimate': 'Nessuna stima',
  'Understood as': 'Interpretato come',
  'Not understood. Try 90, 1.5h or 2h 30m.': 'Non interpretato. Prova 90, 1.5h oppure 2h 30m.',
  'Leave empty if you cannot estimate it yet': 'Lascia vuoto se non riesci ancora a stimarlo',
  'Leave empty if not tracked': 'Lascia vuoto se non lo registri',
  'Leave empty if unknown': 'Lascia vuoto se non lo sai',
  'Same as the estimate': 'Come la stima',
  '{tempo} over the estimate': '{tempo} oltre la stima',
  '{tempo} under the estimate': '{tempo} sotto la stima',
  'at least {tempo}': 'almeno {tempo}',
  'Export Tasks': 'Esporta i task',
  'Choose the format, the columns and which tasks to include.': 'Scegli il formato, le colonne e quali task includere.',
  'Format': 'Formato',
  'Columns': 'Colonne',
  'Which tasks': 'Quali task',
  'Only the filtered tasks': 'Solo i task filtrati',
  'All tasks, including archived ones': 'Tutti i task, compresi quelli archiviati',
  'Select at least one column': 'Scegli almeno una colonna',
  '{righe} rows will be exported': 'Verranno esportate {righe} righe',
  'Export failed': 'Esportazione non riuscita',
  'Allow pop-ups to export the PDF': 'Consenti i pop-up per esportare il PDF',
  'Please allow pop-ups to download PDF': 'Consenti i pop-up per scaricare il PDF',
  'Task List': 'Elenco dei task',
  'Person': 'Persona',
  'Open': 'Aperti',
  'Saved filters': 'Filtri salvati',
  'Save current filters': 'Salva i filtri attuali',
  'Current filters are already saved': 'I filtri attuali sono gia’ salvati',
  'Name of this view': 'Nome di questa vista',
  'Rename this view': 'Rinomina questa vista',
  'Rename "{nome}"': 'Rinomina "{nome}"',
  'Delete "{nome}"': 'Elimina "{nome}"',
  'Delete this saved filter?': 'Eliminare questo filtro salvato?',
  '"{nome}" will be removed. The tasks are not affected.': '"{nome}" verra’ rimosso. I task non vengono toccati.',
  'Set some filters above, then save them here': 'Imposta dei filtri qui sopra, poi salvali qui',
  'Save the filters you use often — status, priority, department, assignee — and bring them back with one click.': 'Salva i filtri che usi spesso — stato, priorita’, reparto, assegnatario — e richiamali con un clic.',
  'Search: {testo}': 'Ricerca: {testo}',
  'Clear All': 'Azzera tutto',
  'Workload': 'Carico di lavoro',
  'Open tasks per person, and how much of that work has an estimate.': 'Task aperti per persona, e quanta parte di quel lavoro ha una stima.',
  'All {totale} open tasks have an estimate.': 'Tutti i {totale} task aperti hanno una stima.',
  '{senza} of {totale} open tasks have no estimate: that part of the workload is unknown.': '{senza} task aperti su {totale} non hanno una stima: quella parte del carico non e’ nota.',
  'Remove due date': 'Togli la scadenza',
  'Please enter a task title': 'Inserisci il titolo del task',
  'Task Title': 'Titolo',
};
