/** Traduzioni tedesche. Chiavi identiche a quelle italiane/inglesi. */
export const TESTI_DE: Record<string, string> = {
  // --- chiavi semantiche (partendo dall'italiano di i18n.ts) ---
  'app.sottotitolo': 'Verwalten Sie die Arbeit Ihres Teams',
  'login.titolo': 'Anmelden',
  'login.descrizione': 'Geben Sie Ihre Zugangsdaten ein, um fortzufahren.',
  'login.email': 'E-Mail',
  'login.password': 'Passwort',
  'login.entra': 'Anmelden',
  'login.inCorso': 'Anmeldung läuft...',
  'login.emailObbligatoria': 'Die E-Mail-Adresse ist erforderlich',
  'login.emailNonValida': 'Geben Sie eine gültige E-Mail-Adresse ein',
  'login.passwordObbligatoria': 'Das Passwort ist erforderlich',
  'login.erroreGenerico': 'Es ist ein unerwarteter Fehler aufgetreten',
  'login.operazioneFallita': 'Vorgang fehlgeschlagen',
  'login.accountDaAmministratore': 'Konten werden vom Administrator erstellt.',
  'login.contattaAmministratore':
    'Wenn die Anmeldung nicht gelingt, wenden Sie sich an ihn.',
  'login.passwordDimenticata': 'Passwort vergessen?',
  'login.invioInCorso': 'Wird gesendet...',
  'login.inserisciEmailPerRipristino':
    'Geben Sie Ihre E-Mail-Adresse ein und fordern Sie dann die Zurücksetzung an',
  'login.ripristinoInviato':
    'Wenn die Adresse zu einem Konto gehört, erhalten Sie einen Link zum Zurücksetzen des Passworts. Prüfen Sie auch den Spam-Ordner.',

  'password.sottotitolo': 'Wählen Sie ein neues Passwort',
  'password.titolo': 'Neues Passwort',
  'password.descrizione':
    'Legen Sie das Passwort fest, mit dem Sie sich künftig anmelden.',
  'password.nuova': 'Neues Passwort',
  'password.ripeti': 'Passwort wiederholen',
  'password.minimo': 'Mindestens 8 Zeichen.',
  'password.troppoCorta': 'Das Passwort muss mindestens 8 Zeichen lang sein',
  'password.nonCoincidono': 'Die beiden Passwörter stimmen nicht überein',
  'password.salva': 'Neues Passwort speichern',
  'password.salvataggio': 'Wird gespeichert...',
  'password.annullaEsci': 'Abbrechen und abmelden',

  'org.nessuna': 'Diesem Konto ist keine Organisation zugeordnet',
  'org.creaTitolo': 'Erstellen Sie Ihre Organisation',
  'org.creaDescrizione':
    'Wenn Sie die Anwendung zum ersten Mal einrichten, erstellen Sie hier den Arbeitsbereich: Sie werden dessen Eigentümer und können weitere Personen einladen. Sollten Sie dagegen zu einer bestehenden Organisation gehören, bitten Sie einen Administrator, Sie hinzuzufügen.',
  'org.nome': 'Name der Organisation',
  'org.crea': 'Organisation erstellen',
  'org.creazione': 'Wird erstellt...',
  'org.nuovaTitolo': 'Neue Organisation',
  'org.nuovaDescrizione':
    'Sie werden Eigentümer des neuen Arbeitsbereichs, der leer beginnt. Die Daten der aktuellen Organisation bleiben unverändert.',
  'org.attiva': 'Aktive Organisation',
  'org.creaNuova': 'Eine neue Organisation erstellen',
  'org.creata': 'Organisation "{nome}" erstellt',
  'org.creazioneFallita': 'Erstellung fehlgeschlagen',

  'account.disattivato': 'Konto deaktiviert',
  'account.disattivatoDescrizione':
    'Dieses Konto wurde von einem Administrator deaktiviert. Wenden Sie sich an ihn, wenn Sie einen Fehler vermuten.',

  'credenziali.titolo': 'Zugangsdaten',
  'credenziali.descrizione':
    'Übergeben Sie diese Zugangsdaten der Benutzerin oder dem Benutzer: Das vorläufige Passwort wird nicht per E-Mail verschickt und ist nach dem Schließen dieses Fensters nicht mehr sichtbar.',
  'credenziali.annotate': 'Ich habe die Zugangsdaten notiert',

  'comune.esci': 'Abmelden',
  'comune.annulla': 'Abbrechen',
  'comune.caricamento': 'Wird geladen…',
  'comune.lingua': 'Sprache',
  'comune.nessunaOrganizzazione': 'Keine aktive Organisation',
  'comune.sessioneScaduta': 'Sitzung abgelaufen, bitte erneut anmelden',
  'comune.inizializzazioneFallita': 'Initialisierung fehlgeschlagen',
  'comune.richiestaFallita': 'Anfrage fehlgeschlagen ({stato})',
  'comune.modificaNonSalvata': 'Änderung nicht gespeichert',
  'ai.nonConfigurata': 'Die KI-Funktionen sind nicht eingerichtet. Ein erneuter Versuch hilft nicht: Wenden Sie sich an eine Administratorin oder einen Administrator.',
  'ai.nonDisponibile': 'Der KI-Dienst ist derzeit nicht erreichbar. Versuchen Sie es gleich noch einmal.',
  'ai.tempoScaduto': 'Der KI-Dienst hat zu lange gebraucht. Versuchen Sie es erneut.',
  'ai.limiteRaggiunto': 'Sie haben das Limit an KI-Anfragen erreicht. Versuchen Sie es später erneut.',
  'ai.testoTroppoLungo': 'Der Text ist zu lang für die Verarbeitung.',
  'ai.rifiutata': 'Der KI-Dienst hat diese Anfrage nicht angenommen.',
  'email.nonPartita': 'Benachrichtigung gespeichert, aber die E-Mail wurde nicht versendet',

  // --- generale, azioni ricorrenti ---
  'Cancel': 'Abbrechen',
  'Close': 'Schließen',
  'Save': 'Speichern',
  'Delete': 'Löschen',
  'Edit': 'Bearbeiten',
  'Apply': 'Anwenden',
  'Back': 'Zurück',
  'Next': 'Weiter',
  'Clear': 'Leeren',
  'Clear all': 'Alles leeren',
  'Create New': 'Neu erstellen',
  'Complete': 'Abschließen',
  'Bulk': 'Mehrfachauswahl',
  'Analysis': 'Analyse',
  'Analytics': 'Auswertungen',
  'Dashboard': 'Übersicht',
  'Category': 'Kategorie',
  'Custom': 'Benutzerdefiniert',
  'Archived': 'Archiviert',
  'Already exists': 'Existiert bereits',
  'Confirm Delete': 'Löschen bestätigen',
  'Are you sure? This action cannot be undone!':
    'Sind Sie sicher? Dieser Vorgang kann nicht rückgängig gemacht werden.',
  'Are you sure you want to remove': 'Möchten Sie wirklich entfernen',
  'All time': 'Gesamter Zeitraum',
  'All types': 'Alle Typen',
  'All Categories': 'Alle Kategorien',
  'All Departments': 'Alle Abteilungen',
  'All Departments Selected': 'Alle Abteilungen ausgewählt',
  'All Members': 'Alle Mitglieder',
  'All Priority': 'Alle Prioritäten',
  'All Status': 'Alle Status',
  'No data available': 'Keine Daten verfügbar',

  // --- stati e priorità ---
  'Active': 'Aktiv',
  'Completed': 'Abgeschlossen',
  'In Progress': 'In Bearbeitung',
  'Not Started': 'Nicht begonnen',
  'Overdue': 'Überfällig',
  'Priority': 'Priorität',
  'Status': 'Status',
  'High': 'Hoch',
  'High Priority': 'Hohe Priorität',
  'Description': 'Beschreibung',

  // --- attività ---
  'Task': 'Aufgabe',
  'Tasks': 'Aufgaben',
  'Add Task': 'Aufgabe hinzufügen',
  'Create Task': 'Aufgabe erstellen',
  'Create New Task': 'Neue Aufgabe',
  'Total Tasks': 'Aufgaben gesamt',
  'Active Tasks': 'Aktive Aufgaben',
  'Completed Tasks': 'Abgeschlossene Aufgaben',
  'Assigned Tasks': 'Zugewiesene Aufgaben',
  'View Task': 'Aufgabe öffnen',
  'Assign To': 'Zuweisen an',
  'Assignee': 'Zugewiesene Person',
  'Add task details...': 'Details hinzufügen...',
  'Add a comment...': 'Kommentar schreiben...',
  'Add comments and attachments': 'Kommentare und Anhänge hinzufügen',
  "Add a new task to your team's workflow. Fill in the details below.":
    'Fügen Sie der Arbeit Ihres Teams eine neue Aufgabe hinzu. Füllen Sie die Felder unten aus.',
  "All changes are automatically tracked in the task's activity history.":
    'Alle Änderungen werden automatisch im Verlauf der Aufgabe festgehalten.',
  'Comment added!': 'Kommentar hinzugefügt',
  'Comment deleted': 'Kommentar gelöscht',
  'Comment updated!': 'Kommentar aktualisiert',
  'Comments and mentions': 'Kommentare und Erwähnungen',
  'Attachment removed': 'Anhang entfernt',
  'Completion Rate': 'Abschlussquote',
  'Average Completion Time': 'Durchschnittliche Bearbeitungszeit',
  'Avg. Completion Time': 'Durchschn. Bearbeitungszeit',
  'Avg Time': 'Durchschn. Zeit',
  'Avg Tasks': 'Durchschn. Aufgaben',
  'Avg Tasks per Member': 'Durchschn. Aufgaben pro Mitglied',
  'Avg/Employee': 'Durchschnitt pro Person',
  'Avg/User': 'Durchschnitt pro Benutzer',
  'Current state of all tasks': 'Aktueller Stand aller Aufgaben',
  'Consider task priorities and deadlines':
    'Berücksichtigt Prioritäten und Fristen',
  'Auto-archive Completed After (days)':
    'Abgeschlossene archivieren nach (Tage)',
  'Allow Task Deletion': 'Löschen von Aufgaben erlauben',
  'Configure task behavior and policies': 'Verhalten und Regeln der Aufgaben',

  // --- persone e dipartimenti ---
  'Admin': 'Administrator',
  'Admin (Super Admin)': 'Administrator (Super-Administrator)',
  'Add User': 'Benutzer hinzufügen',
  'Add Team Member': 'Teammitglied hinzufügen',
  'Add a new member to your team': 'Fügen Sie Ihrem Team eine Person hinzu',
  'Active Members': 'Aktive Mitglieder',
  'Active Users': 'Aktive Benutzer',
  'Active Team Members': 'Aktive Teammitglieder',
  'Avatar URL': 'Bild-URL',
  'Brief description about the team member...':
    'Kurze Beschreibung des Teammitglieds...',
  'Departments': 'Abteilungen',
  'Department already added': 'Abteilung bereits hinzugefügt',
  'Active Departments': 'Aktive Abteilungen',
  'Active departments': 'Aktive Abteilungen',
  'Archived Departments': 'Archivierte Abteilungen',
  'Archive inactive departments': 'Inaktive Abteilungen archivieren',
  'Add Department': 'Abteilung hinzufügen',
  'Add New Department': 'Neue Abteilung',
  'Create Department': 'Abteilung erstellen',
  'Custom Departments': 'Benutzerdefinierte Abteilungen',
  'Assign Departments': 'Abteilungen zuweisen',
  'Add to existing departments': 'Zu bestehenden Abteilungen hinzufügen',
  'Allow Multiple Departments': 'Mehrere Abteilungen erlauben',
  'Assign employees to multiple departments':
    'Personen mehreren Abteilungen zuweisen',
  'A department with this name already exists':
    'Eine Abteilung mit diesem Namen existiert bereits',
  'Brief description of this department...':
    'Kurze Beschreibung der Abteilung...',
  'Busiest Department': 'Am stärksten ausgelastete Abteilung',
  'Busiest Departments': 'Am stärksten ausgelastete Abteilungen',
  'Choose departments to assign to the selected team members':
    'Wählen Sie die Abteilungen, die den ausgewählten Teammitgliedern zugewiesen werden',
  'Create a new department to organize your team structure':
    'Erstellen Sie eine Abteilung, um die Struktur Ihres Teams zu ordnen',
  'Create and manage departments, assign leads, and track team organization':
    'Abteilungen erstellen und verwalten, Leitungen zuweisen und die Organisation verfolgen',
  'Create new departments with details (name, description, color, lead, budget)':
    'Neue Abteilungen mit Name, Beschreibung, Farbe, Leitung und Budget erstellen',
  'Create your first department to start organizing your team':
    'Erstellen Sie die erste Abteilung, um Ihr Team zu ordnen',
  'Add departments to team members to see department analytics':
    'Weisen Sie Teammitgliedern Abteilungen zu, um Auswertungen je Abteilung zu sehen',
  'Analytics across all departments': 'Auswertungen über alle Abteilungen',
  'Complete breakdown by department': 'Vollständige Aufschlüsselung nach Abteilung',
  'Auto-assign color': 'Farbe automatisch zuweisen',
  'Annual Budget': 'Jahresbudget',
  'Analyze team member workloads': 'Auslastung der Teammitglieder analysieren',
  'Custom Permissions': 'Benutzerdefinierte Berechtigungen',
  'Contact your administrator to request changes to your role or permissions.':
    'Wenden Sie sich an einen Administrator, um Ihre Rolle oder Ihre Berechtigungen ändern zu lassen.',

  // --- analisi ---
  'Analytics Dashboard': 'Auswertungsübersicht',
  'Average Engagement': 'Durchschnittliche Interaktion',
  'Avg Rating': 'Durchschnittliche Bewertung',
  'Comprehensive analytics for your team':
    'Umfassende Auswertungen für Ihr Team',
  'Comprehensive performance insights': 'Umfassender Blick auf die Leistung',
  'Complete performance breakdown': 'Vollständige Aufschlüsselung der Leistung',
  'Complete system overview and analytics':
    'Vollständiger Systemüberblick und Auswertungen',
  'Analyzing...': 'Analyse läuft...',
  'CSV report downloaded successfully!': 'CSV-Bericht heruntergeladen',
  'Can I export analytics reports?': 'Kann ich Auswertungsberichte exportieren?',
  'Can I attach files to tasks?': 'Kann ich Dateien an Aufgaben anhängen?',

  // --- AI ---
  'AI Assistant': 'KI-Assistent',
  'AI Auto-Assign': 'Automatische KI-Zuweisung',
  'AI Features': 'KI-Funktionen',
  'AI Insights': 'KI-Analysen',
  'AI Model': 'KI-Modell',
  'AI Recommendation': 'KI-Empfehlung',
  'AI Assignment Suggestions': 'KI-Vorschläge zur Zuweisung',
  'AI Duration & Deadline Estimate': 'KI-Schätzung von Dauer und Frist',
  'AI estimate generated!': 'KI-Schätzung erstellt',
  'Applied AI suggestion!': 'KI-Vorschlag angewendet',
  'Apply All Assignments': 'Alle Zuweisungen anwenden',
  'Apply This Suggestion': 'Diesen Vorschlag anwenden',
  'Assignment Mode': 'Zuweisungsmodus',
  'Ask me anything about your tasks and team!':
    'Fragen Sie mich alles zu Ihren Aufgaben und Ihrem Team',
  'Ask me anything about your tasks...':
    'Fragen Sie mich etwas zu Ihren Aufgaben...',
  'Configure AI-powered capabilities': 'KI-gestützte Funktionen konfigurieren',

  // --- annunci e feedback ---
  'Announcement': 'Ankündigung',
  'Announcement deleted': 'Ankündigung gelöscht',
  'Announcement posted!': 'Ankündigung veröffentlicht',
  'Announcement updated!': 'Ankündigung aktualisiert',
  'Announcement updated successfully!': 'Ankündigung aktualisiert',
  'Create announcements': 'Ankündigungen erstellen',
  'Be the first to share your thoughts!':
    'Sagen Sie als Erste oder Erster Ihre Meinung',
  'Brief summary of your feedback': 'Kurze Zusammenfassung Ihrer Rückmeldung',
  'Bug Report': 'Fehlermeldung',
  'Bug Reports': 'Fehlermeldungen',

  // --- notifiche ---
  'Choose which events trigger notifications':
    'Wählen Sie, welche Ereignisse eine Benachrichtigung auslösen',
  'Control how often you receive notifications':
    'Wie oft Sie Benachrichtigungen erhalten',
  'Control when and how you receive notifications':
    'Wann und wie Sie Benachrichtigungen erhalten',
  'All notification types disabled': 'Alle Benachrichtigungstypen deaktiviert',
  'All notification types enabled': 'Alle Benachrichtigungstypen aktiviert',
  'Batched (every 15 min)': 'Gebündelt (alle 15 Minuten)',
  'Daily digest': 'Tägliche Zusammenfassung',
  'Daily Digest Time': 'Uhrzeit der täglichen Zusammenfassung',

  // --- email ---
  'Bounce Rate': 'Rücklaufquote',
  'Click': 'Klick',
  'Clicks': 'Klicks',
  'Click Rate': 'Klickrate',
  'Click-to-Open Rate': 'Klicks je geöffneter E-Mail',
  'Combined open and click rate average':
    'Durchschnitt aus Öffnungs- und Klickrate',
  'Attachment Inclusion': 'Anhänge einbeziehen',
  'Allowed File Types': 'Erlaubte Dateitypen',
  'Currently allowed file types for email attachments':
    'Derzeit als E-Mail-Anhang erlaubte Dateitypen',
  'Alert users when attachments cannot be included':
    'Hinweisen, wenn ein Anhang nicht eingefügt werden kann',
  'Configure how task attachments are included in email notifications':
    'Wie Anhänge von Aufgaben in Benachrichtigungs-E-Mails eingefügt werden',
  'Control whether task attachments are sent with email notifications':
    'Legt fest, ob Anhänge von Aufgaben mit den E-Mails versendet werden',
  'Customize email notifications sent to users for various task events':
    'Passen Sie die E-Mails für die verschiedenen Aufgabenereignisse an',
  'Available Variables': 'Verfügbare Variablen',
  'Click a variable to insert it at cursor position':
    'Klicken Sie eine Variable an, um sie an der Cursorposition einzufügen',
  'Best regards,': 'Mit freundlichen Grüßen,',

  // --- amministrazione ---
  'Access email settings and system configuration':
    'Zu den E-Mail-Einstellungen und zur Systemkonfiguration',
  'Active Settings Summary': 'Zusammenfassung der aktiven Einstellungen',
  'Application Name': 'Name der Anwendung',
  'Company Name': 'Name des Unternehmens',
  'Basic application configuration': 'Grundlegende Konfiguration der Anwendung',
  'Configure system-wide settings and preferences':
    'Systemweite Einstellungen konfigurieren',
  'Current system status and statistics':
    'Aktueller Systemzustand und Statistiken',
  'Current data usage across all collections': 'Aktuell belegter Speicherplatz',
  'Audit Entries': 'Protokolleinträge',
  'Audit Log': 'Prüfprotokoll',
  'Audit Logging': 'Protokollierung',
  'Audit log cleared': 'Prüfprotokoll geleert',
  'Clear Audit Log': 'Prüfprotokoll leeren',
  'Clear All Data': 'Alle Daten löschen',
  'All data cleared successfully': 'Alle Daten wurden gelöscht',
  'Backup & Restore': 'Sicherung und Wiederherstellung',
  'Backup, restore, and manage system data':
    'Sicherung, Wiederherstellung und Verwaltung der Daten',
  'Changes discarded': 'Änderungen verworfen',
  'Allow Self Registration': 'Selbstregistrierung erlauben',
  'Allowed IP Addresses': 'Erlaubte IP-Adressen',
  'Add IP Address': 'IP-Adresse hinzufügen',
  'Central Time': 'Central Time',
  'Custom Time Range': 'Benutzerdefinierter Zeitraum',
  'DD/MM/YYYY': 'TT/MM/JJJJ',
  'After 81 iterations, your application is ready to deploy.':
    'Nach 81 Iterationen ist Ihre Anwendung bereit für die Veröffentlichung.',
  'Click the': 'Klicken Sie auf',

  // --- testi la cui lingua di partenza è l'italiano ---
  'Accesso revocato e membro rimosso': 'Zugang entzogen und Mitglied entfernt',
  'Apri TaskFlow per vedere i dettagli.':
    'Öffnen Sie TaskFlow, um die Details zu sehen.',
  'Assegna una nuova password provvisoria':
    'Ein neues vorläufiges Passwort vergeben',
  'Backup ripristinato. Ricarico la pagina...':
    'Sicherung wiederhergestellt. Seite wird neu geladen...',

  // --- dati e backup ---
  'Data': 'Daten',
  'Data Management': 'Datenverwaltung',
  'Data Retention (days)': 'Aufbewahrung der Daten (Tage)',
  'Data Safety': 'Datensicherheit',
  'Data exported successfully!': 'Daten exportiert',
  'Data imported successfully! Refresh to see changes.':
    'Daten importiert. Laden Sie die Seite neu, um die Änderungen zu sehen.',
  'Download a backup of all tasks, employees, and settings':
    'Laden Sie eine Sicherung aller Aufgaben, Personen und Einstellungen herunter',
  'Download a complete backup of all system data including tasks, users, settings, and audit logs.':
    'Laden Sie eine vollständige Sicherung herunter: Aufgaben, Benutzer, Einstellungen und Prüfprotokoll.',
  'Export': 'Exportieren',
  'Export Backup': 'Sicherung exportieren',
  'Export Data': 'Daten exportieren',
  'Export Report': 'Bericht exportieren',
  'Export as CSV': 'Als CSV exportieren',
  'Export as PDF': 'Als PDF exportieren',
  'Export, import, or clear your TaskFlow data':
    'Daten exportieren, importieren oder löschen',
  'Import Data': 'Daten importieren',
  'Failed to clear data': 'Löschen der Daten fehlgeschlagen',
  'Failed to export data': 'Export fehlgeschlagen',
  'Failed to export CSV report': 'Export des CSV-Berichts fehlgeschlagen',
  'Failed to export PDF report': 'Export des PDF-Berichts fehlgeschlagen',
  'Failed to import data. Please check the file format.':
    'Import fehlgeschlagen. Prüfen Sie das Dateiformat.',
  'Failed to read file': 'Datei konnte nicht gelesen werden',
  'File attached successfully!': 'Datei angehängt',
  'File size must be less than 10MB':
    'Die Datei muss kleiner als 10 MB sein',
  'Files are stored securely and can be downloaded or deleted by authorized users.':
    'Die Dateien werden sicher gespeichert und können von berechtigten Personen heruntergeladen oder gelöscht werden.',

  // --- eliminazioni e conferme ---
  'Delete Department?': 'Abteilung löschen?',
  'Delete Task?': 'Aufgabe löschen?',
  'Delete Team Member?': 'Teammitglied entfernen?',
  'Delete Task': 'Aufgabe löschen',
  'Discard Changes': 'Änderungen verwerfen',
  'Deselect All': 'Auswahl aufheben',
  'Disable All': 'Alle deaktivieren',
  'Enable All': 'Alle aktivieren',
  'Declined': 'Abgelehnt',

  // --- dipartimenti ---
  'Department': 'Abteilung',
  'Department Admin Dashboard': 'Übersicht der Abteilungsleitung',
  'Department Analytics': 'Auswertungen je Abteilung',
  'Department Analytics Report': 'Auswertungsbericht je Abteilung',
  'Department Announcements': 'Ankündigungen der Abteilung',
  'Department Color': 'Farbe der Abteilung',
  'Department Color Guide': 'Farbleitfaden der Abteilungen',
  'Department Colors': 'Farben der Abteilungen',
  'Department Details': 'Details der Abteilung',
  'Department Health': 'Zustand der Abteilung',
  'Department Information': 'Informationen zur Abteilung',
  'Department Lead': 'Abteilungsleitung',
  'Department Management': 'Verwaltung der Abteilungen',
  'Department Performance': 'Leistung je Abteilung',
  'Department Performance Overview': 'Leistungsüberblick je Abteilung',
  'Department Performance Radar': 'Leistungsradar je Abteilung',
  'Department Settings': 'Einstellungen der Abteilungen',
  'Department Summary': 'Zusammenfassung der Abteilung',
  'Department Tasks': 'Aufgaben der Abteilung',
  'Department Templates': 'Abteilungsvorlagen',
  'Department name is required': 'Der Name der Abteilung ist erforderlich',
  'Department organization and policies':
    'Organisation und Regeln der Abteilungen',
  'Departments with issues': 'Abteilungen mit Problemen',
  'Edit Department': 'Abteilung bearbeiten',
  'Enable Department Budgets': 'Abteilungsbudgets aktivieren',
  'Employee Count by Department': 'Anzahl der Personen je Abteilung',
  'Filter tasks by department': 'Aufgaben nach Abteilung filtern',
  'Engineering, Sales, Marketing...': 'Technik, Vertrieb, Marketing...',
  'Enter department name or select existing':
    'Namen der Abteilung eingeben oder eine bestehende wählen',
  'Lead': 'Leitung',
  'Leads': 'Leitungen',

  // --- persone ---
  'Default User Role': 'Standardrolle',
  'Designate as Team Lead': 'Als Teamleitung festlegen',
  'Edit Team Member': 'Teammitglied bearbeiten',
  'Employees': 'Personen',
  'Employee Performance': 'Leistung der Personen',
  'Email Address': 'E-Mail-Adresse',
  'Email is required: the account is created from this address':
    'Die E-Mail-Adresse ist erforderlich: Das Konto wird aus dieser Adresse erstellt',
  'Invalid name or role': 'Name oder Rolle ungültig',
  'Full system access': 'Vollständiger Systemzugriff',
  'Highest workload per employee': 'Höchste Auslastung pro Person',
  'Highest completion rates': 'Höchste Abschlussquoten',
  'Highest Rated': 'Beste Bewertung',
  'Health Score': 'Zustandswert',
  'Inactive': 'Inaktiv',

  // --- attività ---
  'Edit Task': 'Aufgabe bearbeiten',
  'Enter task title...': 'Titel der Aufgabe...',
  'Due Date': 'Fälligkeitsdatum',
  'Default Task Duration (days)': 'Standarddauer einer Aufgabe (Tage)',
  'Escalate Overdue After (days)': 'Überfällige Aufgaben melden nach (Tage)',
  'Estimated Duration': 'Geschätzte Dauer',
  'Enable Subtasks': 'Teilaufgaben aktivieren',
  'Enable Task Dependencies': 'Abhängigkeiten zwischen Aufgaben aktivieren',
  'High Priority Tasks': 'Aufgaben mit hoher Priorität',
  'In Progress Tasks': 'Aufgaben in Bearbeitung',
  'From creation to completion': 'Von der Erstellung bis zum Abschluss',
  'Key Factors': 'Wichtigste Faktoren',
  'Generate Estimate': 'Schätzung erstellen',
  'Generate optimal assignment suggestions':
    'Optimale Zuweisungsvorschläge erstellen',
  'Get intelligent insights and suggestions for your tasks':
    'Analysen und Vorschläge zu Ihren Aufgaben',
  'Enable Auto-Assignment': 'Automatische Zuweisung aktivieren',
  'Enable Smart Suggestions': 'Intelligente Vorschläge aktivieren',
  'Enable AI Features': 'KI-Funktionen aktivieren',
  'Enable all AI-powered features': 'Alle KI-gestützten Funktionen aktivieren',
  'Insights updated!': 'Analysen aktualisiert',

  // --- annunci ---
  'Edit announcement': 'Ankündigung bearbeiten',
  'Editing announcement': 'Ankündigung wird bearbeitet',
  'Enter announcement title': 'Titel der Ankündigung',
  'Enter your announcement message...': 'Text der Ankündigung...',
  'Invalid title or message': 'Titel oder Nachricht ungültig',
  'Important': 'Wichtig',
  'Info': 'Information',

  // --- notifiche ---
  'Delivery Frequency': 'Zustellhäufigkeit',
  'Desktop Alerts': 'Desktop-Hinweise',
  'Desktop Notifications': 'Desktop-Benachrichtigungen',
  'Desktop notifications enabled!': 'Desktop-Benachrichtigungen aktiviert',
  'Desktop notifications were blocked. Please enable them in your browser settings.':
    'Desktop-Benachrichtigungen sind blockiert. Aktivieren Sie sie in den Einstellungen Ihres Browsers.',
  'Enable Notifications': 'Benachrichtigungen aktivieren',
  'Enable System Notifications': 'Systembenachrichtigungen aktivieren',
  'Enable Email Notifications': 'E-Mail-Benachrichtigungen aktivieren',
  'Email Notifications': 'E-Mail-Benachrichtigungen',
  'Get notified via email about task updates':
    'Erhalten Sie Aktualisierungen zu Aufgaben per E-Mail',
  'End Time': 'Endzeit',
  'Hourly': 'Stündlich',
  'Last 7 days': 'Letzte 7 Tage',
  'Last 30 days': 'Letzte 30 Tage',
  'Last 90 days': 'Letzte 90 Tage',

  // --- email ---
  'Delivery Logs': 'Zustellprotokoll',
  'Device': 'Gerät',
  'Device Distribution': 'Verteilung nach Gerät',
  'Email': 'E-Mail',
  'Email Activity Over Time': 'E-Mail-Aktivität im Zeitverlauf',
  'Email Analytics': 'E-Mail-Auswertungen',
  'Email Attachments': 'E-Mail-Anhänge',
  'Email Attachment Settings': 'Einstellungen für Anhänge',
  'Email Delivery Analytics': 'Auswertung der E-Mail-Zustellung',
  'Email Template Customization': 'Anpassung der E-Mail-Vorlagen',
  'Email Templates': 'E-Mail-Vorlagen',
  'Email Types Distribution': 'Verteilung nach E-Mail-Typ',
  'Email attachment settings saved': 'Einstellungen für Anhänge gespeichert',
  'Email subject...': 'Betreff...',
  'Email template saved successfully!': 'E-Mail-Vorlage gespeichert',
  'Engagement': 'Interaktion',
  'Engagement Metrics': 'Kennzahlen zur Interaktion',
  'Exclusion Notifications': 'Hinweise auf ausgeschlossene Anhänge',
  'Executable files (.exe, .bat, .sh) are automatically excluded for security reasons':
    'Ausführbare Dateien (.exe, .bat, .sh) werden aus Sicherheitsgründen automatisch ausgeschlossen',
  'Include a note in the email when some attachments exceed size limits':
    'Einen Hinweis in die E-Mail aufnehmen, wenn Anhänge die Größenbeschränkung überschreiten',
  'Include attachments in emails': 'Anhänge in E-Mails einfügen',
  'Individual files larger than this will be excluded from emails':
    'Größere Einzeldateien werden nicht per E-Mail versendet',
  'Images': 'Bilder',
  'HTML Template': 'HTML-Vorlage',
  'Latest email delivery activity': 'Letzte Zustellungen',
  'Editor': 'Editor',

  // --- sistema ---
  'Date Format': 'Datumsformat',
  'Eastern Time': 'Eastern Time',
  'Enable API Access': 'API-Zugriff aktivieren',
  'Enable Audit Log': 'Prüfprotokoll aktivieren',
  'Enable IP Whitelist': 'Liste erlaubter IP-Adressen aktivieren',
  'Enable Slack Integration': 'Slack-Integration aktivieren',
  'Enable Two-Factor Authentication': 'Zwei-Faktor-Authentifizierung aktivieren',
  'Enforce password complexity rules':
    'Regeln zur Passwortkomplexität durchsetzen',
  'Expiration Date': 'Ablaufdatum',
  'External service connections': 'Verbindungen zu externen Diensten',
  'General': 'Allgemein',
  'General Settings': 'Allgemeine Einstellungen',
  'Integrations': 'Integrationen',
  'Invalid IP address format': 'Ungültiges Format der IP-Adresse',
  'IP address added': 'IP-Adresse hinzugefügt',
  'IP address removed': 'IP-Adresse entfernt',
  'Last 10 system changes': 'Letzte 10 Systemänderungen',
  'Iterations': 'Iterationen',
  'Launch Info': 'Informationen zum Start',
  'Language': 'Sprache',
  'English': 'Englisch',
  'Italian': 'Italienisch',
  'French': 'Französisch',
  'German': 'Deutsch',
  'GPT-4o (More capable)': 'GPT-4o (leistungsfähiger)',
  'GPT-4o-mini (Faster)': 'GPT-4o-mini (schneller)',

  // --- aiuto e riscontri ---
  'Help': 'Hilfe',
  'Help us improve TaskFlow by sharing your thoughts, suggestions, or reporting issues.':
    'Helfen Sie uns, TaskFlow zu verbessern: Teilen Sie Ihre Meinung und Vorschläge mit oder melden Sie ein Problem.',
  'Everything you need to know about using TaskFlow effectively':
    'Alles, was Sie für die tägliche Arbeit mit TaskFlow wissen müssen',
  'Feature Request': 'Funktionswunsch',
  'Feature Requests': 'Funktionswünsche',
  'Features': 'Funktionen',
  'Feedback Type': 'Art der Rückmeldung',
  'Feedback status updated': 'Status der Rückmeldung aktualisiert',
  'Give Feedback': 'Rückmeldung geben',
  'How would you rate your experience?':
    'Wie bewerten Sie Ihre Erfahrung?',
  'How do I access analytics?': 'Wie rufe ich die Auswertungen auf?',
  'How do I add comments to tasks?':
    'Wie füge ich einer Aufgabe Kommentare hinzu?',
  'How do I add team members?': 'Wie füge ich Teammitglieder hinzu?',
  'How do I create a new task?': 'Wie erstelle ich eine neue Aufgabe?',
  'How do I edit an existing task?':
    'Wie bearbeite ich eine bestehende Aufgabe?',
  'How do I manage departments?': 'Wie verwalte ich die Abteilungen?',
  'How do bulk operations work?': 'Wie funktionieren Mehrfachaktionen?',
  'How does AI Auto-Assignment work?':
    'Wie funktioniert die automatische KI-Zuweisung?',
  'Improvement Suggestion': 'Verbesserungsvorschlag',
  'Improvements': 'Verbesserungen',
  "I'll Do It Later": 'Später erledigen',
  'Detailed Performance Metrics': 'Detaillierte Leistungskennzahlen',
  'Il file non contiene dati da ripristinare':
    'Die Datei enthält keine Daten zum Wiederherstellen',

  // --- anagrafica e ruoli ---
  'Leave blank to auto-generate an avatar':
    'Leer lassen, um ein Bild automatisch zu erzeugen',
  'Location': 'Standort',
  'Manage': 'Verwalten',
  'Manage Role & Permissions': 'Rolle und Berechtigungen verwalten',
  'Manage Team': 'Team verwalten',
  'Manage Users': 'Benutzer verwalten',
  'Manage all users and departments':
    'Alle Benutzer und Abteilungen verwalten',
  'Manage tasks within their department(s)':
    'Verwaltet die Aufgaben der eigenen Abteilungen',
  'Manage your team members, roles, and departments':
    'Verwalten Sie Teammitglieder, Rollen und Abteilungen',
  "Manage your team's work efficiently":
    'Organisieren Sie die Arbeit Ihres Teams',
  'Manager': 'Manager',
  'Manager (Department Admin)': 'Manager (Abteilungsleitung)',
  'Member': 'Mitglied',
  'Name': 'Name',
  'Name and role are required': 'Name und Rolle sind erforderlich',
  'Phone Number': 'Telefonnummer',
  'Role': 'Rolle',
  'Role and permissions updated successfully':
    'Rolle und Berechtigungen aktualisiert',
  'Need different permissions?': 'Benötigen Sie andere Berechtigungen?',
  'Override default role permissions with custom settings':
    'Die Standardberechtigungen der Rolle durch eigene Einstellungen ersetzen',
  'Permission Status': 'Status der Berechtigungen',
  'Search by name, role, email, department, skills...':
    'Suche nach Name, Rolle, E-Mail, Abteilung, Fähigkeiten...',
  'Select All': 'Alle auswählen',
  'Set Active': 'Als aktiv markieren',
  'Set Inactive': 'Als inaktiv markieren',
  'Senior Developer': 'Senior-Entwickler',
  'San Francisco, CA': 'Berlin, Deutschland',
  'New York, Remote...': 'München, Remote...',
  'React, TypeScript, Node.js': 'React, TypeScript, Node.js',

  // --- dipartimenti ---
  'No Department Data': 'Keine Daten zu Abteilungen',
  'No department data available': 'Keine Daten zu Abteilungen verfügbar',
  'No departments selected. Add departments above.':
    'Keine Abteilung ausgewählt. Fügen Sie oben eine hinzu.',
  'No departments yet': 'Noch keine Abteilungen',
  'No employees assigned to this department':
    'Dieser Abteilung ist keine Person zugewiesen',
  'Multi-metric comparison across departments':
    'Vergleich mehrerer Kennzahlen zwischen Abteilungen',
  'Quick insights for your departments':
    'Schneller Blick auf Ihre Abteilungen',
  'Quick-start templates for common department types. Choose individual departments or create entire categories at once.':
    'Fertige Vorlagen für die gängigsten Abteilungen. Wählen Sie eine einzelne Abteilung oder erstellen Sie ganze Kategorien auf einmal.',
  'Replace all departments': 'Alle Abteilungen ersetzen',
  'Require Department Assignment': 'Zuweisung zu einer Abteilung verlangen',
  'Select All Departments': 'Alle Abteilungen auswählen',
  'Select a team lead (optional)': 'Eine Leitung wählen (optional)',
  'Set department leads': 'Abteilungsleitungen festlegen',
  'Please select at least one department':
    'Wählen Sie mindestens eine Abteilung',

  // --- attività ---
  'Low Priority': 'Niedrige Priorität',
  'Medium': 'Mittel',
  'Medium Priority': 'Mittlere Priorität',
  'My Dashboard': 'Meine Übersicht',
  'My Tasks': 'Meine Aufgaben',
  'Match skills and departments':
    'Bringt Fähigkeiten und Abteilungen in Einklang',
  'New Task Assigned': 'Neue Aufgabe zugewiesen',
  'New Comment': 'Neuer Kommentar',
  'New Announcement': 'Neue Ankündigung',
  'Not Started Tasks': 'Noch nicht begonnene Aufgaben',
  'No task data available yet': 'Noch keine Daten zu Aufgaben',
  'No tasks found': 'Keine Aufgaben gefunden',
  'No unassigned tasks to assign': 'Keine Aufgabe zum Zuweisen vorhanden',
  'No upcoming deadlines in the next 3 days':
    'Keine Fristen in den nächsten 3 Tagen',
  'Overdue Tasks': 'Überfällige Aufgaben',
  'Overdue tasks (priority)': 'Überfällige Aufgaben (Priorität)',
  'Priority Breakdown': 'Aufschlüsselung nach Priorität',
  'Priority Distribution': 'Verteilung der Prioritäten',
  'Priority Warnings': 'Prioritätswarnungen',
  'Please enter a task title first':
    'Geben Sie zuerst den Titel der Aufgabe ein',
  'Reminder Before Due (days)': 'Erinnerung vor der Fälligkeit (Tage)',
  'Require Task Approval': 'Freigabe von Aufgaben verlangen',
  'Requiring immediate attention': 'Erfordern sofortige Aufmerksamkeit',
  'Needs Attention': 'Erfordert Aufmerksamkeit',
  'Need attention': 'Erfordern Aufmerksamkeit',
  'Review the suggested task assignments below. These are optimized for workload balance and task requirements.':
    'Prüfen Sie die vorgeschlagenen Zuweisungen: Sie berücksichtigen die Auslastung und die Anforderungen der Aufgaben.',
  'Review the suggestions before applying them.':
    'Prüfen Sie die Vorschläge, bevor Sie sie anwenden.',

  // --- messaggi vuoti ---
  'No active employees available': 'Keine aktive Person verfügbar',
  'No activity yet': 'Noch keine Aktivität',
  'No announcements': 'Keine Ankündigungen',
  'No attachments yet': 'Noch keine Anhänge',
  'No audit entries yet': 'Noch keine Protokolleinträge',
  'No click data available': 'Keine Daten zu Klicks',
  'No comments yet': 'Noch keine Kommentare',
  'No feedback yet': 'Noch keine Rückmeldungen',
  'No insights available yet': 'Noch keine Analysen verfügbar',
  'No notifications': 'Keine Benachrichtigungen',
  'No performance data available': 'Keine Daten zur Leistung',
  'No team members found': 'Keine Teammitglieder gefunden',
  'No team members yet. Add team members to see analytics.':
    'Noch keine Teammitglieder. Fügen Sie welche hinzu, um Auswertungen zu sehen.',
  'None': 'Keine',

  // --- notifiche ---
  'Mark all read': 'Alle als gelesen markieren',
  'Mark as read': 'Als gelesen markieren',
  'Muted': 'Stummgeschaltet',
  'Notification Frequency': 'Häufigkeit der Benachrichtigungen',
  'Notification Retention (days)':
    'Aufbewahrung der Benachrichtigungen (Tage)',
  'Notification Settings': 'Benachrichtigungseinstellungen',
  'Notification Sounds': 'Benachrichtigungstöne',
  'Notification Type': 'Benachrichtigungstyp',
  'Notification Types': 'Benachrichtigungstypen',
  'Notifications': 'Benachrichtigungen',
  'Notifications will be paused between these times':
    'In diesem Zeitraum werden die Benachrichtigungen ausgesetzt',
  'Notify when attachments are excluded':
    'Hinweisen, wenn ein Anhang ausgeschlossen wird',
  'Pause notifications during specific times':
    'Benachrichtigungen zu bestimmten Zeiten aussetzen',
  'Play sounds when notifications arrive':
    'Bei eingehenden Benachrichtigungen einen Ton abspielen',
  'Quiet Hours': 'Ruhezeiten',
  'Quiet Hours Active': 'Ruhezeiten aktiv',
  'Real-time': 'In Echtzeit',
  'Receive notifications': 'Benachrichtigungen erhalten',
  'Receive notifications via email':
    'Benachrichtigungen per E-Mail erhalten',
  'Receive real-time alerts on your desktop for important task updates':
    'Erhalten Sie sofortige Hinweise auf dem Desktop zu wichtigen Aktualisierungen',
  'Send Test Notification': 'Testbenachrichtigung senden',

  // --- email ---
  'Max Attachment Size (MB)': 'Maximale Größe eines Anhangs (MB)',
  'Maximum single attachment size': 'Maximale Größe eines einzelnen Anhangs',
  'Maximum total attachment size per email':
    'Maximale Gesamtgröße der Anhänge',
  'Most email providers have attachment size limits. SendGrid and Resend both support up to 25MB total.':
    'Fast alle Anbieter begrenzen die Größe von Anhängen: SendGrid und Resend erlauben insgesamt bis zu 25 MB.',
  'Most popular links in your emails':
    'Am häufigsten angeklickte Links in Ihren E-Mails',
  'Office Documents': 'Office-Dokumente',
  'PDF Documents': 'PDF-Dokumente',
  'Open Rate': 'Öffnungsrate',
  'Opened': 'Geöffnet',
  'Open and click rates for different email types':
    'Öffnungen und Klicks je E-Mail-Typ',
  'Percentage of opened emails that received clicks':
    'Anteil der geöffneten E-Mails, die einen Klick erhalten haben',
  'Performance by Email Type': 'Leistung je E-Mail-Typ',
  'Plain Text': 'Nur Text',
  'Preview': 'Vorschau',
  'Recent Deliveries': 'Letzte Zustellungen',
  'Recipient': 'Empfänger',
  'Resend': 'Resend',
  'SendGrid': 'SendGrid',
  'Sent': 'Gesendet',
  'Set maximum file sizes for email attachments':
    'Legen Sie die maximale Größe der Anhänge fest',
  'Save Template': 'Vorlage speichern',

  // --- sistema ---
  'MM/DD/YYYY': 'MM/TT/JJJJ',
  'Maintenance Mode': 'Wartungsmodus',
  'Max AI Requests Per Day': 'Maximale KI-Anfragen pro Tag',
  'Max Login Attempts': 'Maximale Anmeldeversuche',
  'Monday': 'Montag',
  'Mountain Time': 'Mountain Time',
  'Pacific Time': 'Pacific Time',
  'London': 'London',
  'Paris': 'Paris',
  'Password Expiry (days)': 'Ablauf des Passworts (Tage)',
  'Permanently delete all audit log entries. This action cannot be undone.':
    'Löscht alle Einträge des Prüfprotokolls endgültig. Dies kann nicht rückgängig gemacht werden.',
  'Permanently delete all tasks, employees, and settings':
    'Aufgaben, Personen und Einstellungen endgültig löschen',
  'Require 2FA for all users':
    'Zwei-Faktor-Authentifizierung für alle verlangen',
  'Require Email Verification': 'Bestätigung der E-Mail-Adresse verlangen',
  'Require Strong Passwords': 'Sichere Passwörter verlangen',
  'Reset': 'Zurücksetzen',
  'Reset to Default': 'Auf den Standardwert zurücksetzen',
  'Reset to Defaults': 'Auf die Standardwerte zurücksetzen',
  'Restore': 'Wiederherstellen',
  'Restore from a previous backup file':
    'Aus einer früheren Sicherungsdatei wiederherstellen',
  'Restore system data from a previously exported backup file.':
    'Stellen Sie die Daten aus einer zuvor exportierten Sicherung wieder her.',
  'Save Changes': 'Änderungen speichern',
  'Save Settings': 'Einstellungen speichern',
  'Security': 'Sicherheit',
  'Security Settings': 'Sicherheitseinstellungen',
  'Security Status': 'Sicherheitsstatus',
  'Security policies and audit configuration':
    'Sicherheitsregeln und Konfiguration des Prüfprotokolls',
  'Session Timeout (minutes)': 'Ablauf der Sitzung (Minuten)',
  'Set expiration date': 'Ablaufdatum festlegen',
  'Please set an expiry date': 'Legen Sie ein Ablaufdatum fest',
  'Overview': 'Übersicht',
  'Overall Summary': 'Gesamtzusammenfassung',
  'Quick Actions': 'Schnellaktionen',
  'Quick Info': 'Kurzinformationen',
  'Quick Presets': 'Voreinstellungen',
  'Recent Activity': 'Letzte Aktivität',
  'Recent Audit Log': 'Letzte Protokolleinträge',
  'Refresh': 'Aktualisieren',
  'Previous': 'Zurück',
  'Rate': 'Bewerten',
  'Recommendations': 'Empfehlungen',
  'Review': 'Prüfen',
  'Reviewing': 'In Prüfung',
  'Review and manage feedback from your team members':
    'Rückmeldungen des Teams lesen und verwalten',
  'Performance': 'Leistung',
  'Performance Patterns': 'Leistungsverlauf',
  'Message': 'Nachricht',
  'Most Popular': 'Am beliebtesten',
  'Most Recent': 'Neueste',
  'Other': 'Sonstiges',
  'Pinned': 'Angeheftet',
  'Planned': 'Geplant',
  'Praise': 'Lob',
  'Praise & Thanks': 'Lob und Dank',
  'Post Announcement': 'Ankündigung veröffentlichen',
  'New 30d': 'Neu in 30 Tagen',
  'Questions or need help? Check the Help Documentation or contact your administrator.':
    'Fragen oder Hilfe nötig? Sehen Sie in der Dokumentation nach oder wenden Sie sich an einen Administrator.',

  // --- validazioni ---
  'Please enter a message': 'Geben Sie eine Nachricht ein',
  'Please enter a title': 'Geben Sie einen Titel ein',
  'Please enter a valid email address':
    'Geben Sie eine gültige E-Mail-Adresse ein',
  'Please provide a description': 'Fügen Sie eine Beschreibung hinzu',
  'Please provide a title': 'Fügen Sie einen Titel hinzu',
  'Please provide as much detail as possible...':
    'Beschreiben Sie es so genau wie möglich...',
  'PDF report will open in print dialog':
    'Der PDF-Bericht wird im Druckdialog geöffnet',

  // --- testi già in italiano ---
  'Rimossa dalla configurazione una chiave API salvata dalla versione precedente: le chiavi vivono solo lato server.':
    'Ein von der vorherigen Version gespeicherter API-Schlüssel wurde aus der Konfiguration entfernt: Schlüssel liegen ausschließlich auf dem Server.',
  'Se stai leggendo questo messaggio, la configurazione di invio lato server funziona.':
    'Wenn Sie diese Nachricht lesen, funktioniert der serverseitige E-Mail-Versand.',
  'Sessione scaduta, accedi di nuovo':
    'Sitzung abgelaufen, bitte erneut anmelden',
  'Serve il ruolo': 'Erfordert die Rolle',
  'Invio di prova': 'Testversand',
  'Indica un indirizzo a cui inviare la prova':
    'Geben Sie eine Adresse für den Testversand an',
  'Le funzioni AI non sono attive': 'Die KI-Funktionen sind nicht aktiv',

  // --- impostazioni ---
  'Settings Version': 'Version der Einstellungen',
  'Settings reset to defaults':
    'Einstellungen auf die Standardwerte zurückgesetzt',
  'Settings saved successfully!': 'Einstellungen gespeichert',
  'Size Limits': 'Größenbeschränkungen',
  'Slack Webhook URL': 'Slack-Webhook-URL',
  'Webhook URL': 'Webhook-URL',
  'Smart Suggestions': 'Intelligente Vorschläge',
  'Sort by': 'Sortieren nach',
  'Spanish': 'Spanisch',
  'Standard Departments': 'Standardabteilungen',
  'Start Time': 'Startzeit',
  'Storage Information': 'Belegter Speicherplatz',
  'Sunday': 'Sonntag',
  'System Notifications': 'Systembenachrichtigungen',
  'System Overview': 'Systemüberblick',
  'System Settings': 'Systemeinstellungen',
  'System is currently in maintenance mode':
    'Das System befindet sich im Wartungsmodus',
  'System-wide notification configuration':
    'Systemweite Konfiguration der Benachrichtigungen',
  'Timezone': 'Zeitzone',
  'Tokyo': 'Tokio',
  'Week Start Day': 'Erster Tag der Woche',
  'YYYY-MM-DD': 'JJJJ-MM-TT',
  'Templates': 'Vorlagen',
  'Template reset to default. Click Save to apply changes.':
    'Vorlage auf den Standardwert zurückgesetzt. Klicken Sie auf Speichern, um die Änderungen zu übernehmen.',
  'Use Template': 'Vorlage verwenden',
  'Type': 'Typ',
  'Title': 'Titel',
  'Subject': 'Betreff',
  'Subject Line': 'Betreffzeile',
  'Text Files': 'Textdateien',
  'Total': 'Gesamt',
  'Unsaved Changes': 'Nicht gespeicherte Änderungen',
  'Track all system changes and actions':
    'Alle Systemänderungen und Aktionen nachverfolgen',
  'Track and manage department budgets':
    'Abteilungsbudgets verfolgen und verwalten',
  'Trends': 'Entwicklung',
  'Try Again': 'Erneut versuchen',
  'Volume': 'Lautstärke',
  'Test Sounds': 'Töne testen',
  'Test notification sent!': 'Testbenachrichtigung gesendet',
  'Tests Passed': 'Bestandene Tests',

  // --- team e analisi ---
  'Team': 'Team',
  'Team Analytics': 'Auswertungen des Teams',
  'Team Analytics Report': 'Auswertungsbericht des Teams',
  'Team Feedback Board': 'Rückmeldungen des Teams',
  'Team Lead': 'Teamleitung',
  'Team Leads': 'Teamleitungen',
  'Team Member Details': 'Details des Teammitglieds',
  'Team Members': 'Teammitglieder',
  'Team Performance': 'Leistung des Teams',
  'Team Performance Overview': 'Leistungsüberblick des Teams',
  'Team member updated successfully!': 'Teammitglied aktualisiert',
  'Team members will be notified of new comments on their assigned tasks.':
    'Teammitglieder werden über neue Kommentare zu den ihnen zugewiesenen Aufgaben benachrichtigt.',
  'Team members with overdue or high-priority tasks':
    'Teammitglieder mit überfälligen Aufgaben oder Aufgaben hoher Priorität',
  'Team size distribution': 'Verteilung der Teamgrößen',
  'Top Performer': 'Bestes Ergebnis',
  'Top Performers': 'Beste Ergebnisse',
  'Top Performing': 'Mit den besten Ergebnissen',
  'Total Departments': 'Abteilungen gesamt',
  'Total Employees': 'Personen gesamt',
  'Total Feedback': 'Rückmeldungen gesamt',
  'Total Members': 'Mitglieder gesamt',
  'Total Team Members': 'Teammitglieder gesamt',
  'Total Sent': 'Insgesamt gesendet',
  'Total tasks per department': 'Aufgaben gesamt je Abteilung',
  'With Leads': 'Mit Leitung',
  'Workload Alerts': 'Hinweise zur Auslastung',
  'Workload Analysis': 'Analyse der Auslastung',
  'Workload Distribution': 'Verteilung der Auslastung',
  'Workload by Department': 'Auslastung je Abteilung',
  'Target Departments': 'Betroffene Abteilungen',
  'Task Distribution by Department': 'Verteilung der Aufgaben je Abteilung',
  'Task breakdown by team member':
    'Aufschlüsselung der Aufgaben je Teammitglied',
  'Tasks by priority level': 'Aufgaben nach Prioritätsstufe',
  'Tasks completed over the last 7 days':
    'In den letzten 7 Tagen abgeschlossene Aufgaben',
  'Tasks due within 24 hours (priority)':
    'Innerhalb von 24 Stunden fällige Aufgaben (Priorität)',
  'Task Completion Trend': 'Entwicklung der Abschlüsse',
  'Task Status Distribution': 'Verteilung der Status',
  'Super Admin Dashboard': 'Übersicht des Super-Administrators',
  'Upcoming Deadlines': 'Nächste Fristen',
  'Unassigned': 'Nicht zugewiesen',
  'Unassigned Tasks': 'Nicht zugewiesene Aufgaben',

  // --- attività, notifiche ed eventi ---
  'Task Creation': 'Erstellung von Aufgaben',
  'Task Management': 'Verwaltung der Aufgaben',
  'Task Priority Updated': 'Priorität der Aufgabe aktualisiert',
  'Task Questions': 'Fragen zu Aufgaben',
  'Task Reassigned to You': 'Aufgabe Ihnen neu zugewiesen',
  'Task Status Updated': 'Status der Aufgabe aktualisiert',
  'Task Updated': 'Aufgabe aktualisiert',
  'Task assignments and updates':
    'Zuweisungen und Aktualisierungen von Aufgaben',
  'Status changes': 'Statusänderungen',
  'This is a reminder that your task is due soon.':
    'Erinnerung: Ihre Aufgabe wird bald fällig.',
  'Your task is now overdue and requires immediate attention.':
    'Ihre Aufgabe ist überfällig und erfordert sofortige Aufmerksamkeit.',
  'This action cannot be undone. This will permanently delete the task from your workspace.':
    'Dieser Vorgang kann nicht rückgängig gemacht werden: Die Aufgabe wird endgültig gelöscht.',
  'Update the task details below.':
    'Aktualisieren Sie unten die Details der Aufgabe.',
  'Upload Attachment': 'Anhang hochladen',
  'Urgent': 'Dringend',
  'You Were Mentioned': 'Sie wurden erwähnt',
  'View Task Now': 'Jetzt öffnen',
  'View Comment': 'Kommentar ansehen',
  'View My Tasks': 'Meine Aufgaben',
  'View All Tasks': 'Alle Aufgaben',
  'View All': 'Alle ansehen',
  'View Overdue': 'Überfällige ansehen',
  'View': 'Ansehen',
  'View details & comments': 'Details und Kommentare',
  'When you have unassigned tasks, click':
    'Wenn Sie nicht zugewiesene Aufgaben haben, klicken Sie auf',

  // --- utenti e permessi ---
  'User Management': 'Benutzerverwaltung',
  'User Role': 'Benutzerrolle',
  'User account policies and defaults':
    'Regeln und Standardwerte für Benutzerkonten',
  'User data exported successfully!': 'Benutzerdaten exportiert',
  'User not loaded': 'Benutzer nicht geladen',
  'Users': 'Benutzer',
  'Users can belong to multiple departments':
    'Personen können mehreren Abteilungen angehören',
  'Users must be assigned to at least one department':
    'Jede Person muss mindestens einer Abteilung angehören',
  'Viewer': 'Nur Lesezugriff',
  'View all analytics and reports':
    'Sieht alle Auswertungen und Berichte',
  'View and update their own tasks':
    'Sieht und aktualisiert die eigenen Aufgaben',
  'View department analytics': 'Sieht die Auswertungen der Abteilung',
  'View your current role and permissions':
    'Ihre aktuelle Rolle und Ihre Berechtigungen ansehen',
  'Your Access Level': 'Ihre Zugriffsstufe',
  'You do not have permission to manage roles':
    'Sie haben keine Berechtigung, Rollen zu verwalten',
  'You do not have permission to manage user roles. Only administrators can modify roles and permissions.':
    'Sie haben keine Berechtigung, Benutzerrollen zu verwalten: Nur Administratoren können Rollen und Berechtigungen ändern.',
  'Update department information and settings':
    'Informationen und Einstellungen der Abteilung aktualisieren',
  'Update team member information':
    'Informationen des Teammitglieds aktualisieren',
  'Update Announcement': 'Ankündigung aktualisieren',
  'Use AI features': 'Nutzt die KI-Funktionen',

  // --- riscontri ---
  'Share Feedback Now': 'Jetzt Rückmeldung geben',
  'Share Your Feedback': 'Sagen Sie uns Ihre Meinung',
  'Submit Feedback': 'Rückmeldung senden',
  'Suggested Deadline': 'Vorgeschlagene Frist',
  'Suggestion applied!': 'Vorschlag angewendet',
  'Thank you for your feedback! 🎉': 'Danke für Ihre Rückmeldung',
  'Thank You for Being Part of Our Launch':
    'Danke, dass Sie beim Start dabei sind',
  'We Need Your Feedback!': 'Wir brauchen Ihre Meinung',
  'Welcome to your new team productivity platform':
    'Willkommen auf Ihrer neuen Plattform für die Teamarbeit',
  'You must be logged in to submit feedback':
    'Sie müssen angemeldet sein, um eine Rückmeldung zu senden',
  'You must be logged in to upvote':
    'Sie müssen angemeldet sein, um abzustimmen',
  'There are no active announcements for your departments':
    'Für Ihre Abteilungen gibt es keine aktiven Ankündigungen',
  'Skip Tour': 'Einführung überspringen',
  'Your Achievements': 'Ihre Ergebnisse',

  // --- aiuto ---
  'What are AI Insights?': 'Was sind KI-Analysen?',
  'What are the different user roles?': 'Welche Benutzerrollen gibt es?',
  'What can the AI Assistant do?': 'Was kann der KI-Assistent?',
  'Yes! In the analytics view, click the':
    'Ja. Klicken Sie in der Auswertungsansicht auf',
  'Yes! Open the task details dialog and go to the':
    'Ja. Öffnen Sie die Details der Aufgabe und wechseln Sie zu',
  'When enabled, task attachments will be included in notification emails':
    'Wenn aktiv, werden Anhänge von Aufgaben in die Benachrichtigungs-E-Mails eingefügt',
  'Total size of all attachments in a single email cannot exceed this limit':
    'Die Gesamtgröße aller Anhänge einer E-Mail darf diesen Wert nicht überschreiten',
  'Show notifications outside the browser':
    'Benachrichtigungen außerhalb des Browsers anzeigen',
  'Your browser does not support desktop notifications':
    'Ihr Browser unterstützt keine Desktop-Benachrichtigungen',
  'Your data is automatically saved in your browser. Use':
    'Die Daten werden automatisch gespeichert. Nutzen Sie',
  'Your data is automatically saved in your browser. Use backup to preserve data before major changes.':
    'Die Daten werden automatisch gespeichert. Erstellen Sie vor größeren Änderungen eine Sicherung.',
  'This will overwrite all existing data. Make sure to export current data first.':
    'Dieser Vorgang überschreibt alle vorhandenen Daten: Exportieren Sie zuerst die aktuellen Daten.',

  // --- errori di runtime ---
  'This spark has encountered a runtime error':
    'In der Anwendung ist ein Fehler aufgetreten',
  'Something unexpected happened while running the application. The error details are shown below. Contact the spark author and let them know about this issue.':
    'Es ist ein unerwarteter Fehler aufgetreten. Die Details finden Sie unten: Melden Sie sie der für die Anwendung zuständigen Person.',

  // --- parte 5 ---
  'My Permissions': 'Meine Berechtigungen',
  'Avg Completion Time': 'Durchschnittliche Bearbeitungszeit',
  'Avg Tasks/Employee': 'Durchschn. Aufgaben pro Person',
  'Count': 'Anzahl',
  'Low': 'Niedrig',
  'Metric': 'Kennzahl',
  'Total Assigned Tasks': 'Zugewiesene Aufgaben gesamt',
  'Value': 'Wert',
  'Generated': 'Erstellt am',
  'days': 'Tage',
  'Joined': 'Dabei seit',
  'All': 'Alle',
  'tasks': 'Aufgaben',
  'task': 'Aufgabe',
  'more': 'weitere',
  'This user has': 'Diese Person hat',
  'assigned task(s). Those tasks will become unassigned.':
    'zugewiesene Aufgaben, die danach ohne zugewiesene Person bleiben.',
  'This action cannot be undone and any assigned tasks will become unassigned.':
    'Dieser Vorgang kann nicht rückgängig gemacht werden: Zugewiesene Aufgaben bleiben ohne zugewiesene Person.',
  'active': 'aktiv',
  'inactive': 'inaktiv',
  'Feedback Board': 'Rückmeldungen',
  'Announcements': 'Ankündigungen',
  'Skills (comma-separated)': 'Fähigkeiten (durch Komma getrennt)',
  'Task created successfully!': 'Aufgabe erstellt',
  'Task updated successfully!': 'Aufgabe aktualisiert',
  'Task reassigned successfully!': 'Aufgabe neu zugewiesen',
  'Task deleted': 'Aufgabe gelöscht',
  'Task completed!': 'Aufgabe abgeschlossen',
  'Task status distribution across departments':
    'Verteilung der Status über die Abteilungen',
  'Top Clicked Links': 'Am häufigsten angeklickte Links',
  'Visual reference for department color coding and icons used throughout the app':
    'Visuelle Referenz der Farben und Symbole der Abteilungen in der Anwendung',
  'TaskFlow Help & Documentation': 'Hilfe und Dokumentation',
  'TaskFlow is Production Ready!': 'TaskFlow ist produktionsbereit',
  "Get your webhook URL from Slack's Incoming Webhooks app":
    'Die Webhook-URL finden Sie in der Slack-App Incoming Webhooks',
  'TaskFlow Analytics - Team Performance Report':
    'TaskFlow - Bericht zur Leistung des Teams',
  'TaskFlow Analytics - Department Performance Report':
    'TaskFlow - Bericht zur Leistung je Abteilung',
  '{n}% complete': '{n}% erledigt',
  '{n} tasks/user': '{n} Aufgaben pro Person',
  '{n} announcements': '{n} Ankündigungen',
  '{n} unassigned': '{n} ohne Zuweisung',
  'Last modified: {data} by {autore}': 'Zuletzt geändert: {data} von {autore}',
  'Variables': 'Variablen',
  'Note:': 'Hinweis:',
  'Email notifications are sent when enabled in user notification preferences. Variables will be automatically replaced with actual values when emails are sent.': 
    'Benachrichtigungs-E-Mails werden nur versendet, wenn sie in den Benachrichtigungseinstellungen der Person aktiviert sind. Variablen werden beim Versand automatisch durch die tatsächlichen Werte ersetzt.',
  'Mention a teammate': 'Teammitglied erwähnen',
  'Use the arrow keys to choose, Enter to confirm, Esc to close': 'Pfeiltasten zum Auswählen, Enter zum Bestätigen, Esc zum Schließen',
  'Press Cmd+Enter to post. Type @ to mention a teammate': 'Cmd+Enter zum Absenden. @ eingeben, um jemanden zu erwähnen',
  'This attachment was blocked because its format is not allowed': 'Anhang blockiert: Dieses Format ist nicht zulässig',
  'Edit comment': 'Kommentar bearbeiten',
  'Delete comment': 'Kommentar löschen',
  'Post comment': 'Kommentar absenden',
  'Download attachment': 'Anhang herunterladen',
  'Delete attachment': 'Anhang löschen',
  'AI Service': 'KI-Dienst',
  'Available': 'Verfügbar',
  'Unavailable': 'Nicht verfügbar',
  'Checking...': 'Wird geprüft...',
  'Shown in the application header and used in notification emails.': 'Erscheint in der Kopfzeile und in den Benachrichtigungs-E-Mails.',
  'Notifications ({count} unread)': 'Benachrichtigungen ({count} ungelesen)',
  'Delete notification': 'Benachrichtigung löschen',
  'Edit task': 'Aufgabe bearbeiten',
  'Delete task': 'Aufgabe löschen',
  'Select task': 'Aufgabe auswählen',
  'Select {name}': '{name} auswählen',
  'Skip tour': 'Einführung überspringen',
  'tasks shown': 'Aufgaben angezeigt',
  'Show more tasks': 'Weitere Aufgaben anzeigen',
  'Calendar': 'Kalender',
  'Previous month': 'Vorheriger Monat',
  'Next month': 'Nächster Monat',
  'Today': 'Heute',
  'Selected day': 'Ausgewählter Tag',
  'Priority: {priority}': 'Priorität: {priority}',
  'Tasks by due date for {month}': 'Aufgaben nach Fälligkeit für {month}',
  '+{count} more': '+{count} weitere',
  '{count} tasks': '{count} Aufgaben',
  '{count} overdue': '{count} überfällig',
  '{count} scheduled this month': '{count} in diesem Monat geplant',
  '{count} tasks have no due date and are not shown here': '{count} Aufgaben haben kein Fälligkeitsdatum und erscheinen hier nicht',
  'Every task has a due date': 'Alle Aufgaben haben ein Fälligkeitsdatum',
  'Nothing due on this day': 'An diesem Tag ist nichts fällig',
  'Nothing is due this month': 'In diesem Monat ist nichts fällig',
  'Repeat': 'Wiederholen',
  'Does not repeat': 'Wiederholt sich nicht',
  'Daily': 'Täglich',
  'Weekly': 'Wöchentlich',
  'Monthly': 'Monatlich',
  'Repeat every': 'Wiederholen alle',
  'weeks': 'Wochen',
  'months': 'Monate',
  'Repeat on': 'Wiederholen an',
  'Leave empty to repeat on the same weekday.': 'Leer lassen, um am selben Wochentag zu wiederholen.',
  'End date (optional)': 'Enddatum (optional)',
  'No end date': 'Kein Enddatum',
  'Remove end date': 'Enddatum entfernen',
  'Mon': 'Mo',
  'Tue': 'Di',
  'Wed': 'Mi',
  'Thu': 'Do',
  'Fri': 'Fr',
  'Sat': 'Sa',
  'Sun': 'So',
  'Tuesday': 'Dienstag',
  'Wednesday': 'Mittwoch',
  'Thursday': 'Donnerstag',
  'Friday': 'Freitag',
  'Saturday': 'Samstag',
  'Daily summary instead of immediate emails': 'Tageszusammenfassung statt sofortiger E-Mails',
  'One email a day with the notifications you have not read, instead of one email for every event': 'Eine E-Mail pro Tag mit den ungelesenen Benachrichtigungen statt einer E-Mail pro Ereignis',
  'Summary time': 'Uhrzeit der Zusammenfassung',
  'Times are in your timezone: {zone}': 'Die Zeiten gelten in Ihrer Zeitzone: {zone}',
  'If there is nothing new, no email is sent. In-app notifications stay immediate.': 'Wenn es nichts Neues gibt, wird keine E-Mail versendet. Benachrichtigungen in der Anwendung bleiben sofort.',
  'Daily summary enabled: one email per day instead of one per event': 'Tageszusammenfassung aktiv: eine E-Mail pro Tag statt einer pro Ereignis',
  'Immediate emails enabled: one email per event': 'Sofortige E-Mails aktiv: eine E-Mail pro Ereignis',
  'No due date': 'Kein Fälligkeitsdatum',
  'Blocked': 'Blockiert',
  'Labels': 'Labels',
  'Search or add a label': 'Label suchen oder hinzufügen',
  'Create label "{name}"': 'Label "{name}" erstellen',
  'Remove label {name}': 'Label {name} entfernen',
  'Label {name} added': 'Label {name} hinzugefügt',
  'Label {name} removed': 'Label {name} entfernt',
  'Label suggestions': 'Vorgeschlagene Labels',
  'No matching label in use — type to create one': 'Kein passendes Label in Verwendung — tippen, um es zu erstellen',
  'Labels are saved in lowercase so the same one is never created twice.': 'Labels werden kleingeschrieben gespeichert, damit dasselbe Label nicht zweimal entsteht.',
  'Similar labels already exist. Reusing one keeps filters useful.': 'Es gibt bereits ähnliche Labels. Eines davon wiederzuverwenden hält Filter nützlich.',
  'Watchers': 'Beobachter',
  'Add someone who should follow this task': 'Jemanden hinzufügen, der diese Aufgabe verfolgen soll',
  'Nobody follows this task yet': 'Noch niemand verfolgt diese Aufgabe',
  'People who can follow this task': 'Wer diese Aufgabe verfolgen kann',
  'No one else to add': 'Niemand mehr zum Hinzufügen',
  'No people to show': 'Keine Personen anzuzeigen',
  'Follow this task': 'Diese Aufgabe verfolgen',
  'Following this task': 'Verfolgt diese Aufgabe',
  'Remove {name} from watchers': '{name} aus den Beobachtern entfernen',
  '{name} now follows this task': '{name} verfolgt diese Aufgabe jetzt',
  '{name} no longer follows this task': '{name} verfolgt diese Aufgabe nicht mehr',
  'You are assigned to this task, so you already get every update.': 'Diese Aufgabe ist Ihnen zugewiesen, Sie erhalten also bereits jede Aktualisierung.',
  '(you)': '(Sie)',
  'Unknown user': 'Unbekannter Benutzer',
  'Removed member': 'Entferntes Mitglied',
  'Estimated time': 'Geschätzte Zeit',
  'Time spent': 'Aufgewendete Zeit',
  'Estimated': 'Geschätzt',
  'No estimate': 'Keine Schätzung',
  'Understood as': 'Verstanden als',
  'Not understood. Try 90, 1.5h or 2h 30m.': 'Nicht verstanden. Versuchen Sie 90, 1.5h oder 2h 30m.',
  'Leave empty if you cannot estimate it yet': 'Leer lassen, wenn noch keine Schätzung möglich ist',
  'Leave empty if not tracked': 'Leer lassen, wenn nicht erfasst',
  'Leave empty if unknown': 'Leer lassen, wenn unbekannt',
  'Same as the estimate': 'Wie die Schätzung',
  '{tempo} over the estimate': '{tempo} über der Schätzung',
  '{tempo} under the estimate': '{tempo} unter der Schätzung',
  'at least {tempo}': 'mindestens {tempo}',
  'Export Tasks': 'Aufgaben exportieren',
  'Choose the format, the columns and which tasks to include.': 'Wählen Sie Format, Spalten und die einzuschließenden Aufgaben.',
  'Format': 'Format',
  'Columns': 'Spalten',
  'Which tasks': 'Welche Aufgaben',
  'Only the filtered tasks': 'Nur die gefilterten Aufgaben',
  'All tasks, including archived ones': 'Alle Aufgaben, auch archivierte',
  'Select at least one column': 'Wählen Sie mindestens eine Spalte',
  '{righe} rows will be exported': '{righe} Zeilen werden exportiert',
  'Export failed': 'Export fehlgeschlagen',
  'Allow pop-ups to export the PDF': 'Pop-ups zulassen, um das PDF zu exportieren',
  'Please allow pop-ups to download PDF': 'Pop-ups zulassen, um das PDF herunterzuladen',
  'Task List': 'Aufgabenliste',
  'Person': 'Person',
  'Open': 'Offen',
  'Saved filters': 'Gespeicherte Filter',
  'Save current filters': 'Aktuelle Filter speichern',
  'Current filters are already saved': 'Die aktuellen Filter sind bereits gespeichert',
  'Name of this view': 'Name dieser Ansicht',
  'Rename this view': 'Diese Ansicht umbenennen',
  'Rename "{nome}"': '"{nome}" umbenennen',
  'Delete "{nome}"': '"{nome}" löschen',
  'Delete this saved filter?': 'Diesen gespeicherten Filter löschen?',
  '"{nome}" will be removed. The tasks are not affected.': '"{nome}" wird entfernt. Die Aufgaben bleiben unberührt.',
  'Set some filters above, then save them here': 'Setzen Sie oben Filter und speichern Sie sie hier',
  'Save the filters you use often — status, priority, department, assignee — and bring them back with one click.': 'Speichern Sie häufig genutzte Filter — Status, Priorität, Abteilung, Zuständige — und holen Sie sie mit einem Klick zurück.',
  'Search: {testo}': 'Suche: {testo}',
  'Clear All': 'Alles zurücksetzen',
  'Workload': 'Arbeitslast',
  'Open tasks per person, and how much of that work has an estimate.': 'Offene Aufgaben pro Person und wie viel davon geschätzt ist.',
  'All {totale} open tasks have an estimate.': 'Alle {totale} offenen Aufgaben haben eine Schätzung.',
  '{senza} of {totale} open tasks have no estimate: that part of the workload is unknown.': '{senza} von {totale} offenen Aufgaben haben keine Schätzung: dieser Teil der Last ist unbekannt.',
  'Remove due date': 'Fälligkeitsdatum entfernen',
  'Please enter a task title': 'Geben Sie einen Aufgabentitel ein',
  'Task Title': 'Titel',
  '"Create a task for the upcoming product launch"': '„Erstelle eine Aufgabe für den Produktstart“',
  '"How can I balance the workload across my team?"': '„Wie kann ich die Arbeitslast in meinem Team besser verteilen?“',
  '"Which tasks should I prioritize this week?"': '„Welche Aufgaben sollte ich diese Woche zuerst angehen?“',
  '1 day': '1 Tag',
  '1 day ago': 'vor 1 Tag',
  '1. Click "{label}" in the header': '1. Klicke in der Kopfzeile auf „{label}“',
  '1. Click the "{label}" button in the header': '1. Klicke in der Kopfzeile auf die Schaltfläche „{label}“',
  '1. Navigate to the "{label}" tab': '1. Wechsle zum Reiter „{label}“',
  '100% Tests Passed': '100 % der Tests bestanden',
  '150+ Features Built': 'Über 150 Funktionen umgesetzt',
  '2. Check the boxes next to tasks you want to modify': '2. Setze die Häkchen bei den Aufgaben, die du ändern willst',
  '2. Click "{label}"': '2. Klicke auf „{label}“',
  '2. Fill in the task details:': '2. Fülle die Angaben zur Aufgabe aus:',
  '2. Type your comment in the text field': '2. Schreibe deinen Kommentar in das Textfeld',
  '3. Choose an action:': '3. Wähle eine Aktion:',
  '3. Click "{label}"': '3. Klicke auf „{label}“',
  '3. Click "{label}" to save': '3. Klicke auf „{label}“, um zu speichern',
  '3. Enter their information:': '3. Gib die Daten der Person ein:',
  '81 Iterations Completed': '81 Iterationen abgeschlossen',
  'AI': 'KI',
  'AI Insights appear in the Analytics view and provide:': 'Die KI-Analysen erscheinen in der Analyseansicht und bieten:',
  'AI Integration Active': 'KI-Integration aktiv',
  'AI assistant': 'KI-Assistent',
  'AI insights': 'KI-Analysen',
  'AI-Powered Features': 'Funktionen mit KI',
  'Actionable Suggestions:': 'Umsetzbare Vorschläge:',
  'Actionable suggestions to improve workflow': 'Konkrete Vorschläge, um den Arbeitsablauf zu verbessern',
  'Active: {active} • Done: {done}': 'Laufend: {active} • Erledigt: {done}',
  'Activity ({count})': 'Verlauf ({count})',
  'Add': 'Hinzufügen',
  'Add Comment': 'Kommentar hinzufügen',
  'Add and organize team members': 'Teammitglieder hinzufügen und organisieren',
  'Add comments': 'Kommentare hinzufügen',
  'Add employees': 'Mitarbeitende hinzufügen',
  'Add new employees': 'Neue Mitarbeitende hinzufügen',
  'Admin, Manager, or Member': 'Administrator, Manager oder Mitglied',
  'All ({count})': 'Alle ({count})',
  'All analytics': 'Alle Analysen',
  'All caught up! 🎉': 'Alles erledigt! 🎉',
  'All departments on track! 🎉': 'Alle Abteilungen liegen im Plan! 🎉',
  'All existing departments will be replaced with {count} new ones': 'Die bisherigen Abteilungen werden durch {count} neue ersetzt',
  'Are you sure you want to clear all audit log entries? This cannot be undone.': 'Willst du das Prüfprotokoll wirklich leeren? Das lässt sich nicht rückgängig machen.',
  'Are you sure you want to delete this comment?': 'Willst du diesen Kommentar wirklich löschen?',
  'Are you sure you want to remove {count} team members from your team?': 'Willst du wirklich {count} Personen aus dem Team entfernen?',
  'Are you sure you want to remove {name} from your team?': 'Willst du {name} wirklich aus dem Team entfernen?',
  'Are you sure you want to reset all settings to default values? This cannot be undone.': 'Willst du wirklich alle Einstellungen auf die Standardwerte zurücksetzen? Das lässt sich nicht rückgängig machen.',
  'Ask about specific tasks or team status': 'Frage nach einzelnen Aufgaben oder dem Stand des Teams',
  'Assign departments to {count} users': 'Abteilungen für {count} Personen zuweisen',
  'Assign tasks': 'Aufgaben zuweisen',
  'Assign tasks to others': 'Aufgaben an andere zuweisen',
  'Assign to:': 'Zuweisen an:',
  'Assigned to {name}': '{name} zugewiesen',
  'Attach File': 'Datei anhängen',
  'Attach files': 'Dateien anhängen',
  'Attach files to tasks': 'Dateien an Aufgaben anhängen',
  'Attachments': 'Anhänge',
  'Attachments ({count})': 'Anhänge ({count})',
  'Auto-assign': 'Automatische Zuweisung',
  'Automated recommendations and trend analysis': 'Automatische Empfehlungen und Trendanalyse',
  'Bio': 'Kurzprofil',
  'Brand identity and creative direction': 'Markenidentität und Kreativleitung',
  'Brand strategy, campaigns, and growth marketing': 'Markenstrategie, Kampagnen und Wachstumsmarketing',
  'Brief description of the task': 'Kurze Beschreibung der Aufgabe',
  'Bright ascending chime': 'Heller aufsteigender Klang',
  'Budget: {amount}': 'Budget: {amount}',
  'Bulk Select': 'Mehrfachauswahl',
  'Bulk operations': 'Sammelaktionen',
  'Business': 'Betriebswirtschaft',
  'Business operations and process management': 'Geschäftsabläufe und Prozessmanagement',
  'Celebratory ascending chime': 'Festlicher aufsteigender Klang',
  'Change status': 'Status ändern',
  'Change task status': 'Status von Aufgaben ändern',
  'Check browser console for errors': 'Browser-Konsole auf Fehler prüfen',
  'Clear Audit Log ({count} entries)': 'Protokoll leeren ({count} Einträge)',
  'Click "Add Task" to create new tasks. Assign them to team members, set priorities, due dates, and track status. Use bulk operations to manage multiple tasks at once.': 'Klicke auf „Aufgabe hinzufügen“, um neue Aufgaben anzulegen. Weise sie Teammitgliedern zu, lege Prioritäten und Fristen fest und verfolge den Status. Mit Sammelaktionen bearbeitest du mehrere auf einmal.',
  'Click "Enable Notifications" to receive desktop alerts.': 'Klicke auf „Benachrichtigungen aktivieren“, um Hinweise auf dem Desktop zu erhalten.',
  'Click "Publish" in Spark UI': 'In der Spark-Oberfläche auf „Publish“ klicken',
  'Click "{label}" in the header to start chatting!': 'Klicke in der Kopfzeile auf „{label}“ und leg los.',
  'Click "{label}" to upload documents, images, or other files (max 10MB per file).': 'Klicke auf „{label}“, um Dokumente, Bilder oder andere Dateien hochzuladen (höchstens 10 MB pro Datei).',
  'Click on any task card to open the details dialog, then:': 'Klicke auf eine Karte, um die Aufgabendetails zu öffnen, dann:',
  'Click the "{label}" button in the header to view:': 'Klicke in der Kopfzeile auf die Schaltfläche „{label}“, um Folgendes zu sehen:',
  'Click the "{label}" button to:': 'Klicke auf die Schaltfläche „{label}“, um:',
  'Click the edit icon (pencil) on any task card, make your changes, and click "{label}".': 'Klicke auf einer Karte auf das Stiftsymbol, nimm deine Änderungen vor und klicke auf „{label}“.',
  'Client acquisition and revenue generation': 'Kundengewinnung und Umsatzsteigerung',
  'Client relationships and support services': 'Kundenbeziehungen und Supportleistungen',
  'Comment on tasks': 'Aufgaben kommentieren',
  'Comments': 'Kommentare',
  'Comments ({count})': 'Kommentare ({count})',
  'Common departments:': 'Häufige Abteilungen:',
  'Complete these final steps before going live:': 'Erledige diese letzten Schritte vor dem Start:',
  'Completed: {done} • Rate: {rate}%': 'Erledigt: {done} • Quote: {rate} %',
  'Completion rates, workload distribution, task trends': 'Abschlussquoten, Verteilung der Arbeitslast, Aufgabentrends',
  'Confidence: {level}': 'Zuverlässigkeit: {level}',
  'Configure access level and permissions for {name}': 'Zugriffsebene und Berechtigungen von {name} festlegen',
  'Configure your notification preferences by clicking the bell icon in the header. You can customize which events trigger notifications, set quiet hours, and choose notification sounds.': 'Stelle deine Einstellungen über das Glockensymbol in der Kopfzeile ein. Du kannst festlegen, welche Ereignisse eine Benachrichtigung auslösen, Ruhezeiten definieren und Töne auswählen.',
  'Contact email': 'Kontakt-E-Mail',
  'Content creation, writing, and editorial': 'Content-Erstellung, Texten und Redaktion',
  'Content of a comment': 'Inhalt eines Kommentars',
  'Create': 'Erstellen',
  'Create All ({count})': 'Alle erstellen ({count})',
  'Create and Assign Tasks': 'Aufgaben erstellen und zuweisen',
  'Create new tasks': 'Neue Aufgaben erstellen',
  'Create, assign, and track tasks efficiently': 'Aufgaben erstellen, zuweisen und im Blick behalten',
  'Created {count} departments from the {category} template': '{count} Abteilungen aus der Vorlage {category} erstellt',
  'Creative': 'Kreativ',
  'Current date': 'Aktuelles Datum',
  'Current status of the task': 'Aktueller Status der Aufgabe',
  'Current year': 'Aktuelles Jahr',
  'Data analysis, machine learning, and analytics': 'Datenanalyse, maschinelles Lernen und Auswertungen',
  'Date when the action occurred': 'Datum, an dem die Aktion stattfand',
  'Delete announcements': 'Ankündigungen löschen',
  'Delete any task': 'Beliebige Aufgaben löschen',
  'Delete employees': 'Mitarbeitende löschen',
  'Delete own tasks': 'Eigene Aufgaben löschen',
  'Delete {count} users?': '{count} Benutzer löschen?',
  'Department "{name}" already exists': 'Die Abteilung „{name}“ gibt es bereits',
  'Department "{name}" archived': 'Abteilung „{name}“ archiviert',
  'Department "{name}" created successfully!': 'Abteilung „{name}“ erstellt',
  'Department "{name}" deleted successfully': 'Abteilung „{name}“ gelöscht',
  'Department "{name}" restored': 'Abteilung „{name}“ wiederhergestellt',
  'Department "{name}" updated successfully!': 'Abteilung „{name}“ aktualisiert',
  'Department Name *': 'Name der Abteilung *',
  'Department-specific metrics and comparisons': 'Kennzahlen und Vergleiche je Abteilung',
  'Departments added to {users} users: {departments} in total': 'Abteilungen für {users} Personen ergänzt: {departments} insgesamt',
  'Departments available: {count}': 'Verfügbare Abteilungen: {count}',
  'Departments replaced for {users} users: {departments} in total': 'Abteilungen für {users} Personen ersetzt: {departments} insgesamt',
  'Descending alert': 'Absteigender Warnton',
  'Describe a task naturally and AI will create it': 'Beschreibe eine Aufgabe in eigenen Worten und die KI legt sie an',
  'Description of the task': 'Beschreibung der Aufgabe',
  'Desktop': 'Computer',
  'Desktop notifications are blocked. Check your browser settings to enable them.': 'Desktop-Benachrichtigungen sind blockiert. Prüfe die Einstellungen deines Browsers, um sie zu erlauben.',
  'Desktop notifications are enabled and working.': 'Desktop-Benachrichtigungen sind aktiv und funktionieren.',
  'Detailed information (optional)': 'Ausführliche Angaben (optional)',
  'Due Soon': 'Bald fällig',
  'Due date of the task': 'Fälligkeitsdatum der Aufgabe',
  'Due {when}': 'Fällig {when}',
  'Early Bird (9 PM - 6 AM)': 'Frühaufsteher (21:00 - 06:00)',
  'Edit announcements': 'Ankündigungen bearbeiten',
  'Edit any task': 'Beliebige Aufgaben bearbeiten',
  'Edit employee details': 'Daten von Mitarbeitenden bearbeiten',
  'Edit employees': 'Mitarbeitende bearbeiten',
  'Edit own tasks': 'Eigene Aufgaben bearbeiten',
  'Efficiency': 'Effizienz',
  'Email Address *': 'E-Mail-Adresse *',
  'Email address of the recipient': 'E-Mail-Adresse der empfangenden Person',
  'Employee Management': 'Personalverwaltung',
  'Employees: {count}': 'Personen: {count}',
  'Enable Quiet Hours': 'Ruhezeiten aktivieren',
  'Enable Sounds': 'Töne aktivieren',
  'Existing departments: {list}': 'Vorhandene Abteilungen: {list}',
  'Expires {date}': 'Läuft am {date} ab',
  'Export data backup': 'Datensicherung exportieren',
  'Failed to generate assignments': 'Die Zuweisungen konnten nicht erstellt werden',
  'Failed to get AI response': 'Von der KI kam keine Antwort',
  'Financial planning, accounting, and reporting': 'Finanzplanung, Buchhaltung und Berichtswesen',
  'Flag urgent overdue tasks': 'Weist auf dringende überfällige Aufgaben hin',
  'Formatted report with charts': 'Formatierter Bericht mit Diagrammen',
  "From concept to production in 81 iterations. That's persistence!": 'Von der Idee bis zur Produktion in 81 Iterationen – das nennt man Ausdauer!',
  'Full Name *': 'Vor- und Nachname *',
  'Full name': 'Vor- und Nachname',
  'Gentle ascending tone': 'Sanfter aufsteigender Ton',
  'Get AI insights': 'KI-Analysen abrufen',
  'Get AI task estimates': 'KI-Schätzungen für Aufgaben abrufen',
  'Get Started': "Los geht's",
  'Get recommendations for task reassignment or priority changes': 'Erhalte Vorschläge, um Aufgaben neu zuzuweisen oder Prioritäten zu ändern',
  'High double ping': 'Hoher Doppelton',
  'High, Medium, or Low': 'Hoch, mittel oder niedrig',
  'I apologize, but I encountered an error processing your request: {message}': 'Entschuldige, bei der Bearbeitung deiner Anfrage ist ein Fehler aufgetreten: {message}',
  'Identify overloaded team members': 'Erkennt überlastete Teammitglieder',
  'Identify overworked team members': 'Erkennt überarbeitete Teammitglieder',
  'Importing...': 'Import läuft...',
  'Information security and cybersecurity operations': 'Informationssicherheit und Cybersicherheit',
  'Infrastructure, deployment, and system operations': 'Infrastruktur, Deployment und Systembetrieb',
  'Job Title *': 'Position *',
  'Job title or position': 'Berufsbezeichnung oder Position',
  'John Doe': 'Max Mustermann',
  'Joined Date': 'Eintrittsdatum',
  'LAUNCH_CELEBRATION.md - Celebration & stats': 'LAUNCH_CELEBRATION.md - Feier und Zahlen',
  'LAUNCH_READINESS_REPORT.md - Full audit': 'LAUNCH_READINESS_REPORT.md - Vollständige Prüfung',
  'Lead: {name}': 'Leitung: {name}',
  'Legal compliance and contract management': 'Rechtliche Compliance und Vertragsmanagement',
  "Let's Launch! 🚀": "Auf geht's! 🚀",
  'Link to view the task': 'Link zum Öffnen der Aufgabe',
  'Manage Your Team': 'Verwalte dein Team',
  'Manage roles': 'Rollen verwalten',
  'Manage user roles and permissions': 'Rollen und Berechtigungen der Benutzer verwalten',
  'Managing: {departments}': 'Von dir verwaltete Abteilungen: {departments}',
  'Mark all as completed': 'Alle als erledigt markieren',
  'Mentions': 'Erwähnungen',
  'Mobile': 'Smartphone',
  'Monitor team analytics': 'Behalte die Team-Analysen im Blick',
  'N/A': 'k. A.',
  'Name of the application': 'Name der Anwendung',
  'Name of the company': 'Name des Unternehmens',
  'Name of the email recipient': 'Name der empfangenden Person',
  'Name of the person assigned': 'Name der zugewiesenen Person',
  'Name of the person who performed the action': 'Name der Person, die die Aktion ausgeführt hat',
  'New': 'Neu',
  'New comment added': 'Neuer Kommentar hinzugefügt',
  'Night Owl (12 AM - 10 AM)': 'Nachteule (00:00 - 10:00)',
  'No': 'Nein',
  'No data': 'Keine Daten',
  'Notification Preferences': 'Benachrichtigungseinstellungen',
  'Out of {count} total': 'Von insgesamt {count}',
  'PRODUCTION_DEPLOYMENT.md - Deployment guide': 'PRODUCTION_DEPLOYMENT.md - Anleitung zum Deployment',
  'Perform bulk operations': 'Sammelaktionen ausführen',
  'Personal analytics': 'Persönliche Analysen',
  'Phone': 'Telefon',
  'Playing {sound}': 'Wiedergabe: {sound}',
  'Preview: This color will be auto-assigned based on the department name': 'Vorschau: Diese Farbe wird automatisch anhand des Abteilungsnamens vergeben',
  'Priority Changed': 'Priorität geändert',
  'Priority changed to {priority}': 'Priorität auf {priority} geändert',
  'Priority level of the task': 'Prioritätsstufe der Aufgabe',
  'Product strategy and user experience design': 'Produktstrategie und Gestaltung der Nutzererfahrung',
  'Production Ready': 'Bereit für den Produktivbetrieb',
  'Quality assurance and software testing': 'Qualitätssicherung und Softwaretests',
  'Quick double chirp': 'Schneller Doppelton',
  'Quick select existing departments:': 'Schnellauswahl aus den vorhandenen Abteilungen:',
  'Quiet hours disabled': 'Ruhezeiten deaktiviert',
  'Quiet hours enabled - notifications paused during sleep times': 'Ruhezeiten aktiv: Benachrichtigungen pausieren während der Ruhephase',
  'Quiet hours set: {preset}': 'Ruhezeiten festgelegt: {preset}',
  'Raw data for further analysis': 'Rohdaten für weitere Auswertungen',
  'Remove all selected tasks': 'Alle ausgewählten Aufgaben entfernen',
  'Remove employees': 'Mitarbeitende entfernen',
  'Reset all to not-started': 'Alle auf „Nicht begonnen“ zurücksetzen',
  'Rising alert tone': 'Ansteigender Warnton',
  'Run final smoke test (30 minutes)': 'Letzten Smoke-Test durchführen (30 Minuten)',
  'Saving…': 'Wird gespeichert…',
  'Security Hardened': 'Sicherheit gehärtet',
  'Select at least one department to continue': 'Wähle mindestens eine Abteilung aus, um fortzufahren',
  "Selected departments will be added to each user's current departments": 'Die gewählten Abteilungen kommen zu den bisherigen jeder Person hinzu',
  'Selected departments will replace all current departments for each user': 'Die gewählten Abteilungen ersetzen alle bisherigen jeder Person',
  'Selected users: {count}': 'Ausgewählte Personen: {count}',
  'Set all to in-progress': 'Alle auf „In Bearbeitung“ setzen',
  'Share URL with your team': 'Adresse mit deinem Team teilen',
  'Single soft ping': 'Einzelner sanfter Ton',
  'Skills': 'Fähigkeiten',
  'Sleep Time (10 PM - 7 AM)': 'Schlafenszeit (22:00 - 07:00)',
  'Smart suggestions and automated workflows': 'Intelligente Vorschläge und automatisierte Abläufe',
  'Smart task management': 'Intelligente Aufgabenverwaltung',
  'Social media management and community engagement': 'Social-Media-Betreuung und Community-Arbeit',
  'Software development and technical implementation': 'Softwareentwicklung und technische Umsetzung',
  'Spot trends in completion rates': 'Erkennt Trends bei den Abschlussquoten',
  'Start by adding your team members. Click the "Users" button in the header to add employees, assign departments, and set roles (Admin, Manager, or Member).': 'Füge zuerst deine Teammitglieder hinzu. Klicke in der Kopfzeile auf „Benutzer“, um Personen anzulegen, Abteilungen zuzuweisen und Rollen festzulegen (Administrator, Manager oder Mitglied).',
  'Status Changed': 'Status geändert',
  'Status changed to {status}': 'Status auf {status} geändert',
  'Switch to the Analytics view to see team performance metrics, workload distribution, and department insights. Export reports as PDF or CSV.': 'Wechsle zur Analyseansicht, um Teamleistung, Verteilung der Arbeitslast und Abteilungsdaten zu sehen. Berichte lassen sich als PDF oder CSV exportieren.',
  'Tablet': 'Tablet',
  'Talent management and employee relations': 'Talentmanagement und Mitarbeiterbeziehungen',
  'Task Assigned': 'Aufgabe zugewiesen',
  'Task Completed': 'Aufgabe abgeschlossen',
  'Task Reassigned': 'Aufgabe neu zugewiesen',
  'Task created': 'Aufgabe erstellt',
  'Task estimates': 'Aufgabenschätzungen',
  'Task updated': 'Aufgabe aktualisiert',
  'Tasks assigned: {count}': 'Zugewiesene Aufgaben: {count}',
  'Tasks: {count}': 'Aufgaben: {count}',
  'Tasks: {done}/{total}': 'Aufgaben: {done}/{total}',
  'Team Collaboration': 'Zusammenarbeit im Team',
  'Team analytics': 'Team-Analysen',
  'Team member responsible': 'Teammitglied, das sich darum kümmert',
  'Team members: {count}': 'Teammitglieder: {count}',
  'Team members: {members} · Tasks: {tasks}': 'Teammitglieder: {members} · Aufgaben: {tasks}',
  'Technical support and system maintenance': 'Technischer Support und Systemwartung',
  'Technology': 'Technik',
  'Template applied! Review and create "{name}"': 'Vorlage übernommen: Prüfe die Angaben und lege „{name}“ an',
  'Test on mobile device': 'Auf einem Mobilgerät testen',
  'The AI Assistant helps you with:': 'Der KI-Assistent hilft dir bei:',
  'The departments in the {category} template already exist': 'Die Abteilungen der Vorlage {category} gibt es bereits',
  'This department cannot be archived: it still has {count} assigned people': 'Diese Abteilung lässt sich nicht archivieren: Ihr sind noch {count} Personen zugeordnet',
  'This department cannot be deleted: it still has {count} assigned people': 'Diese Abteilung lässt sich nicht löschen: Ihr sind noch {count} Personen zugeordnet',
  'This is a test notification from TaskFlow!': 'Das ist eine Testbenachrichtigung von TaskFlow.',
  'This user has {count} assigned tasks. Those tasks will become unassigned.': 'Dieser Person sind {count} Aufgaben zugewiesen; sie bleiben danach ohne zuständige Person.',
  'This will permanently delete "{name}". This action cannot be undone.': '„{name}“ wird endgültig gelöscht. Das lässt sich nicht rückgängig machen.',
  'Three warning tones': 'Drei Warntöne',
  'Tips for great feedback:': 'Tipps für nützliches Feedback:',
  'Title of the task': 'Titel der Aufgabe',
  'Total clicks: {count}': 'Klicks insgesamt: {count}',
  'Total tasks: {count}': 'Aufgaben insgesamt: {count}',
  'Track Performance': 'Behalte die Leistung im Blick',
  'Try asking:': 'Frag zum Beispiel:',
  'Two-tone notification': 'Zweitöniger Hinweis',
  'Type of action performed': 'Art der ausgeführten Aktion',
  'UI/UX design and visual design work': 'Gestaltung von Oberflächen, Nutzererfahrung und Grafik',
  'Unique: {count}': 'Eindeutig: {count}',
  'Unknown': 'Unbekannt',
  'Unread ({count})': 'Ungelesen ({count})',
  'Updated {time}': 'Aktualisiert um {time}',
  'Use AI Assistant for intelligent task suggestions, auto-assignment based on workload, and insights about team performance and bottlenecks.': 'Nutze den KI-Assistenten für Aufgabenvorschläge, die automatische Zuweisung nach Arbeitslast und Erkenntnisse zu Leistung und Engpässen im Team.',
  'Use AI assistant': 'KI-Assistenten nutzen',
  'Use AI auto-assign': 'Automatische KI-Zuweisung nutzen',
  'Users affected: {count}': 'Betroffene Personen: {count}',
  'Users removed: {count}': 'Entfernte Personen: {count}',
  'Verify all critical paths working': 'Prüfen, ob die kritischen Abläufe funktionieren',
  'Video creation, editing, and multimedia': 'Videoproduktion, Schnitt und Multimedia',
  'View all tasks': 'Alle Aufgaben sehen',
  'View announcements': 'Ankündigungen sehen',
  'View employee list': 'Liste der Mitarbeitenden sehen',
  'View employees': 'Mitarbeitende sehen',
  'View organization analytics': 'Analysen der Organisation sehen',
  'View own tasks': 'Eigene Aufgaben sehen',
  'View personal analytics': 'Persönliche Analysen sehen',
  'View team analytics': 'Team-Analysen sehen',
  'View team tasks': 'Aufgaben des Teams sehen',
  'Visualize team performance and insights': 'Sieh dir die Teamleistung und die Auswertungen an',
  'Warning:': 'Achtung:',
  'Warning: this department has {count} assigned people.': 'Achtung: Dieser Abteilung sind {count} Personen zugeordnet.',
  "We'll notify you when something important happens": 'Wir sagen dir Bescheid, sobald etwas Wichtiges passiert',
  "We've built TaskFlow to help teams work smarter, collaborate better, and achieve more together. Your feedback during this launch phase is invaluable and will help us shape the future of this platform.": 'Wir haben TaskFlow gebaut, damit Teams besser arbeiten, enger zusammenarbeiten und gemeinsam mehr erreichen. In dieser Startphase ist deine Rückmeldung besonders wertvoll und hilft uns, die Plattform weiterzuentwickeln.',
  'Welcome back, {name}!': 'Willkommen zurück, {name}!',
  'Welcome to TaskFlow! 🎉': 'Willkommen bei TaskFlow! 🎉',
  'When a task becomes overdue': 'Wenn eine Aufgabe überfällig wird',
  'When a task is assigned to you': 'Wenn dir eine Aufgabe zugewiesen wird',
  'When a task is due within 24 hours': 'Wenn eine Aufgabe innerhalb von 24 Stunden fällig wird',
  'When a task is marked as complete': 'Wenn eine Aufgabe als erledigt markiert wird',
  'When a task is reassigned to you': 'Wenn dir eine Aufgabe neu zugewiesen wird',
  'When someone comments on your task': 'Wenn jemand eine deiner Aufgaben kommentiert',
  'When task details are modified': 'Wenn sich die Angaben einer Aufgabe ändern',
  'When task priority is modified': 'Wenn sich die Priorität einer Aufgabe ändert',
  'When task status is updated': 'Wenn sich der Status einer Aufgabe ändert',
  'When the task should be completed': 'Bis wann die Aufgabe erledigt sein soll',
  'When you are mentioned in comments': 'Wenn du in einem Kommentar erwähnt wirst',
  'When you have unassigned tasks, click "{label}" to:': 'Wenn Aufgaben niemandem zugewiesen sind, klicke auf „{label}“, um:',
  'Which teams they belong to': 'Zu welchen Teams die Person gehört',
  'Work together with departments and roles': 'Arbeitet zusammen – nach Abteilungen und Rollen',
  'Working Hours (6 PM - 9 AM)': 'Außerhalb der Arbeitszeit (18:00 - 09:00)',
  'Yes': 'Ja',
  'Yes! In the analytics view, click the "{label}" button to download reports as:': 'Ja. Klicke in der Analyseansicht auf die Schaltfläche „{label}“, um die Berichte herunterzuladen als:',
  'Yes! Open the task details dialog and go to the "{label}" tab.': 'Ja. Öffne die Aufgabendetails und wechsle zum Reiter „{label}“.',
  'You Did It! 🎊': 'Du hast es geschafft! 🎊',
  'You will now receive desktop notifications for important updates!': 'Ab jetzt bekommst du bei wichtigen Neuigkeiten eine Benachrichtigung auf dem Desktop.',
  "You'll receive desktop notifications for:": 'Du bekommst eine Desktop-Benachrichtigung bei:',
  "You're all caught up!": 'Du bist auf dem neuesten Stand.',
  'Your complete employee task management solution': 'Deine komplette Lösung für die Arbeit des Teams',
  'Your data is automatically saved in your browser. Use "{label}" to export your data before making major changes. You can also import data from previous backups.': 'Die Daten werden automatisch im Browser gespeichert. Nutze „{label}“, um sie vor größeren Änderungen zu exportieren; du kannst auch eine frühere Sicherung wieder einspielen.',
  'Your experience matters! Please take a moment to share your thoughts, report any issues, or suggest improvements. Every piece of feedback helps us make TaskFlow better for everyone.': 'Deine Erfahrung zählt. Nimm dir einen Moment, um uns deine Meinung zu sagen, Probleme zu melden oder Verbesserungen vorzuschlagen – jede Rückmeldung macht TaskFlow für alle besser.',
  'added a comment': 'hat einen Kommentar hinzugefügt',
  'assigned to {name}': 'hat sie {name} zugewiesen',
  'attached {file}': 'hat {file} angehängt',
  'by {name}': 'von {name}',
  'changed due date from {old} to {new}': 'hat die Frist von {old} auf {new} geändert',
  'changed priority from {old} to {new}': 'hat die Priorität von {old} auf {new} geändert',
  'changed status from {old} to {new}': 'hat den Status von {old} auf {new} geändert',
  'completion': 'Abschluss',
  'created this task': 'hat diese Aufgabe erstellt',
  'in 1 day': 'in 1 Tag',
  'in 1 hour': 'in 1 Stunde',
  'in {count} days': 'in {count} Tagen',
  'in {count} hours': 'in {count} Stunden',
  'made a change': 'hat etwas geändert',
  'reassigned from {old} to {new}': 'hat sie von {old} auf {new} übertragen',
  'removed attachment {file}': 'hat den Anhang {file} entfernt',
  'tasks/person': 'Aufgaben pro Person',
  'today': 'heute',
  'updated the description': 'hat die Beschreibung aktualisiert',
  'updated the title': 'hat den Titel aktualisiert',
  'yesterday': 'gestern',
  '{count} In Progress': '{count} in Bearbeitung',
  '{count} Overdue': '{count} überfällig',
  '{count} active': '{count} aktiv',
  '{count} already created': '{count} bereits erstellt',
  '{count} bounced': '{count} unzustellbar',
  '{count} clicked': '{count} angeklickt',
  '{count} days': '{count} Tage',
  '{count} days ago': 'vor {count} Tagen',
  '{count} days from now': 'in {count} Tagen',
  '{count} departments will be added to the existing ones': '{count} Abteilungen kommen zu den bisherigen hinzu',
  '{count} high priority': '{count} mit hoher Priorität',
  '{count} not started': '{count} nicht begonnen',
  '{count} opened': '{count} geöffnet',
  '{count} sent': '{count} gesendet',
  '{count} tasks/person': '{count} Aufgaben pro Person',
  '{count} unassigned': '{count} nicht zugewiesen',
  '{count} users set to {status}': '{count} Personen auf den Status {status} gesetzt',
  '{count}% completion': '{count} % Abschluss',
  '{name} department': 'Abteilung {name}',
  '~{hours}h per day': 'etwa {hours} Std. pro Tag',
  '• Be specific about what you experienced': '• Beschreibe genau, was passiert ist',
  '• Describe the impact on your workflow': '• Erkläre, wie es deine Arbeit beeinflusst',
  '• Include steps to reproduce (for bugs)': '• Bei einem Fehler: beschreibe, wie er sich nachstellen lässt',
  '• Suggest potential solutions if you have ideas': '• Wenn du eine Lösungsidee hast, schlag sie vor',
  '🎉 Desktop Notifications Enabled': '🎉 Desktop-Benachrichtigungen aktiv',
  '🎉 TaskFlow is Now Live! 🎉': '🎉 TaskFlow ist online! 🎉',
  '🎉 Time to Celebrate!': '🎉 Zeit zu feiern!',
  '📊 By The Numbers:': '📊 In Zahlen:',
  '📋 Launch Checklist': '📋 Checkliste für den Start',
  '📚 Documentation Ready:': '📚 Dokumentation bereit:',
  '🔔 Test Notification': '🔔 Testbenachrichtigung',
  '🔴 Needs Attention': '🔴 Braucht Aufmerksamkeit',
  '🚀 Ready for Launch!': '🚀 Bereit für den Start!',
  '🟠 Fair': '🟠 Mittelmäßig',
  '🟡 Good': '🟡 Gut',
  '🟢 Excellent': '🟢 Ausgezeichnet',
  'Awaiting approval': 'Warten auf Freigabe',
  'Approved': 'Freigegeben',
  'Requires approval': 'Freigabe erforderlich',
  'This task is completed but still needs approval': 'Diese Aufgabe ist erledigt, muss aber noch freigegeben werden',
  'Once completed, this task must be approved before it closes': 'Nach Abschluss muss diese Aufgabe freigegeben werden, bevor sie geschlossen wird',
  'Approved by {name} on {date}': 'Freigegeben von {name} am {date}',
  'Approved on {date}': 'Freigegeben am {date}',
  'Approve': 'Freigeben',
  'Request changes': 'Änderungen anfordern',
  'Send back to in progress': 'Zurück in Bearbeitung',
  'What needs to change? (optional)': 'Was muss geändert werden? (optional)',
  'Reason for sending the task back': 'Grund für die Rückgabe der Aufgabe',
  'Waiting for someone else to approve your work': 'Warten darauf, dass jemand anderes deine Arbeit freigibt',
  '{name} marked this task as done and is waiting for approval': '{name} hat diese Aufgabe als erledigt markiert und wartet auf die Freigabe',
  'This task is marked as done and is waiting for approval': 'Diese Aufgabe ist als erledigt markiert und wartet auf die Freigabe',
  'Require approval before this task can be closed': 'Freigabe verlangen, bevor diese Aufgabe geschlossen werden kann',
  'Task approved': 'Aufgabe freigegeben',
  'Task sent back for changes': 'Aufgabe zur Überarbeitung zurückgegeben',
  'Marked as done, waiting for approval': 'Als erledigt markiert, wartet auf Freigabe',
  'Awaiting my approval': 'Wartet auf meine Freigabe',
  'Loading tasks': 'Aufgaben werden geladen',
  'Loading statistics': 'Statistiken werden geladen',
  'Loading dashboard': 'Dashboard wird geladen',
  'No tasks yet': 'Noch keine Aufgaben',
  'Get started by creating your first task': 'Erstellen Sie zunächst Ihre erste Aufgabe',
  'Try adjusting your filters': 'Passen Sie die Filter an',
  "Organize your team's work": "Organisiere die Arbeit deines Teams",
  "TaskFlow helps teams organize work, track progress, and collaborate effectively. Let's take a quick tour of the key features.": "TaskFlow hilft Teams, Arbeit zu organisieren, den Fortschritt zu verfolgen und besser zusammenzuarbeiten. Sehen wir uns kurz die wichtigsten Funktionen an.",
  'approved this task': 'hat diese Aufgabe genehmigt',
  'sent it back for changes': 'hat sie zur Überarbeitung zurückgeschickt',
  'sent it back for changes: {reason}': 'hat sie zurückgeschickt: {reason}',
  'Exit Bulk Mode': 'Mehrfachauswahl beenden',
  'Selected tasks: {count}': 'Ausgewählte Aufgaben: {count}',
  'All Tasks ({count})': 'Alle Aufgaben ({count})',
  'Unassigned ({count})': 'Nicht zugewiesen ({count})',
  'When the assignee marks it done, a manager has to approve it.': 'Wenn die zugewiesene Person sie als erledigt markiert, muss eine verantwortliche Person sie genehmigen.',
  'This task is waiting for approval: approve it or send it back to change this.': 'Diese Aufgabe wartet auf eine Genehmigung: genehmigen Sie sie oder schicken Sie sie zurück, um das zu ändern.',
};
