/** Traduzioni spagnole. Chiavi identiche a quelle italiane/inglesi. */
export const TESTI_ES: Record<string, string> = {
  // === chiavi semantiche (partendo dall'italiano di i18n.ts) ===

  // --- accesso ---
  'app.sottotitolo': 'Gestione el trabajo de su equipo',
  'login.titolo': 'Iniciar sesión',
  'login.descrizione': 'Introduzca sus credenciales para continuar.',
  'login.email': 'Correo electrónico',
  'login.password': 'Contraseña',
  'login.entra': 'Iniciar sesión',
  'login.inCorso': 'Iniciando sesión...',
  'login.emailObbligatoria': 'El correo electrónico es obligatorio',
  'login.emailNonValida': 'Introduzca una dirección de correo válida',
  'login.passwordObbligatoria': 'La contraseña es obligatoria',
  'login.erroreGenerico': 'Se ha producido un error inesperado',
  'login.operazioneFallita': 'La operación no se ha completado',
  'login.accountDaAmministratore': 'Las cuentas las crea el administrador.',
  'login.contattaAmministratore': 'Si no consigue acceder, póngase en contacto con él.',
  'login.passwordDimenticata': '¿Ha olvidado la contraseña?',
  'login.invioInCorso': 'Enviando...',
  'login.inserisciEmailPerRipristino':
    'Introduzca su correo electrónico y solicite el restablecimiento',
  'login.ripristinoInviato':
    'Si la dirección corresponde a una cuenta, recibirá un enlace para restablecer la contraseña. Revise también el correo no deseado.',

  // --- nuova password ---
  'password.sottotitolo': 'Elija una nueva contraseña',
  'password.titolo': 'Nueva contraseña',
  'password.descrizione': 'Establezca la contraseña que usará a partir de ahora para acceder.',
  'password.nuova': 'Nueva contraseña',
  'password.ripeti': 'Repita la contraseña',
  'password.minimo': 'Al menos 8 caracteres.',
  'password.troppoCorta': 'La contraseña debe tener al menos 8 caracteres',
  'password.nonCoincidono': 'Las dos contraseñas no coinciden',
  'password.salva': 'Guardar la nueva contraseña',
  'password.salvataggio': 'Guardando...',
  'password.annullaEsci': 'Cancelar y cerrar sesión',

  // --- organizzazioni ---
  'org.nessuna': 'Ninguna organización asociada a esta cuenta',
  'org.creaTitolo': 'Cree su organización',
  'org.creaDescrizione':
    'Si está configurando la aplicación por primera vez, cree aquí el espacio de trabajo: será su propietario y podrá invitar a los demás. Si, en cambio, debería formar parte de una organización existente, pida a un administrador que le añada.',
  'org.nome': 'Nombre de la organización',
  'org.crea': 'Crear organización',
  'org.creazione': 'Creando...',
  'org.nuovaTitolo': 'Nueva organización',
  'org.nuovaDescrizione':
    'Será el propietario del nuevo espacio de trabajo, que empieza vacío. Los datos de la organización actual no se modifican.',
  'org.attiva': 'Organización activa',
  'org.creaNuova': 'Crear una nueva organización',
  'org.creata': 'Organización "{nome}" creada',
  'org.creazioneFallita': 'No se ha podido crear',

  // --- account disattivato ---
  'account.disattivato': 'Cuenta desactivada',
  'account.disattivatoDescrizione':
    'Un administrador ha desactivado esta cuenta. Póngase en contacto con él si cree que se trata de un error.',

  // --- credenziali ---
  'credenziali.titolo': 'Credenciales de acceso',
  'credenziali.descrizione':
    'Entregue estas credenciales al usuario: la contraseña provisional no se envía por correo y no volverá a estar visible tras cerrar esta ventana.',
  'credenziali.annotate': 'He anotado las credenciales',

  // --- comuni ---
  'comune.esci': 'Cerrar sesión',
  'comune.annulla': 'Cancelar',
  'comune.caricamento': 'Cargando…',
  'comune.lingua': 'Idioma',
  'comune.nessunaOrganizzazione': 'Ninguna organización activa',
  'comune.sessioneScaduta': 'Sesión caducada, vuelva a iniciar sesión',
  'comune.inizializzazioneFallita': 'Error de inicialización',
  'comune.richiestaFallita': 'Error en la solicitud ({stato})',
  'comune.modificaNonSalvata': 'Cambio no guardado',
  'ai.nonConfigurata': 'Las funciones de IA no están configuradas. Reintentar no sirve: contacte con un administrador.',
  'ai.nonDisponibile': 'El servicio de IA no está disponible ahora mismo. Inténtelo dentro de un momento.',
  'ai.tempoScaduto': 'El servicio de IA ha tardado demasiado. Inténtelo de nuevo.',
  'ai.limiteRaggiunto': 'Ha alcanzado el límite de solicitudes de IA. Inténtelo más tarde.',
  'ai.testoTroppoLungo': 'El texto es demasiado largo para procesarlo.',
  'ai.rifiutata': 'El servicio de IA no ha aceptado esta solicitud.',
  'email.nonPartita': 'Aviso guardado, pero el correo no se ha enviado',

  // === chiavi = stringa inglese (partendo dall'inglese) ===

  // --- generale, azioni ricorrenti ---
  'Cancel': 'Cancelar',
  'Close': 'Cerrar',
  'Save': 'Guardar',
  'Delete': 'Eliminar',
  'Edit': 'Editar',
  'Apply': 'Aplicar',
  'Back': 'Atrás',
  'Next': 'Siguiente',
  'Clear': 'Vaciar',
  'Clear all': 'Vaciar todo',
  'Create New': 'Crear nuevo',
  'Complete': 'Completar',
  'Bulk': 'Selección múltiple',
  'Analysis': 'Análisis',
  'Analytics': 'Análisis',
  'Dashboard': 'Panel',
  'Category': 'Categoría',
  'Custom': 'Personalizado',
  'Archived': 'Archivado',
  'Already exists': 'Ya existe',
  'Confirm Delete': 'Confirmar la eliminación',
  'Are you sure? This action cannot be undone!':
    '¿Está seguro? Esta acción no se puede deshacer.',
  'Are you sure you want to remove': '¿Seguro que desea eliminar',
  'All time': 'Siempre',
  'All types': 'Todos los tipos',
  'All Categories': 'Todas las categorías',
  'All Departments': 'Todos los departamentos',
  'All Departments Selected': 'Todos los departamentos seleccionados',
  'All Members': 'Todos los miembros',
  'All Priority': 'Todas las prioridades',
  'All Status': 'Todos los estados',
  'No data available': 'No hay datos disponibles',

  // --- stati e priorità ---
  'Active': 'Activo',
  'Completed': 'Completada',
  'In Progress': 'En curso',
  'Not Started': 'Sin empezar',
  'Overdue': 'Retrasada',
  'Priority': 'Prioridad',
  'Status': 'Estado',
  'High': 'Alta',
  'High Priority': 'Prioridad alta',
  'Description': 'Descripción',

  // --- attività ---
  'Task': 'Tarea',
  'Tasks': 'Tareas',
  'Add Task': 'Añadir tarea',
  'Create Task': 'Crear tarea',
  'Create New Task': 'Nueva tarea',
  'Total Tasks': 'Tareas totales',
  'Active Tasks': 'Tareas activas',
  'Completed Tasks': 'Tareas completadas',
  'Assigned Tasks': 'Tareas asignadas',
  'View Task': 'Abrir tarea',
  'Assign To': 'Asignar a',
  'Assignee': 'Responsable',
  'Add task details...': 'Añada los detalles...',
  'Add a comment...': 'Escriba un comentario...',
  'Add comments and attachments': 'Añada comentarios y archivos adjuntos',
  "Add a new task to your team's workflow. Fill in the details below.":
    'Añada una nueva tarea al trabajo del equipo. Complete los detalles a continuación.',
  "All changes are automatically tracked in the task's activity history.":
    'Todos los cambios quedan registrados en el historial de actividad de la tarea.',
  'Comment added!': 'Comentario añadido',
  'Comment deleted': 'Comentario eliminado',
  'Comment updated!': 'Comentario actualizado',
  'Comments and mentions': 'Comentarios y menciones',
  'Attachment removed': 'Archivo adjunto eliminado',
  'Completion Rate': 'Porcentaje de finalización',
  'Average Completion Time': 'Tiempo medio de finalización',
  'Avg. Completion Time': 'Tiempo medio de finalización',
  'Avg Time': 'Tiempo medio',
  'Avg Tasks': 'Tareas medias',
  'Avg Tasks per Member': 'Tareas medias por miembro',
  'Avg/Employee': 'Media por persona',
  'Avg/User': 'Media por usuario',
  'Current state of all tasks': 'Estado actual de todas las tareas',
  'Consider task priorities and deadlines': 'Tiene en cuenta prioridades y fechas límite',
  'Auto-archive Completed After (days)': 'Archivar las completadas después de (días)',
  'Allow Task Deletion': 'Permitir eliminar tareas',
  'Configure task behavior and policies': 'Comportamiento y reglas de las tareas',

  // --- persone e dipartimenti ---
  'Admin': 'Administrador',
  'Admin (Super Admin)': 'Administrador (superadministrador)',
  'Add User': 'Añadir usuario',
  'Add Team Member': 'Añadir un miembro',
  'Add a new member to your team': 'Añada una persona a su equipo',
  'Active Members': 'Miembros activos',
  'Active Users': 'Usuarios activos',
  'Active Team Members': 'Miembros activos del equipo',
  'Avatar URL': 'URL de la imagen',
  'Brief description about the team member...':
    'Breve descripción del miembro del equipo...',
  'Departments': 'Departamentos',
  'Department already added': 'Departamento ya añadido',
  'Active Departments': 'Departamentos activos',
  'Active departments': 'Departamentos activos',
  'Archived Departments': 'Departamentos archivados',
  'Archive inactive departments': 'Archivar los departamentos inactivos',
  'Add Department': 'Añadir departamento',
  'Add New Department': 'Nuevo departamento',
  'Create Department': 'Crear departamento',
  'Custom Departments': 'Departamentos personalizados',
  'Assign Departments': 'Asignar departamentos',
  'Add to existing departments': 'Añadir a los departamentos existentes',
  'Allow Multiple Departments': 'Permitir varios departamentos',
  'Assign employees to multiple departments': 'Asigne personas a varios departamentos',
  'A department with this name already exists': 'Ya existe un departamento con este nombre',
  'Brief description of this department...': 'Breve descripción del departamento...',
  'Busiest Department': 'Departamento con más carga',
  'Busiest Departments': 'Departamentos con más carga',
  'Choose departments to assign to the selected team members':
    'Elija los departamentos que desea asignar a los miembros seleccionados',
  'Create a new department to organize your team structure':
    'Cree un departamento para organizar la estructura del equipo',
  'Create and manage departments, assign leads, and track team organization':
    'Cree y gestione departamentos, asigne responsables y siga la organización del equipo',
  'Create new departments with details (name, description, color, lead, budget)':
    'Cree nuevos departamentos con nombre, descripción, color, responsable y presupuesto',
  'Create your first department to start organizing your team':
    'Cree el primer departamento para empezar a organizar su equipo',
  'Add departments to team members to see department analytics':
    'Asigne departamentos a los miembros del equipo para ver los análisis por departamento',
  'Analytics across all departments': 'Análisis de todos los departamentos',
  'Complete breakdown by department': 'Desglose completo por departamento',
  'Auto-assign color': 'Color asignado automáticamente',
  'Annual Budget': 'Presupuesto anual',
  'Analyze team member workloads': 'Analice la carga de trabajo del equipo',
  'Custom Permissions': 'Permisos personalizados',
  'Contact your administrator to request changes to your role or permissions.':
    'Póngase en contacto con un administrador para solicitar cambios en su rol o en sus permisos.',

  // --- analisi ---
  'Analytics Dashboard': 'Panel de análisis',
  'Average Engagement': 'Interacción media',
  'Avg Rating': 'Valoración media',
  'Comprehensive analytics for your team': 'Análisis completos de su equipo',
  'Comprehensive performance insights': 'Visión completa del rendimiento',
  'Complete performance breakdown': 'Desglose completo del rendimiento',
  'Complete system overview and analytics': 'Visión general del sistema y análisis',
  'Analyzing...': 'Analizando...',
  'CSV report downloaded successfully!': 'Informe CSV descargado',
  'Can I export analytics reports?': '¿Puedo exportar los informes de análisis?',
  'Can I attach files to tasks?': '¿Puedo adjuntar archivos a las tareas?',

  // --- AI ---
  'AI Assistant': 'Asistente de IA',
  'AI Auto-Assign': 'Asignación automática con IA',
  'AI Features': 'Funciones de IA',
  'AI Insights': 'Análisis de IA',
  'AI Model': 'Modelo de IA',
  'AI Recommendation': 'Recomendación de IA',
  'AI Assignment Suggestions': 'Propuestas de asignación de IA',
  'AI Duration & Deadline Estimate': 'Estimación de IA de duración y fecha límite',
  'AI estimate generated!': 'Estimación de IA generada',
  'Applied AI suggestion!': 'Sugerencia de IA aplicada',
  'Apply All Assignments': 'Aplicar todas las asignaciones',
  'Apply This Suggestion': 'Aplicar esta sugerencia',
  'Assignment Mode': 'Modo de asignación',
  'Ask me anything about your tasks and team!':
    'Pregúnteme lo que quiera sobre sus tareas y su equipo',
  'Ask me anything about your tasks...': 'Pregúnteme algo sobre sus tareas...',
  'Configure AI-powered capabilities': 'Configure las funciones basadas en IA',

  // --- annunci e feedback ---
  'Announcement': 'Anuncio',
  'Announcement deleted': 'Anuncio eliminado',
  'Announcement posted!': 'Anuncio publicado',
  'Announcement updated!': 'Anuncio actualizado',
  'Announcement updated successfully!': 'Anuncio actualizado',
  'Create announcements': 'Crear anuncios',
  'Be the first to share your thoughts!': 'Sea el primero en dar su opinión',
  'Brief summary of your feedback': 'Breve resumen de sus comentarios',
  'Bug Report': 'Informe de un problema',
  'Bug Reports': 'Informes de problemas',

  // --- notifiche ---
  'Choose which events trigger notifications': 'Elija qué eventos generan una notificación',
  'Control how often you receive notifications':
    'Con qué frecuencia recibe las notificaciones',
  'Control when and how you receive notifications': 'Cuándo y cómo recibe las notificaciones',
  'All notification types disabled': 'Todos los tipos de notificación desactivados',
  'All notification types enabled': 'Todos los tipos de notificación activados',
  'Batched (every 15 min)': 'Agrupadas (cada 15 minutos)',
  'Daily digest': 'Resumen diario',
  'Daily Digest Time': 'Hora del resumen diario',

  // --- email ---
  'Bounce Rate': 'Porcentaje de rebote',
  'Click': 'Clic',
  'Clicks': 'Clics',
  'Click Rate': 'Porcentaje de clics',
  'Click-to-Open Rate': 'Clics sobre correos abiertos',
  'Combined open and click rate average': 'Media de aperturas y clics',
  'Attachment Inclusion': 'Inclusión de los archivos adjuntos',
  'Allowed File Types': 'Tipos de archivo permitidos',
  'Currently allowed file types for email attachments':
    'Tipos de archivo permitidos actualmente como adjuntos',
  'Alert users when attachments cannot be included':
    'Avisar cuando un archivo adjunto no se pueda incluir',
  'Configure how task attachments are included in email notifications':
    'Cómo se incluyen los archivos adjuntos de las tareas en los correos de notificación',
  'Control whether task attachments are sent with email notifications':
    'Decide si los archivos adjuntos de las tareas se envían con los correos',
  'Customize email notifications sent to users for various task events':
    'Personalice los correos enviados para los distintos eventos de las tareas',
  'Available Variables': 'Variables disponibles',
  'Click a variable to insert it at cursor position':
    'Haga clic en una variable para insertarla en la posición del cursor',
  'Best regards,': 'Atentamente,',

  // --- amministrazione ---
  'Access email settings and system configuration':
    'Acceda a los ajustes de correo y a la configuración del sistema',
  'Active Settings Summary': 'Resumen de los ajustes activos',
  'Application Name': 'Nombre de la aplicación',
  'Company Name': 'Nombre de la empresa',
  'Basic application configuration': 'Configuración básica de la aplicación',
  'Configure system-wide settings and preferences':
    'Configure los ajustes generales del sistema',
  'Current system status and statistics': 'Estado actual del sistema y estadísticas',
  'Current data usage across all collections': 'Espacio ocupado por los datos',
  'Audit Entries': 'Entradas del registro',
  'Audit Log': 'Registro de actividad',
  'Audit Logging': 'Registro de actividad',
  'Audit log cleared': 'Registro vaciado',
  'Clear Audit Log': 'Vaciar el registro',
  'Clear All Data': 'Borrar todos los datos',
  'All data cleared successfully': 'Se han borrado todos los datos',
  'Backup & Restore': 'Copia de seguridad y restauración',
  'Backup, restore, and manage system data':
    'Copia de seguridad, restauración y gestión de los datos',
  'Changes discarded': 'Cambios descartados',
  'Allow Self Registration': 'Permitir el registro autónomo',
  'Allowed IP Addresses': 'Direcciones IP permitidas',
  'Add IP Address': 'Añadir dirección IP',
  'Central Time': 'Hora central',
  'Custom Time Range': 'Intervalo personalizado',
  'DD/MM/YYYY': 'DD/MM/AAAA',
  'After 81 iterations, your application is ready to deploy.':
    'Tras 81 iteraciones, su aplicación está lista para publicarse.',
  'Click the': 'Haga clic en',

  // --- testi la cui lingua di partenza è l'italiano ---
  'Accesso revocato e membro rimosso': 'Acceso revocado y miembro eliminado',
  'Apri TaskFlow per vedere i dettagli.': 'Abra TaskFlow para ver los detalles.',
  'Assegna una nuova password provvisoria': 'Asignar una nueva contraseña provisional',
  'Backup ripristinato. Ricarico la pagina...':
    'Copia de seguridad restaurada. Recargando la página...',

  // --- dati e backup ---
  'Data': 'Datos',
  'Data Management': 'Gestión de los datos',
  'Data Retention (days)': 'Conservación de los datos (días)',
  'Data Safety': 'Seguridad de los datos',
  'Data exported successfully!': 'Datos exportados',
  'Data imported successfully! Refresh to see changes.':
    'Datos importados. Actualice para ver los cambios.',
  'Download a backup of all tasks, employees, and settings':
    'Descargue una copia de seguridad de las tareas, las personas y los ajustes',
  'Download a complete backup of all system data including tasks, users, settings, and audit logs.':
    'Descargue una copia de seguridad completa: tareas, usuarios, ajustes y registro de actividad.',
  'Export': 'Exportar',
  'Export Backup': 'Exportar copia de seguridad',
  'Export Data': 'Exportar datos',
  'Export Report': 'Exportar informe',
  'Export as CSV': 'Exportar en CSV',
  'Export as PDF': 'Exportar en PDF',
  'Export, import, or clear your TaskFlow data': 'Exporte, importe o borre sus datos',
  'Import Data': 'Importar datos',
  'Failed to clear data': 'No se han podido borrar los datos',
  'Failed to export data': 'No se han podido exportar los datos',
  'Failed to export CSV report': 'No se ha podido exportar el informe CSV',
  'Failed to export PDF report': 'No se ha podido exportar el informe PDF',
  'Failed to import data. Please check the file format.':
    'No se han podido importar los datos. Compruebe el formato del archivo.',
  'Failed to read file': 'No se ha podido leer el archivo',
  'File attached successfully!': 'Archivo adjuntado',
  'File size must be less than 10MB': 'El archivo debe ser menor de 10 MB',
  'Files are stored securely and can be downloaded or deleted by authorized users.':
    'Los archivos se guardan de forma segura y pueden descargarlos o eliminarlos los usuarios autorizados.',

  // --- eliminazioni e conferme ---
  'Delete Department?': '¿Eliminar el departamento?',
  'Delete Task?': '¿Eliminar la tarea?',
  'Delete Team Member?': '¿Eliminar al miembro del equipo?',
  'Delete Task': 'Eliminar tarea',
  'Discard Changes': 'Descartar los cambios',
  'Deselect All': 'Deseleccionar todo',
  'Disable All': 'Desactivar todo',
  'Enable All': 'Activar todo',
  'Declined': 'Rechazado',

  // --- dipartimenti ---
  'Department': 'Departamento',
  'Department Admin Dashboard': 'Panel del responsable de departamento',
  'Department Analytics': 'Análisis por departamento',
  'Department Analytics Report': 'Informe de análisis por departamento',
  'Department Announcements': 'Anuncios del departamento',
  'Department Color': 'Color del departamento',
  'Department Color Guide': 'Guía de colores de los departamentos',
  'Department Colors': 'Colores de los departamentos',
  'Department Details': 'Detalles del departamento',
  'Department Health': 'Salud del departamento',
  'Department Information': 'Información del departamento',
  'Department Lead': 'Responsable del departamento',
  'Department Management': 'Gestión de los departamentos',
  'Department Performance': 'Rendimiento por departamento',
  'Department Performance Overview': 'Visión del rendimiento por departamento',
  'Department Performance Radar': 'Radar del rendimiento por departamento',
  'Department Settings': 'Ajustes de los departamentos',
  'Department Summary': 'Resumen del departamento',
  'Department Tasks': 'Tareas del departamento',
  'Department Templates': 'Plantillas de departamento',
  'Department name is required': 'El nombre del departamento es obligatorio',
  'Department organization and policies': 'Organización y reglas de los departamentos',
  'Departments with issues': 'Departamentos con problemas',
  'Edit Department': 'Editar departamento',
  'Enable Department Budgets': 'Activar los presupuestos de departamento',
  'Employee Count by Department': 'Número de personas por departamento',
  'Filter tasks by department': 'Filtre las tareas por departamento',
  'Engineering, Sales, Marketing...': 'Ingeniería, Ventas, Marketing...',
  'Enter department name or select existing':
    'Escriba el nombre del departamento o elija uno existente',
  'Lead': 'Responsable',
  'Leads': 'Responsables',

  // --- persone ---
  'Default User Role': 'Rol predeterminado',
  'Designate as Team Lead': 'Designar como responsable del equipo',
  'Edit Team Member': 'Editar miembro del equipo',
  'Employees': 'Personas',
  'Employee Performance': 'Rendimiento de las personas',
  'Email Address': 'Dirección de correo electrónico',
  'Email is required: the account is created from this address':
    'El correo electrónico es obligatorio: la cuenta se crea a partir de esta dirección',
  'Invalid name or role': 'Nombre o rol no válidos',
  'Full system access': 'Acceso completo al sistema',
  'Highest workload per employee': 'Mayor carga de trabajo por persona',
  'Highest completion rates': 'Mayores porcentajes de finalización',
  'Highest Rated': 'Mejor valorado',
  'Health Score': 'Índice de salud',
  'Inactive': 'No activo',

  // --- attività ---
  'Edit Task': 'Editar tarea',
  'Enter task title...': 'Título de la tarea...',
  'Due Date': 'Fecha límite',
  'Default Task Duration (days)': 'Duración predeterminada de una tarea (días)',
  'Escalate Overdue After (days)': 'Escalar las tareas retrasadas después de (días)',
  'Estimated Duration': 'Duración estimada',
  'Enable Subtasks': 'Activar las subtareas',
  'Enable Task Dependencies': 'Activar las dependencias entre tareas',
  'High Priority Tasks': 'Tareas de prioridad alta',
  'In Progress Tasks': 'Tareas en curso',
  'From creation to completion': 'De la creación a la finalización',
  'Key Factors': 'Factores principales',
  'Generate Estimate': 'Generar la estimación',
  'Generate optimal assignment suggestions': 'Genere propuestas de asignación óptimas',
  'Get intelligent insights and suggestions for your tasks':
    'Análisis y sugerencias sobre sus tareas',
  'Enable Auto-Assignment': 'Activar la asignación automática',
  'Enable Smart Suggestions': 'Activar las sugerencias inteligentes',
  'Enable AI Features': 'Activar las funciones de IA',
  'Enable all AI-powered features': 'Activar todas las funciones basadas en IA',
  'Insights updated!': 'Análisis actualizados',

  // --- annunci ---
  'Edit announcement': 'Editar anuncio',
  'Editing announcement': 'Edición del anuncio',
  'Enter announcement title': 'Título del anuncio',
  'Enter your announcement message...': 'Texto del anuncio...',
  'Invalid title or message': 'Título o mensaje no válidos',
  'Important': 'Importante',
  'Info': 'Información',

  // --- notifiche ---
  'Delivery Frequency': 'Frecuencia de envío',
  'Desktop Alerts': 'Avisos de escritorio',
  'Desktop Notifications': 'Notificaciones de escritorio',
  'Desktop notifications enabled!': 'Notificaciones de escritorio activadas',
  'Desktop notifications were blocked. Please enable them in your browser settings.':
    'Las notificaciones de escritorio están bloqueadas. Actívelas en los ajustes del navegador.',
  'Enable Notifications': 'Activar las notificaciones',
  'Enable System Notifications': 'Activar las notificaciones del sistema',
  'Enable Email Notifications': 'Activar las notificaciones por correo',
  'Email Notifications': 'Notificaciones por correo',
  'Get notified via email about task updates':
    'Reciba por correo las novedades de las tareas',
  'End Time': 'Hora de fin',
  'Hourly': 'Cada hora',
  'Last 7 days': 'Últimos 7 días',
  'Last 30 days': 'Últimos 30 días',
  'Last 90 days': 'Últimos 90 días',

  // --- email ---
  'Delivery Logs': 'Registro de envíos',
  'Device': 'Dispositivo',
  'Device Distribution': 'Distribución por dispositivo',
  'Email': 'Correo electrónico',
  'Email Activity Over Time': 'Actividad de correo a lo largo del tiempo',
  'Email Analytics': 'Análisis de los correos',
  'Email Attachments': 'Archivos adjuntos de los correos',
  'Email Attachment Settings': 'Ajustes de los archivos adjuntos',
  'Email Delivery Analytics': 'Análisis de entrega de los correos',
  'Email Template Customization': 'Personalización de las plantillas de correo',
  'Email Templates': 'Plantillas de correo',
  'Email Types Distribution': 'Distribución por tipo de correo',
  'Email attachment settings saved': 'Ajustes de los archivos adjuntos guardados',
  'Email subject...': 'Asunto...',
  'Email template saved successfully!': 'Plantilla de correo guardada',
  'Engagement': 'Interacción',
  'Engagement Metrics': 'Indicadores de interacción',
  'Exclusion Notifications': 'Avisos de exclusión',
  'Executable files (.exe, .bat, .sh) are automatically excluded for security reasons':
    'Los archivos ejecutables (.exe, .bat, .sh) se excluyen automáticamente por seguridad',
  'Include a note in the email when some attachments exceed size limits':
    'Añadir una nota al correo cuando algunos archivos adjuntos superen el límite',
  'Include attachments in emails': 'Incluir los archivos adjuntos en los correos',
  'Individual files larger than this will be excluded from emails':
    'Los archivos mayores que este límite se excluyen de los correos',
  'Images': 'Imágenes',
  'HTML Template': 'Plantilla HTML',
  'Latest email delivery activity': 'Últimos envíos',
  'Editor': 'Editor',

  // --- sistema ---
  'Date Format': 'Formato de la fecha',
  'Eastern Time': 'Hora del Este',
  'Enable API Access': 'Activar el acceso a la API',
  'Enable Audit Log': 'Activar el registro de actividad',
  'Enable IP Whitelist': 'Activar la lista de IP permitidas',
  'Enable Slack Integration': 'Activar la integración con Slack',
  'Enable Two-Factor Authentication': 'Activar la autenticación en dos pasos',
  'Enforce password complexity rules': 'Imponer reglas de complejidad de la contraseña',
  'Expiration Date': 'Fecha de caducidad',
  'External service connections': 'Conexiones con servicios externos',
  'General': 'General',
  'General Settings': 'Ajustes generales',
  'Integrations': 'Integraciones',
  'Invalid IP address format': 'Formato de la dirección IP no válido',
  'IP address added': 'Dirección IP añadida',
  'IP address removed': 'Dirección IP eliminada',
  'Last 10 system changes': 'Últimos 10 cambios del sistema',
  'Iterations': 'Iteraciones',
  'Launch Info': 'Información del lanzamiento',
  'Language': 'Idioma',
  'English': 'Inglés',
  'Italian': 'Italiano',
  'French': 'Francés',
  'German': 'Alemán',
  'GPT-4o (More capable)': 'GPT-4o (más capaz)',
  'GPT-4o-mini (Faster)': 'GPT-4o-mini (más rápido)',

  // --- aiuto e riscontri ---
  'Help': 'Ayuda',
  'Help us improve TaskFlow by sharing your thoughts, suggestions, or reporting issues.':
    'Ayúdenos a mejorar TaskFlow: cuéntenos qué opina, proponga ideas o informe de un problema.',
  'Everything you need to know about using TaskFlow effectively':
    'Todo lo que necesita saber para usar bien TaskFlow',
  'Feature Request': 'Solicitud de función',
  'Feature Requests': 'Solicitudes de funciones',
  'Features': 'Funciones',
  'Feedback Type': 'Tipo de comentario',
  'Feedback status updated': 'Estado del comentario actualizado',
  'Give Feedback': 'Dejar un comentario',
  'How would you rate your experience?': '¿Cómo valora su experiencia?',
  'How do I access analytics?': '¿Cómo accedo a los análisis?',
  'How do I add comments to tasks?': '¿Cómo añado comentarios a una tarea?',
  'How do I add team members?': '¿Cómo añado miembros al equipo?',
  'How do I create a new task?': '¿Cómo creo una nueva tarea?',
  'How do I edit an existing task?': '¿Cómo edito una tarea existente?',
  'How do I manage departments?': '¿Cómo gestiono los departamentos?',
  'How do bulk operations work?': '¿Cómo funcionan las operaciones múltiples?',
  'How does AI Auto-Assignment work?': '¿Cómo funciona la asignación automática con IA?',
  'Improvement Suggestion': 'Sugerencia de mejora',
  'Improvements': 'Mejoras',
  "I'll Do It Later": 'Lo haré más tarde',
  'Detailed Performance Metrics': 'Indicadores detallados del rendimiento',
  'Il file non contiene dati da ripristinare': 'El archivo no contiene datos que restaurar',

  // --- anagrafica e ruoli ---
  'Leave blank to auto-generate an avatar': 'Deje en blanco para generar una imagen',
  'Location': 'Ubicación',
  'Manage': 'Gestionar',
  'Manage Role & Permissions': 'Gestionar el rol y los permisos',
  'Manage Team': 'Gestionar el equipo',
  'Manage Users': 'Gestionar usuarios',
  'Manage all users and departments': 'Gestiona todos los usuarios y departamentos',
  'Manage tasks within their department(s)': 'Gestiona las tareas de sus departamentos',
  'Manage your team members, roles, and departments':
    'Gestione los miembros del equipo, los roles y los departamentos',
  "Manage your team's work efficiently": 'Organice el trabajo de su equipo',
  'Manager': 'Manager',
  'Manager (Department Admin)': 'Manager (responsable de departamento)',
  'Member': 'Miembro',
  'Name': 'Nombre',
  'Name and role are required': 'El nombre y el rol son obligatorios',
  'Phone Number': 'Número de teléfono',
  'Role': 'Rol',
  'Role and permissions updated successfully': 'Rol y permisos actualizados',
  'Need different permissions?': '¿Necesita permisos distintos?',
  'Override default role permissions with custom settings':
    'Sustituya los permisos predeterminados del rol por ajustes personalizados',
  'Permission Status': 'Estado de los permisos',
  'Search by name, role, email, department, skills...':
    'Busque por nombre, rol, correo, departamento, competencias...',
  'Select All': 'Seleccionar todo',
  'Set Active': 'Marcar como activo',
  'Set Inactive': 'Marcar como no activo',
  'Senior Developer': 'Desarrollador sénior',
  'San Francisco, CA': 'Madrid, España',
  'New York, Remote...': 'Barcelona, en remoto...',
  'React, TypeScript, Node.js': 'React, TypeScript, Node.js',

  // --- dipartimenti (2) ---
  'No Department Data': 'Sin datos de departamentos',
  'No department data available': 'No hay datos disponibles sobre los departamentos',
  'No departments selected. Add departments above.':
    'Ningún departamento seleccionado. Añada uno más arriba.',
  'No departments yet': 'Todavía no hay departamentos',
  'No employees assigned to this department':
    'No hay personas asignadas a este departamento',
  'Multi-metric comparison across departments':
    'Comparación de varios indicadores entre departamentos',
  'Quick insights for your departments': 'Vistazo rápido a sus departamentos',
  'Quick-start templates for common department types. Choose individual departments or create entire categories at once.':
    'Plantillas listas para los departamentos más habituales. Elija un departamento concreto o cree categorías enteras de una vez.',
  'Replace all departments': 'Sustituir todos los departamentos',
  'Require Department Assignment': 'Exigir la asignación a un departamento',
  'Select All Departments': 'Seleccionar todos los departamentos',
  'Select a team lead (optional)': 'Elija un responsable (opcional)',
  'Set department leads': 'Defina los responsables de los departamentos',
  'Please select at least one department': 'Seleccione al menos un departamento',

  // --- attività (2) ---
  'Low Priority': 'Prioridad baja',
  'Medium': 'Media',
  'Medium Priority': 'Prioridad media',
  'My Dashboard': 'Mi panel',
  'My Tasks': 'Mis tareas',
  'Match skills and departments': 'Hace coincidir competencias y departamentos',
  'New Task Assigned': 'Nueva tarea asignada',
  'New Comment': 'Nuevo comentario',
  'New Announcement': 'Nuevo anuncio',
  'Not Started Tasks': 'Tareas sin empezar',
  'No task data available yet': 'Todavía no hay datos sobre las tareas',
  'No tasks found': 'No se han encontrado tareas',
  'No unassigned tasks to assign': 'No hay tareas sin asignar',
  'No upcoming deadlines in the next 3 days':
    'No hay fechas límite en los próximos 3 días',
  'Overdue Tasks': 'Tareas retrasadas',
  'Overdue tasks (priority)': 'Tareas retrasadas (prioridad)',
  'Priority Breakdown': 'Desglose por prioridad',
  'Priority Distribution': 'Distribución de las prioridades',
  'Priority Warnings': 'Avisos de prioridad',
  'Please enter a task title first': 'Escriba antes el título de la tarea',
  'Reminder Before Due (days)': 'Recordatorio antes de la fecha límite (días)',
  'Require Task Approval': 'Exigir la aprobación de las tareas',
  'Requiring immediate attention': 'Requieren atención inmediata',
  'Needs Attention': 'Requiere atención',
  'Need attention': 'Requieren atención',
  'Review the suggested task assignments below. These are optimized for workload balance and task requirements.':
    'Revise las asignaciones propuestas a continuación: tienen en cuenta el equilibrio de la carga de trabajo y los requisitos de las tareas.',
  'Review the suggestions before applying them.':
    'Revise las sugerencias antes de aplicarlas.',

  // --- messaggi vuoti ---
  'No active employees available': 'No hay personas activas disponibles',
  'No activity yet': 'Todavía no hay actividad',
  'No announcements': 'No hay anuncios',
  'No attachments yet': 'Todavía no hay archivos adjuntos',
  'No audit entries yet': 'Todavía no hay entradas en el registro',
  'No click data available': 'No hay datos sobre los clics',
  'No comments yet': 'Todavía no hay comentarios',
  'No feedback yet': 'Todavía no hay comentarios',
  'No insights available yet': 'Todavía no hay análisis disponibles',
  'No notifications': 'No hay notificaciones',
  'No performance data available': 'No hay datos sobre el rendimiento',
  'No team members found': 'No se han encontrado miembros del equipo',
  'No team members yet. Add team members to see analytics.':
    'Todavía no hay miembros en el equipo. Añada alguno para ver los análisis.',
  'None': 'Ninguno',

  // --- notifiche (2) ---
  'Mark all read': 'Marcar todas como leídas',
  'Mark as read': 'Marcar como leída',
  'Muted': 'Silenciadas',
  'Notification Frequency': 'Frecuencia de las notificaciones',
  'Notification Retention (days)': 'Conservación de las notificaciones (días)',
  'Notification Settings': 'Ajustes de las notificaciones',
  'Notification Sounds': 'Sonidos de las notificaciones',
  'Notification Type': 'Tipo de notificación',
  'Notification Types': 'Tipos de notificación',
  'Notifications': 'Notificaciones',
  'Notifications will be paused between these times':
    'Las notificaciones se pausarán en esta franja horaria',
  'Notify when attachments are excluded': 'Avisar cuando se excluya un archivo adjunto',
  'Pause notifications during specific times':
    'Pause las notificaciones en determinadas franjas horarias',
  'Play sounds when notifications arrive': 'Reproducir un sonido al llegar una notificación',
  'Quiet Hours': 'Horas de silencio',
  'Quiet Hours Active': 'Horas de silencio activas',
  'Real-time': 'En tiempo real',
  'Receive notifications': 'Recibir las notificaciones',
  'Receive notifications via email': 'Recibir las notificaciones por correo',
  'Receive real-time alerts on your desktop for important task updates':
    'Reciba avisos inmediatos en el escritorio de las novedades importantes',
  'Send Test Notification': 'Enviar una notificación de prueba',

  // --- email (2) ---
  'Max Attachment Size (MB)': 'Tamaño máximo del archivo adjunto (MB)',
  'Maximum single attachment size': 'Tamaño máximo de un solo archivo adjunto',
  'Maximum total attachment size per email':
    'Tamaño máximo total de los archivos adjuntos por correo',
  'Most email providers have attachment size limits. SendGrid and Resend both support up to 25MB total.':
    'Casi todos los proveedores tienen un límite para los archivos adjuntos: SendGrid y Resend llegan a 25 MB en total.',
  'Most popular links in your emails': 'Enlaces más clicados de sus correos',
  'Office Documents': 'Documentos de Office',
  'PDF Documents': 'Documentos PDF',
  'Open Rate': 'Porcentaje de apertura',
  'Opened': 'Abiertos',
  'Open and click rates for different email types':
    'Aperturas y clics por tipo de correo',
  'Percentage of opened emails that received clicks':
    'Porcentaje de correos abiertos que recibieron un clic',
  'Performance by Email Type': 'Rendimiento por tipo de correo',
  'Plain Text': 'Texto sin formato',
  'Preview': 'Vista previa',
  'Recent Deliveries': 'Envíos recientes',
  'Recipient': 'Destinatario',
  'Resend': 'Resend',
  'SendGrid': 'SendGrid',
  'Sent': 'Enviados',
  'Set maximum file sizes for email attachments':
    'Defina los tamaños máximos de los archivos adjuntos',
  'Save Template': 'Guardar la plantilla',

  // --- sistema (2) ---
  'MM/DD/YYYY': 'MM/DD/AAAA',
  'Maintenance Mode': 'Modo de mantenimiento',
  'Max AI Requests Per Day': 'Máximo de peticiones de IA al día',
  'Max Login Attempts': 'Máximo de intentos de acceso',
  'Monday': 'Lunes',
  'Mountain Time': 'Hora de las Montañas Rocosas',
  'Pacific Time': 'Hora del Pacífico',
  'London': 'Londres',
  'Paris': 'París',
  'Password Expiry (days)': 'Caducidad de la contraseña (días)',
  'Permanently delete all audit log entries. This action cannot be undone.':
    'Elimina definitivamente todas las entradas del registro. No se puede deshacer.',
  'Permanently delete all tasks, employees, and settings':
    'Elimina definitivamente las tareas, las personas y los ajustes',
  'Require 2FA for all users': 'Exigir la autenticación en dos pasos a todos',
  'Require Email Verification': 'Exigir la verificación del correo',
  'Require Strong Passwords': 'Exigir contraseñas seguras',
  'Reset': 'Restablecer',
  'Reset to Default': 'Restablecer el valor predeterminado',
  'Reset to Defaults': 'Restablecer los valores predeterminados',
  'Restore': 'Restaurar',
  'Restore from a previous backup file':
    'Restaure desde un archivo de copia de seguridad anterior',
  'Restore system data from a previously exported backup file.':
    'Restaure los datos del sistema desde una copia de seguridad exportada anteriormente.',
  'Save Changes': 'Guardar los cambios',
  'Save Settings': 'Guardar los ajustes',
  'Security': 'Seguridad',
  'Security Settings': 'Ajustes de seguridad',
  'Security Status': 'Estado de la seguridad',
  'Security policies and audit configuration':
    'Reglas de seguridad y configuración del registro',
  'Session Timeout (minutes)': 'Caducidad de la sesión (minutos)',
  'Set expiration date': 'Establecer una fecha de caducidad',
  'Please set an expiry date': 'Establezca una fecha de caducidad',
  'Overview': 'Resumen',
  'Overall Summary': 'Resumen general',
  'Quick Actions': 'Acciones rápidas',
  'Quick Info': 'Información rápida',
  'Quick Presets': 'Preajustes',
  'Recent Activity': 'Actividad reciente',
  'Recent Audit Log': 'Registro reciente',
  'Refresh': 'Actualizar',
  'Previous': 'Anterior',
  'Rate': 'Valorar',
  'Recommendations': 'Recomendaciones',
  'Review': 'Revisar',
  'Reviewing': 'En revisión',
  'Review and manage feedback from your team members':
    'Lea y gestione los comentarios de los miembros de su equipo',
  'Performance': 'Rendimiento',
  'Performance Patterns': 'Evolución del rendimiento',
  'Message': 'Mensaje',
  'Most Popular': 'Más populares',
  'Most Recent': 'Más recientes',
  'Other': 'Otro',
  'Pinned': 'Destacado',
  'Planned': 'Planificado',
  'Praise': 'Felicitaciones',
  'Praise & Thanks': 'Felicitaciones y agradecimientos',
  'Post Announcement': 'Publicar anuncio',
  'New 30d': 'Nuevos en 30 días',
  'Questions or need help? Check the Help Documentation or contact your administrator.':
    '¿Tiene preguntas o necesita ayuda? Consulte la documentación o póngase en contacto con un administrador.',

  // --- validazioni ---
  'Please enter a message': 'Escriba un mensaje',
  'Please enter a title': 'Escriba un título',
  'Please enter a valid email address': 'Introduzca una dirección de correo válida',
  'Please provide a description': 'Añada una descripción',
  'Please provide a title': 'Añada un título',
  'Please provide as much detail as possible...': 'Describa con el mayor detalle posible...',
  'PDF report will open in print dialog':
    'El informe PDF se abrirá en la ventana de impresión',

  // --- testi già in italiano ---
  'Rimossa dalla configurazione una chiave API salvata dalla versione precedente: le chiavi vivono solo lato server.':
    'Se ha eliminado de la configuración una clave de API guardada por la versión anterior: las claves solo existen en el servidor.',
  'Se stai leggendo questo messaggio, la configurazione di invio lato server funziona.':
    'Si está leyendo este mensaje, la configuración de envío del servidor funciona.',
  'Sessione scaduta, accedi di nuovo': 'Sesión caducada, vuelva a iniciar sesión',
  'Serve il ruolo': 'Se requiere el rol',
  'Invio di prova': 'Envío de prueba',
  'Indica un indirizzo a cui inviare la prova':
    'Indique una dirección a la que enviar la prueba',
  'Le funzioni AI non sono attive': 'Las funciones de IA no están activas',

  // --- impostazioni ---
  'Settings Version': 'Versión de los ajustes',
  'Settings reset to defaults': 'Ajustes restablecidos a los valores predeterminados',
  'Settings saved successfully!': 'Ajustes guardados',
  'Size Limits': 'Límites de tamaño',
  'Slack Webhook URL': 'URL del webhook de Slack',
  'Webhook URL': 'URL del webhook',
  'Smart Suggestions': 'Sugerencias inteligentes',
  'Sort by': 'Ordenar por',
  'Spanish': 'Español',
  'Standard Departments': 'Departamentos estándar',
  'Start Time': 'Hora de inicio',
  'Storage Information': 'Ocupación de los datos',
  'Sunday': 'Domingo',
  'System Notifications': 'Notificaciones del sistema',
  'System Overview': 'Visión del sistema',
  'System Settings': 'Ajustes del sistema',
  'System is currently in maintenance mode': 'El sistema está en modo de mantenimiento',
  'System-wide notification configuration': 'Configuración general de las notificaciones',
  'Timezone': 'Zona horaria',
  'Tokyo': 'Tokio',
  'Week Start Day': 'Primer día de la semana',
  'YYYY-MM-DD': 'AAAA-MM-DD',
  'Templates': 'Plantillas',
  'Template reset to default. Click Save to apply changes.':
    'Plantilla restablecida al valor predeterminado. Pulse Guardar para aplicar los cambios.',
  'Use Template': 'Usar la plantilla',
  'Type': 'Tipo',
  'Title': 'Título',
  'Subject': 'Asunto',
  'Subject Line': 'Asunto',
  'Text Files': 'Archivos de texto',
  'Total': 'Total',
  'Unsaved Changes': 'Cambios sin guardar',
  'Track all system changes and actions': 'Registre todos los cambios y acciones del sistema',
  'Track and manage department budgets':
    'Controle y gestione los presupuestos de los departamentos',
  'Trends': 'Tendencia',
  'Try Again': 'Reintentar',
  'Volume': 'Volumen',
  'Test Sounds': 'Probar los sonidos',
  'Test notification sent!': 'Notificación de prueba enviada',
  'Tests Passed': 'Pruebas superadas',

  // --- team e analisi ---
  'Team': 'Equipo',
  'Team Analytics': 'Análisis del equipo',
  'Team Analytics Report': 'Informe de análisis del equipo',
  'Team Feedback Board': 'Tablón de comentarios del equipo',
  'Team Lead': 'Responsable del equipo',
  'Team Leads': 'Responsables del equipo',
  'Team Member Details': 'Detalles del miembro del equipo',
  'Team Members': 'Miembros del equipo',
  'Team Performance': 'Rendimiento del equipo',
  'Team Performance Overview': 'Visión del rendimiento del equipo',
  'Team member updated successfully!': 'Miembro del equipo actualizado',
  'Team members will be notified of new comments on their assigned tasks.':
    'Se avisará a los miembros del equipo de los nuevos comentarios en las tareas que tienen asignadas.',
  'Team members with overdue or high-priority tasks':
    'Miembros del equipo con tareas retrasadas o de prioridad alta',
  'Team size distribution': 'Distribución del tamaño de los equipos',
  'Top Performer': 'Mejor resultado',
  'Top Performers': 'Mejores resultados',
  'Top Performing': 'Con los mejores resultados',
  'Total Departments': 'Departamentos totales',
  'Total Employees': 'Personas totales',
  'Total Feedback': 'Comentarios totales',
  'Total Members': 'Miembros totales',
  'Total Team Members': 'Miembros totales del equipo',
  'Total Sent': 'Enviados en total',
  'Total tasks per department': 'Tareas totales por departamento',
  'With Leads': 'Con responsable',
  'Workload Alerts': 'Avisos sobre la carga de trabajo',
  'Workload Analysis': 'Análisis de la carga de trabajo',
  'Workload Distribution': 'Distribución de la carga de trabajo',
  'Workload by Department': 'Carga de trabajo por departamento',
  'Target Departments': 'Departamentos afectados',
  'Task Distribution by Department': 'Distribución de las tareas por departamento',
  'Task breakdown by team member': 'Desglose de las tareas por miembro del equipo',
  'Tasks by priority level': 'Tareas por nivel de prioridad',
  'Tasks completed over the last 7 days': 'Tareas completadas en los últimos 7 días',
  'Tasks due within 24 hours (priority)': 'Tareas que vencen en 24 horas (prioridad)',
  'Task Completion Trend': 'Evolución de las tareas completadas',
  'Task Status Distribution': 'Distribución de los estados',
  'Super Admin Dashboard': 'Panel del superadministrador',
  'Upcoming Deadlines': 'Próximas fechas límite',
  'Unassigned': 'Sin asignar',
  'Unassigned Tasks': 'Tareas sin asignar',

  // --- attività, notifiche ed eventi ---
  'Task Creation': 'Creación de tareas',
  'Task Management': 'Gestión de las tareas',
  'Task Priority Updated': 'Prioridad de la tarea actualizada',
  'Task Questions': 'Preguntas sobre las tareas',
  'Task Reassigned to You': 'Tarea reasignada a usted',
  'Task Status Updated': 'Estado de la tarea actualizado',
  'Task Updated': 'Tarea actualizada',
  'Task assignments and updates': 'Asignaciones y novedades de las tareas',
  'Status changes': 'Cambios de estado',
  'This is a reminder that your task is due soon.':
    'Recordatorio: su tarea está a punto de vencer.',
  'Your task is now overdue and requires immediate attention.':
    'Su tarea está retrasada y requiere atención inmediata.',
  'This action cannot be undone. This will permanently delete the task from your workspace.':
    'Esta acción no se puede deshacer: la tarea se eliminará definitivamente del espacio de trabajo.',
  'Update the task details below.': 'Actualice los detalles de la tarea a continuación.',
  'Upload Attachment': 'Subir un archivo adjunto',
  'Urgent': 'Urgente',
  'You Were Mentioned': 'Le han mencionado',
  'View Task Now': 'Abrir ahora',
  'View Comment': 'Ver el comentario',
  'View My Tasks': 'Mis tareas',
  'View All Tasks': 'Todas las tareas',
  'View All': 'Ver todo',
  'View Overdue': 'Ver las retrasadas',
  'View': 'Ver',
  'View details & comments': 'Detalles y comentarios',
  'When you have unassigned tasks, click': 'Cuando tenga tareas sin asignar, pulse',

  // --- utenti e permessi ---
  'User Management': 'Gestión de usuarios',
  'User Role': 'Rol del usuario',
  'User account policies and defaults':
    'Reglas y valores predeterminados de las cuentas',
  'User data exported successfully!': 'Datos de los usuarios exportados',
  'User not loaded': 'Usuario no cargado',
  'Users': 'Usuarios',
  'Users can belong to multiple departments':
    'Las personas pueden pertenecer a varios departamentos',
  'Users must be assigned to at least one department':
    'Cada persona debe pertenecer al menos a un departamento',
  'Viewer': 'Solo lectura',
  'View all analytics and reports': 'Ve todos los análisis e informes',
  'View and update their own tasks': 'Ve y actualiza sus propias tareas',
  'View department analytics': 'Ve los análisis del departamento',
  'View your current role and permissions': 'Consulte su rol y sus permisos actuales',
  'Your Access Level': 'Su nivel de acceso',
  'You do not have permission to manage roles': 'No tiene permiso para gestionar los roles',
  'You do not have permission to manage user roles. Only administrators can modify roles and permissions.':
    'No tiene permiso para gestionar los roles: solo los administradores pueden modificarlos.',
  'Update department information and settings':
    'Actualice la información y los ajustes del departamento',
  'Update team member information': 'Actualice la información del miembro del equipo',
  'Update Announcement': 'Actualizar anuncio',
  'Use AI features': 'Usa las funciones de IA',

  // --- riscontri ---
  'Share Feedback Now': 'Dejar un comentario',
  'Share Your Feedback': 'Díganos qué opina',
  'Submit Feedback': 'Enviar el comentario',
  'Suggested Deadline': 'Fecha límite sugerida',
  'Suggestion applied!': 'Sugerencia aplicada',
  'Thank you for your feedback! 🎉': 'Gracias por su comentario',
  'Thank You for Being Part of Our Launch':
    'Gracias por acompañarnos en el lanzamiento',
  'We Need Your Feedback!': 'Necesitamos su opinión',
  'Welcome to your new team productivity platform':
    'Bienvenido a la nueva plataforma de trabajo de su equipo',
  'You must be logged in to submit feedback':
    'Debe iniciar sesión para enviar un comentario',
  'You must be logged in to upvote': 'Debe iniciar sesión para votar',
  'There are no active announcements for your departments':
    'No hay anuncios activos para sus departamentos',
  'Skip Tour': 'Saltar la presentación',
  'Your Achievements': 'Sus logros',

  // --- aiuto ---
  'What are AI Insights?': '¿Qué son los análisis de IA?',
  'What are the different user roles?': '¿Cuáles son los roles de usuario?',
  'What can the AI Assistant do?': '¿Qué puede hacer el asistente de IA?',
  'Yes! In the analytics view, click the': 'Sí. En la vista de análisis, pulse',
  'Yes! Open the task details dialog and go to the':
    'Sí. Abra los detalles de la tarea y vaya a',
  'When enabled, task attachments will be included in notification emails':
    'Si está activo, los archivos adjuntos de las tareas se incluyen en los correos de notificación',
  'Total size of all attachments in a single email cannot exceed this limit':
    'El tamaño total de los archivos adjuntos de un solo correo no puede superar este límite',
  'Show notifications outside the browser': 'Mostrar las notificaciones fuera del navegador',
  'Your browser does not support desktop notifications':
    'Su navegador no admite las notificaciones de escritorio',
  'Your data is automatically saved in your browser. Use':
    'Los datos se guardan automáticamente. Use',
  'Your data is automatically saved in your browser. Use backup to preserve data before major changes.':
    'Los datos se guardan automáticamente. Haga una copia de seguridad antes de cambios importantes.',
  'This will overwrite all existing data. Make sure to export current data first.':
    'Esta operación sobrescribe todos los datos existentes: exporte antes los actuales.',

  // --- errori di runtime ---
  'This spark has encountered a runtime error': 'La aplicación ha encontrado un error',
  'Something unexpected happened while running the application. The error details are shown below. Contact the spark author and let them know about this issue.':
    'Se ha producido un error inesperado. Los detalles aparecen a continuación: comuníquelos a quien gestiona la aplicación.',

  // --- voci sfuggite alla sostituzione automatica ---
  'My Permissions': 'Mis permisos',
  'Avg Completion Time': 'Tiempo medio de finalización',
  'Avg Tasks/Employee': 'Tareas medias por persona',
  'Count': 'Número',
  'Low': 'Baja',
  'Metric': 'Indicador',
  'Total Assigned Tasks': 'Tareas asignadas en total',
  'Value': 'Valor',
  'Generated': 'Generado el',
  'days': 'días',
  'Joined': 'Alta',
  'All': 'Todos',
  'tasks': 'tareas',
  'task': 'tarea',
  'more': 'más',
  'This user has': 'Este usuario tiene',
  'assigned task(s). Those tasks will become unassigned.':
    'tarea(s) asignada(s), que quedarán sin responsable.',
  'This action cannot be undone and any assigned tasks will become unassigned.':
    'Esta acción no se puede deshacer: las tareas asignadas quedarán sin responsable.',
  'active': 'activo',
  'inactive': 'no activo',
  'Feedback Board': 'Tablón de comentarios',
  'Announcements': 'Anuncios',
  'Skills (comma-separated)': 'Competencias (separadas por comas)',
  'Task created successfully!': 'Tarea creada',
  'Task updated successfully!': 'Tarea actualizada',
  'Task reassigned successfully!': 'Tarea reasignada',
  'Task deleted': 'Tarea eliminada',
  'Task completed!': 'Tarea completada',
  'Task status distribution across departments':
    'Distribución de los estados entre los departamentos',
  'Top Clicked Links': 'Enlaces más clicados',
  'Visual reference for department color coding and icons used throughout the app':
    'Referencia visual de los colores y los iconos de los departamentos usados en la aplicación',
  'TaskFlow Help & Documentation': 'Ayuda y documentación',
  'TaskFlow is Production Ready!': 'TaskFlow está listo para producción',
  "Get your webhook URL from Slack's Incoming Webhooks app":
    'Obtenga la URL del webhook en la aplicación Incoming Webhooks de Slack',
  'TaskFlow Analytics - Team Performance Report':
    'TaskFlow - Informe de rendimiento del equipo',
  'TaskFlow Analytics - Department Performance Report':
    'TaskFlow - Informe de rendimiento por departamento',
  '{n}% complete': '{n}% completado',
  '{n} tasks/user': '{n} tareas por usuario',
  '{n} announcements': '{n} anuncios',
  '{n} unassigned': '{n} sin responsable',
  'Last modified: {data} by {autore}': 'Última modificación: {data} por {autore}',
  'Variables': 'Variables',
  'Note:': 'Nota:',
  'Email notifications are sent when enabled in user notification preferences. Variables will be automatically replaced with actual values when emails are sent.': 
    'Los correos de notificación solo se envían si están activados en las preferencias de notificación del usuario. Las variables se sustituyen por los valores reales al enviarlos.',
  'Mention a teammate': 'Mencionar a alguien del equipo',
  'Use the arrow keys to choose, Enter to confirm, Esc to close': 'Flechas para elegir, Intro para confirmar, Esc para cerrar',
  'Press Cmd+Enter to post. Type @ to mention a teammate': 'Cmd+Intro para publicar. Escriba @ para mencionar a alguien',
  'This attachment was blocked because its format is not allowed': 'Archivo bloqueado: el formato no está permitido',
  'Edit comment': 'Editar el comentario',
  'Delete comment': 'Eliminar el comentario',
  'Post comment': 'Publicar el comentario',
  'Download attachment': 'Descargar el archivo',
  'Delete attachment': 'Eliminar el archivo',
  'AI Service': 'Servicio de IA',
  'Available': 'Disponible',
  'Unavailable': 'No disponible',
  'Checking...': 'Comprobando...',
  'Shown in the application header and used in notification emails.': 'Aparece en la cabecera y en los correos de notificación.',
  'Notifications ({count} unread)': 'Notificaciones ({count} sin leer)',
  'Delete notification': 'Eliminar la notificación',
  'Edit task': 'Editar la tarea',
  'Delete task': 'Eliminar la tarea',
  'Select task': 'Seleccionar la tarea',
  'Select {name}': 'Seleccionar a {name}',
  'Skip tour': 'Saltar la introducción',
};
